<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>1,'id'=>243893,'name'=>'1 Stop Camera & Electronics','description'=>'','displayUrl'=>'http://www.1stopcamera.com/','imageUrl'=>'http://cdn.savings.com/logo/1109856.','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>2,'id'=>206452,'name'=>'1&1','description'=>'','displayUrl'=>'http://order.1and1.com/xml/order/Home','imageUrl'=>'http://cdn.savings.com/logo/1115900.gif','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>3,'id'=>5094,'name'=>'1800Contacts','description'=>'Since it was founded in 1995, 1800Contacts has become the world\'s leading contact lens retailer, having fulfilled over 15 million contact lens orders online.
<br>
<br>
In a single day, 1800Contacts sells more contact lenses than 2500 optical retailers and offers the easiest and most convenient way to replace soft or hard contact lenses. Ordering your contacts online is accurate and fast, and 1800Contacts will beat any online price by 2%, so you\'re guaranteed to get a great price. Plus, with a 1800Contacts coupon, discount or promo code from Savings.com, you\'ll save even more on your order.
<br>
<br>
Orders are shipped directly to you from the 1800Contacts warehouse, which has the largest inventory of contacts on the planet, so it\'s almost certain that they will have your exact prescription ready to ship to you in no time. Savings.com has 1800Contacts coupons, 1800Contacts discounts and 1800Contacts promo codes that you can use to increase the savings on the brand name vision you need and trust. 
<br>
<br>
These guys carry over 20 million contacts, making them your number one source for Acuvue, Bausch and Lomb, DuraSoft, PureVision, SofLens, Optima, Focus, Biomedics and many more. In addition to carrying a giant inventory of standard contact lenses, they also carry products like color lenses, bifocal lenses, daily disposables, as well as eye drops, cleaning solutions and contact lens cases.
<br>
<br>
Save the time it would have taken running around town to your optometrist\'s office by filling your contact lens prescription online at <a href=\"http://www.1800contacts.com\">1800Contacts</a>, and save money with a 1800Contacts coupon, 1800Contacts discount or 1800Contacts promo code from Savings.com.','displayUrl'=>'http://www.1800contacts.com','imageUrl'=>'http://cdn.savings.com/logo/1680.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>4,'id'=>5644,'name'=>'1-800 Flowers','description'=>'Established in 1976, 1800Flowers is a leader in the floral delivery industry.  Whether it\'s a breath-taking spring bouquet, a dozen long-stemmed red roses or an exquisite floral arrangement, each delivery shows the thoughtfulness of the giver and brings a smile to its recipient.  A gift of beautiful blossoms from 1800 Flowers is appropriate for any occasion--birthdays, anniversaries, holidays, sympathy, graduation, weddings or just because.  If you want something a bit more original than traditional blooms, you\'ll also find a variety of plants, gift baskets, wine, chocolate and other assorted goodies at 1800Flowers.
<p></p>
One of the first retailers to use a toll-free telephone number, you can place orders 24/7 by dialing 1 800 Flowers or by visiting their website.  If time is of the essence, they have a number of gift ideas available for same day delivery.  1800Flowers guarantees your satisfaction with your floral gift:  if you\'re not completely satisfied, they will either redeliver your order, refund your money, offer a credit towards a future purchase or offer a comparable replacement if the original product is not available.  You save on arrangements, gift baskets and more via their Fresh Rewards program where you accumulate points for every dollar spent at 1800Flowers.  And they offer gift recipients a way to show their appreciation with a free email virtual bouquet back to their sender.
<p></p>
Looking to save money on floral delivery?  Try a 1800Flowers promotion code from Savings.com!  At Savings.com, we scour the web to bring you all the best deals and discounts--like our 1800 Flowers coupons.  So before you finalize your order at <a href=\"http://www.1800flowers.com/\">1800Flowers.com</a>, stop by Savings.com for a 1 800 Flowers coupon code.','displayUrl'=>'http://www.1800Flowers.com','imageUrl'=>'http://cdn.savings.com/logo/2830502.jpeg','allowPartnerDeals'=>'false','categoryIds'=>'Array'),
  array('id_index'=>5,'id'=>256126,'name'=>'1-800 Hotels','description'=>'','displayUrl'=>'http://www.1800hotels.com','imageUrl'=>'http://cdn.savings.com/logo/1506853.gif','allowPartnerDeals'=>'true','categoryIds'=>20890),
  array('id_index'=>6,'id'=>254012,'name'=>'1-800-4Clocks','description'=>'','displayUrl'=>'http://www.1-800-4clocks.com/','imageUrl'=>'http://cdn.savings.com/logo/1502879.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>7,'id'=>251271,'name'=>'1-800 Baskets','description'=>'1-800 Baskets.com, the companion website to 1-800 Flowers, has been offering unique gift  basket creations for several years now. From elaborate gourmet gift ideas to simpler holiday themed gift baskets, they have the ideal package available to suit any event.

The Birthday basket section, for instance, is packed with tasty treats and festive sweets. You can choose from a variety of mouth-watering gift combinations from the delectable Happy Birthday Caramel Apple with candies to the classically scrumptious chocolate dipped strawberries. Tins from the Popcorn Factory, candy bar pretzels, red velvet cheesecake, and Belgian chocolate covered Oreo cookie tins are some of the other sweet tooth enticing choices available on their website. They also carry several birthday baskets of the non-edible variety as well. You can choose to send your friends or loved ones a beautiful spa basket filled with lotions, anti-aging creams, and revitalizing gels. You can also treat yourself and purchase a wooden handle, willow basket Harvest Bounty gift basket filled with Cheryl and Co. chocolate chip cookies, butter toffee popcorn, peanut brittle, crackers and much more. 

1-800 Baskets also offers a wide variety of back to school treats for the college bound student heading far away from home. Send a care package stuffed with Popcorn Factory treats or a Happy Face Cookie Gift Box to lift the pre and post exam spirits of those future philosophers, engineers, and lawyers close to you. Sending them the Giant Confetti Fortune Cookie is another great way to wish them the best of luck in the coming school year or job well done once the academic grind finally screeches to a halt. 

You can also search their site to find the perfect corporate gift basket to send to your boss or favorite retiring co-worker. Beautifully arranged anniversary gift baskets are also available. 

Whether it is housewarming gifts filled with delicious candies and snacks for your parents, friends, or significant others, or perhaps a basket of goodies for an ailing loved one, Savings.com has all of your <a href=\"http://ww11.1800baskets.com/\">1-800 Baskets</a> coupon code needs covered. Search the site for discount rich 1-800 Baskets coupons and promotional codes.','displayUrl'=>'http://www.1800baskets.com/','imageUrl'=>'http://cdn.savings.com/logo/2623185.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8,'id'=>5327,'name'=>'1 800 Florals','description'=>'Founded by the Phillips family in 1923, the 1 800 FLORALS company started as a small family flower shop and has grown to become a thriving global florist with customers in every country of the world. 

We just know you\'ll love its friendly customer service team, 100% satisfaction guarantee, and speedy, same-day delivery service for all of your most important flower arrangements.

At 1 800 FLORALS, you can find fresh bouquets that have flowers to suit every taste, as well as green plants, blooming bushes, romantic roses, and even fruit baskets. If you are shopping for a gift for special occasions, such as birthdays, anniversaries, or even the birth of a new baby, you can browse through a collection of specific floral arrangements designed with your needs in mind.

At Savings.com, we are pleased to offer you <a href=\"http://www.800florals.com\">1 800 FLORALS coupons</a> so you can spend less money on your next big flower purchase, so grab a 1 800 FLORALS coupon today and start saving.','displayUrl'=>'http://www.800florals.com/','imageUrl'=>'http://cdn.savings.com/logo/1684.gif','allowPartnerDeals'=>'true','categoryIds'=>20213),
  array('id_index'=>9,'id'=>229917,'name'=>'1800GetLens','description'=>'1-800-Get-Lens is a leading online supplier of prescription contact lenses and carries all the top brand contacts including Acuvue, Focus, Freshlook, Bausch & Lomb, Cooper Vision. 

With customer in focus, this online store stocks over 5.5 million prescription contact lenses to ensure accurate and fast delivery. 1-800-Get-Lens is a great solution to the high cost and inconvenience of refilling your contact lens prescriptions at your local eye care store.

So if you are a savvy shopper looking for affordable brand name contact lenses or Halloween, Special Effect, FX, Theatrical & Novelty Contact Lenses, then check out the unbelievable prices and massive choice of contact lenses at 1-800-Get-Lens.

For even bigger discounts, be sure to check out our site right here at Savings.com for some of the latest 1-800-Get-Lens coupon codes or <a href=\"http://www.1800getlens.com\">1-800-Get-Lens coupons</a>. So get your discount contact lenses hassle free and delivered at your door step without losing focus on your budget.','displayUrl'=>'http://www.1800getlens.com','imageUrl'=>'http://cdn.savings.com/logo/615849.png','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>10,'id'=>236202,'name'=>'1-800-GO-VAPOR.com','description'=>'','displayUrl'=>'http://www.vapor-systems.com','imageUrl'=>'http://cdn.savings.com/logo/656323.gif','allowPartnerDeals'=>'true','categoryIds'=>20873),
  array('id_index'=>11,'id'=>5367,'name'=>'1800PetMeds','description'=>'If you\'re looking for affordable pet medications, pet supplies, pet accessories and more for your furry friends, then we\'re pretty sure you\'ll like the phenomenal prices and massive selection of products at 1800PetMeds.

These guys have served over 5 million happy customers and carry all the top brands you\'ve come to trust for cats, dogs and even horses, from Frontline and K9 Advantix to Fancy Feast, Natural Balance and more. So whether you\'re shopping for toys, food, grooming products or something else - chances are you\'ll find it at this store and at amazing low prices that are sure to make you smile.

For even better and bigger discounts on top of already low prices, be sure to check out our site right here at Savings.com for some of the latest <a href=\"http://www.1800petmeds.com\">1800PetMeds</a> coupon codes or coupons for 1800PetMeds and get ready to make your pet happy and healthy without having to worry about breaking the bank.','displayUrl'=>'http://www.1800petmeds.com/','imageUrl'=>'http://cdn.savings.com/logo/1685.gif','allowPartnerDeals'=>'false','categoryIds'=>'Array'),
  array('id_index'=>12,'id'=>300995,'name'=>'10 Minute Trainer','description'=>'Most workouts are given bold and elaborate names to cover up their lack of effectiveness, yet 10 Minute Trainer is a workout as straightforward as its name would suggest it is. The main goal of the workout is to give the customer a workout that shows results with only ten minutes of their time per workout session.

The 10 Minute Trainer breakthrough secret in weight-loss technology comes in the form of \"Super Stacking\" resistance bands which boosts the potency of the workout on key parts of the body. The workout is meant to target all important areas of the body simultaneously in order to guarantee success with as little time as possible. The company also provides athletic gear, workout equipment and merchandise as well as their main service.

The 10 Minute trainer program is undoubtedly a great deal, but our addition here at Savings.com of a 10 Minute Trainer coupon and <a href=\"http://www.10minutetrainer.com\">10 Minute Trainer coupon code</a> sweetens the deal even more and makes this workout something that is well worth any customer\'s time.','displayUrl'=>'http://www.10minutetrainer.com','imageUrl'=>'http://cdn.savings.com/logo/2612796.png','allowPartnerDeals'=>'true','categoryIds'=>20884),
  array('id_index'=>13,'id'=>229541,'name'=>'1000bulbs','description'=>'1000Bulbs is an internet-based business, founded by Kim Pedersen who was Consumer Goods\' 2010 Entrepreneur of the Year. The online marketplace offers cutting-edge lighting solutions and specialty lighting for large and small companies and households.

1000Bulbs offers a large choice of light bulbs, ranging from the new efficient LED and metal halide bulbs, which are energy-efficient alternatives to the general or standard light bulbs. The online store provides unbeatable pricing, fast shipping, and odd-shaped replacement bulbs, as well as lighting accessories that are not available at your local home stores. 

Check out the variety of Christmas and rope lighting options for decorating displays or special events. Order online directly or by phone to talk to a specialist that offers recommendations for every lighting need.

Shop at 1000Bulbs using a <a href=\"http://www.1000bulbs.com\">1000Bulbs coupon</a>, so you can save on lighting accessories like dimmers, smoke alarms, and carbon monoxide detectors. Savings.com is the best place to find 1000Bulbs coupons to use on stocking up on special lighting products.','displayUrl'=>'http://www.1000bulbs.com','imageUrl'=>'http://cdn.savings.com/logo/622397.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>14,'id'=>239727,'name'=>'101inks','description'=>'101 Inks is a trusted online source for discount printer ink. Their entire inventory of high quality inks are modestly priced at savings well below normal retail prices. Members of the website receive discount coupons, product updates on their favorite brands, and exclusive offers on replacement toners and inks, cataloged on the site by the printer model to which they correspond. 101inks.com has been supplying name brand ink cartridges online since 2001. They pride themselves on stocking only the finest in top-of-the-line low-cost printer supplies. The website is both secure and user friendly. They carry compatible and re-manufactured inkjet cartridges, laser toners, and accessories suited for a number of top printer brands. These include HP printers, Epson print machines, Dell printers, Xerox, Apple, Kodak, Konica-Minolta, Sharp, Okidata, Pitney Bowes, the Brother lineup of printers, Lexmark, Panasonic, Samsung, Sharp, Canon, and Compaq. 

The website’s customer service department is also quite excellent. Given it’s own section of the website, the customer service department is set up to answer frequently asked questions and to provide timely solutions for defective cartridge issues, explanations of the exchange policy, cartridge troubleshooting, and order placement. They also stand by a one hundred eighty day guarantee that allows customers unsatisfied by the performance and quality of their purchases the opportunity to return those products for a full refund or suitable replacement of their choosing. Order status can also be tracked online via the website in an easy to use manner. 

Certain series of refurbished ink cartridges match up specifically to select printer models. Many of those available at 101 Inks have been thoroughly vetted and tested to assure excellent performance and reliability. The deeply budget priced MagiColor and PagePro series for instance match up perfectly as replacement packs for the Minolta group of printers. Other replacement cartridge styles they carry, designed to suit any type of  ink refill requirement, include the Deskjet, Photosmart, Designjet, Pixma, PanaFax, Dell Color Laser, and ESP series. 

Savings.com carries all the latest <a href=\"http://101inks.com/\" >101 Inks</a> coupons and deals. Search the site for the best 101 Inks coupon codes to assist you in your next inkjet, laser cartridge, or fax toner purchase.','displayUrl'=>'http://101inks.com/','imageUrl'=>'http://cdn.savings.com/logo/952027.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>15,'id'=>206579,'name'=>'101Phones','description'=>'Customers rave about the selection, quality, and service at 101Phones. For over six years 101Phones has been a reliable telephone, headset, and phone accessory dealer on the web. 101Phones is committed to bringing you the best selection phones at a price that won\'t break the bank. You can trust 101Phones to carry all your favorite brands like AT&T, Panasonic, Uniden, VTech, Siemens, and more. 101Phones has cordless, corded, mulit-line, conference, VOIP, and video phones in stock every day. You can also count on 101Phones for fax machines, answering machines, batteries, and headsets at everyday low prices. 
<br><br>
With Savings.com, you can save today and everyday at 101Phones.com with great deals, updated codes, and unbelievable savings. Search Savings.com for 101Phones coupons and 101 Phones codes. We work hard to bring you the best deals and discount on the web--like our 101Phones coupons.  So before you finalize your <a href=\"http://www.101phones.com\">101Phones.com</a> order, get a coupon for 101Phones and ring up a great deal thanks to 101 Phones and Savings.com.','displayUrl'=>'http://www.101phones.com','imageUrl'=>'http://cdn.savings.com/logo/26945.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>16,'id'=>289559,'name'=>'1099FIRE','description'=>'','displayUrl'=>'http://www.1099fire.com/','imageUrl'=>'http://cdn.savings.com/logo/1684217.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>17,'id'=>215905,'name'=>'121TIME','description'=>'Have you ever looked for a watch that suited your personality to a \"T\"? With 121Time custom watch creation service, you can ensure that you have a watch made specifically for you. 121Time is a unique website where you can create your own personalized 121Time Swiss watch. 121Time offers a host of watch options, inluding 121Time shapes, 121Time colors, 121Time materials, and even 121Time gemstones for your perfect 121Time watch. And no matter where in the world you live, 121Time will deliver your custom 121Time Swiss watch in 10 days free. Leave your mark in time with your own custom Swiss watch from 121Time. Looking for 121Time money saving coupons? Well, look no further than Savings.com for the most up to date 121Time coupons on the net. Savings.com is the best place to stop for 121Time promotional codes, 121Time online offers, 121Time coupons and money saving 121Time deals before you shop.','displayUrl'=>'http://www.121time.com','imageUrl'=>'http://cdn.savings.com/logo/1178082.png','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>18,'id'=>249779,'name'=>'123 REFILLS','description'=>'There are many ink and toner supply websites around the internet, but few carry as wide a selection of professionally remanufactured inkjet and laser toner cartridges in stock as 123 Refills. They have upwards of four thousand plus products listed on the site. Their lineup of compatible inkjet cartridges, laserjet cartridges, and laser toner catridges cover several top industry brands. Some of the more notable brand items include Brother, Canon, Dell inkjet cartridges, Epson toner packs, HP cartridges, Kodak, Lexmark, Okidata, Samsung, Xerox, IBM, Apple, Pitney Bowes, Fujitsu, Sanyo, and Toshiba. 

123 Refills utilizes a simple three-step process to assist users in finding the ink and toner refills that will best suit their needs. The first step involves selecting the printer make, then once a list of results have been returned for the printer model, choosing one and then selecting cartridge model. Customers can expect to pay significantly less than the cost of buying original inkjet cartridges and laser toner cartridges also known as OEM ink cartridges. They also offer many refill options such as purchasing the aforementioned remanufactured or compatible sets. Buyers can opt to refill cartridges with in-house brand Uni-Kit ink and toner refill kits. The last option is to purchase Jetpak ink refill mailers to send in your empty cartridges to be filled by 123 Refills technicians.  

The laser toner lineup includes laser toner cartridges, toner refill kits, toner refill accessories, bulk toner, and toner chips and fuses. Other cartridge types available for sale on the website include solid ink Phaser cartridge sticks and ribbon cartridges suitable for use with Murata, Panasonic, and Sharp systems.  The inkjet section contains a wide variety of cartridges, refill kits, postage ink, refill accessories, bulk ink, refilling machines, and continuous ink systems

Savings.com is your one-stop resource for <a href=\"http://www.123refills.net/\" >123 Refills</a> coupons and coupon codes. Search the site for the best deals on toner, printer accessories such as DVD cases, USB and MP3 gadgets, CD and DVD labeling, CD repair kits, photo paper, VHS labels, mobile pen drives, digital photo frames, laser pointer projectors, cell phone and sunglass cases, shipping labels, address labels, and more.','displayUrl'=>'http://www.123refills.net/','imageUrl'=>'http://cdn.savings.com/logo/1483617.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>19,'id'=>235609,'name'=>'123 Security Products','description'=>'','displayUrl'=>'http://www.123securityproducts.com/','imageUrl'=>'http://cdn.savings.com/logo/630331.gif','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>20,'id'=>5446,'name'=>'123Inkjets','description'=>'Having sold more than 5 million ink cartridges, 123InkJets has the experience to deliver quality printer cartridges. 123InkJets handles their own fulfillment, which ensures you receive the highest quality 123InkJets ink and laser toner cartridges at the best 123InkJets prices. 123InkJets can\'t be beat for selection, including ink cartridges, laser toners, ribbons, and solid ink. You can even find a great array of paper, CDs, DVDs, and printer cables at 123InkJets. Concerned about the environment, 123InkJets makes it easy to recycle your used ink cartridges with the 123InkJets recycling program. Free shipping and a 1-year guarantee should make <a href=\"http://www.123Inkjets.com\">123InkJets</a> your only source for printer ink. Savings.com can help bring low 123InkJets prices even lower. Check Savings.com for 123InkJets computer coupons, 123InkJets online deals, 123InkJets special offers, and 123InkJets rebates and discounts. At Savings.com, we update our great 123InkJets promotional code, offers, codes, and promotional codes regularly, so check back often for the latest 123InkJets promotion codes, promotions, and specials.','displayUrl'=>'http://www.123Inkjets.com','imageUrl'=>'http://cdn.savings.com/logo/27166.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>21,'id'=>321286,'name'=>'123language.com','description'=>'','displayUrl'=>'http://www.123language.com/','imageUrl'=>'http://cdn.savings.com/logo/2824466.png','allowPartnerDeals'=>'true','categoryIds'=>20894),
  array('id_index'=>22,'id'=>238020,'name'=>'123 Print','description'=>'123 Print provides customers with the opportunity to imprint their own personal style on everything from business cards to wedding invitations, flyers, letterheads and more.<p> 

With the ability to customize letterhead, mailing labels, greeting cards, envelopes, banners, magnets and more, 123 Print offers quality printing at affordable prices. Full color, free photo and logo uploads and completely personalized papers and products allow you to more easily express your personal style or the design of your business with 123 Print – all at affordable prices that are sure to make you smile and help keep your budget in check.<p>  

Although 123 Print caters to small business owners with a wide variety of customizable stationery and office supplies, brides-to-be will find 123 Print to be the perfect one-stop shop for wedding invitations and more.  Create the perfect look for your wedding with 123 Print save the date cards, wedding invitations, RSVP cards and thank you cards. Make that perfect day even more wonderful with affordable wedding invitations that’ll save you money without forcing you to cut back on quality.<p>

123 Print has dozens of templates and their design tips and design tool will help you generate professional looking cards, flyers and brochures. Plus, you can save up to an extra 30% off services and products with 123 Print coupons and 123 Print coupon codes, as well as score free shipping on orders of $35 or more and other great promotions.<p>

Want to save even more on 123 Print\'s already great pricing?  Look for 123Print coupon codes at Savings.com.  With 123 Print coupons from Savings.com, you not only customize your print design but your printing price as well!  Savings.com has the best deals and discounts on the web - like our coupons for 123 Print.  So before you finalize your order at <a href=\"http://www.123print.com\">123 Print</a>, head  to Savings.com for the latest and greatest in 123 Print coupon codes.','displayUrl'=>'http://www.123print.com','imageUrl'=>'http://cdn.savings.com/logo/764857.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>24,'id'=>279016,'name'=>'123Together.com','description'=>'','displayUrl'=>'http://www.123together.com/','imageUrl'=>'http://cdn.savings.com/logo/1657587.png','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>25,'id'=>245266,'name'=>'1800Mattress','description'=>'From its humble beginnings over 30 years ago as Dial-a-Mattress, 1800Mattress has become a household name.  Since 1976, 1-800-Mattress has served over two million customers, helping each one to find the right mattress for a good night\'s sleep.  Sealy, Serta, Simmons, Stearns and Foster, Tempur-Pedic are just some of the top mattress brands carried by 1800Mattress.com.  1800Mattress also offers latex mattresses, memory foam mattresses, organic mattresses and futons in a variety of comfort levels from ultra plush to extra firm.  With an inventory that includes boxsprings, bed frames, mattress pads, sheets, pillows and more, 1-800-Mattress aims to be your complete bedding superstore.  You\'ll find competitive prices, excellent customer service, efficient delivery and a free return guarantee at 1800Mattress.com, so start shopping for your new mattress today!

Want to save money on your 1800Mattress purchase?  Check out the 1800Mattress coupons at Savings.com.  With 1800Mattress coupons courtesy of Savings.com, you\'ll sleep even better on that new 1-800-Mattress knowing that you there\'s extra cash leftover from your purchase.  So before you finalize your order at <a href=\"http://www.mattress.com\">1800Mattress.com</a>, look for 1-800-Mattress coupons and 1800Mattress deals and discounts at Savings.com.','displayUrl'=>'http://www.mattress.com','imageUrl'=>'http://cdn.savings.com/logo/2682691.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>26,'id'=>495011,'name'=>'1800businesscards.com','description'=>'','displayUrl'=>'http://www.1800businesscards.com/','imageUrl'=>'http://cdn.savings.com/logo/2935956.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>27,'id'=>238804,'name'=>'1800eMart','description'=>'','displayUrl'=>'http://www.1800emart.com','imageUrl'=>'http://cdn.savings.com/logo/770868.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>28,'id'=>5624,'name'=>'1800Mobiles','description'=>'Log on to 1-800 Mobiles for anything you could ever want in a cell phone.  1-800 Mobiles not only offers name brand cell phones and major carrier cellular plans, but 1-800 Mobiles offers the best pricing, savings, and more online at 1-800 Mobiles. 1-800 Mobiles provides a one-stop shop for cell phones and cellular phone accessories. 1-800 Mobiles can help you secure the right cell phone for you. 1-800 Mobiles simply can\'t be beat for Cingular, T-Mobile, Nextel, Verizon, Sprint, and more. Plus, 1-800 Mobiles offers real customer phone reviews and Bluetooth accessories. Savings.com brings 1-800 Mobiles already low prices even lower. Click on to Savings.com for 1-800 Mobiles incentives, 1-800 Mobiles coupons, 1-800 Mobiles online coupons, 1-800 Mobiles specials, and 1-800 Mobiles deals. At Savings.com, getting 1-800 Mobiles promotional codes, 1-800 Mobiles codes, 1-800 Mobiles code, and 1-800 Mobiles promotional code is a snap!','displayUrl'=>'http://www.1800mobiles.com/','imageUrl'=>'http://cdn.savings.com/logo/1665247.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>29,'id'=>238425,'name'=>'1800Pools','description'=>'When it\'s time to cool off in your backyard pool, or relax in your spa, 1800Pools has everything you need to keep your pools, spas, and ponds healthy and happy. We know that the professionals here, with over 150 years combined experience in the pool industry, will make sure that you get the products you need to keep swimming all season long.

At 1800Pools, you\'ll find items like the Hayward Underwater Inground Pool Lighting System, which has fun, energy-saving LED lights for a great nighttime atmosphere. When it\'s time to open your pool, choose a HassleFree Start-Up kit, or use a Salt Water Magic kit to cut your chlorine requirements. For when it\'s just too cold to swim, you can find great winter-weather items here like NiceRink backyard ice rink kits, Mountain Boy kicksleds, and pre-lit artificial Christmas trees.

You can receive exclusive deals and discount offers by signing up for their Crazylegs Savings Club, and to find a current <a href=\"http://www.1800pools.com\">1800Pools coupon</a> right now, check here at Savings.com, the best place to find 1800Pools coupons and codes.','displayUrl'=>'http://www.1800pools.com','imageUrl'=>'http://cdn.savings.com/logo/766498.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20736),
  array('id_index'=>30,'id'=>311125,'name'=>'1800postcards','description'=>'$model.description','displayUrl'=>'http://www.1800postcards.com','imageUrl'=>'http://cdn.savings.com/logo/2824788.gif','allowPartnerDeals'=>'true','categoryIds'=>20854),
  array('id_index'=>31,'id'=>301142,'name'=>'1840s Carrollton Inn','description'=>'','displayUrl'=>'http://www.1840scarrolltoninn.com/specials_baltimore_fells_point_hotel_inn_md.php','imageUrl'=>'http://cdn.savings.com/logo/2613482.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20890),
  array('id_index'=>32,'id'=>287712,'name'=>'1888PressRelease','description'=>'','displayUrl'=>'http://www.1888pressrelease.com/','imageUrl'=>'http://cdn.savings.com/logo/1668617.png','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>33,'id'=>286565,'name'=>'1888Toys.com','description'=>'','displayUrl'=>'http://www.1888toys.com/','imageUrl'=>'http://cdn.savings.com/logo/1666212.png','allowPartnerDeals'=>'true','categoryIds'=>20237),
  array('id_index'=>34,'id'=>285094,'name'=>'1928.com','description'=>'','displayUrl'=>'http://www.1928.com/','imageUrl'=>'http://cdn.savings.com/logo/1664727.png','allowPartnerDeals'=>'true','categoryIds'=>20823),
  array('id_index'=>35,'id'=>296044,'name'=>'1cheapstore','description'=>'','displayUrl'=>'http://www.1cheapstore.com','imageUrl'=>'http://cdn.savings.com/logo/1875755.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>36,'id'=>237378,'name'=>'1LAP2GO','description'=>'','displayUrl'=>'http://www.1lap2go.com/','imageUrl'=>'http://cdn.savings.com/logo/731568.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20882),
  array('id_index'=>37,'id'=>288689,'name'=>'1st Choice Apparel','description'=>'','displayUrl'=>'http://www.1stchoiceapparel.com','imageUrl'=>'http://cdn.savings.com/logo/1670730.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>38,'id'=>240606,'name'=>'1ST ERGO','description'=>'','displayUrl'=>'http://www.1stergo.com','imageUrl'=>'http://cdn.savings.com/logo/1014800.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>39,'id'=>238885,'name'=>'1st in Coffee','description'=>'1st in Coffee offers espresso machines and coffee makers by Capresso, La Pavoni, Nespresso, Jura, Elektra, Pasquini and Saeco.','displayUrl'=>'http://www.1stincoffee.com/?source=bizrate','imageUrl'=>'http://cdn.savings.com/logo/789582.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20861),
  array('id_index'=>40,'id'=>290751,'name'=>'1st Phorm','description'=>'','displayUrl'=>'http://www.1stphorm.com','imageUrl'=>'http://cdn.savings.com/logo/1695847.gif','allowPartnerDeals'=>'true','categoryIds'=>20857),
  array('id_index'=>41,'id'=>236164,'name'=>'1st Quality School Supplies','description'=>'','displayUrl'=>'http://www.1st-quality-school-supplies.com','imageUrl'=>'http://cdn.savings.com/logo/1505996.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>42,'id'=>243068,'name'=>'1st Warehouse','description'=>'','displayUrl'=>'http://1stwarehouse.com','imageUrl'=>'http://cdn.savings.com/logo/1506488.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20729),
  array('id_index'=>43,'id'=>238861,'name'=>'1STOPlighting - Your lighting superstore','description'=>'','displayUrl'=>'http://www.1stoplighting.com','imageUrl'=>'http://cdn.savings.com/logo/785420.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20875),
  array('id_index'=>44,'id'=>245243,'name'=>'1st Wishes','description'=>'Most people get a fair amount of birthdays over the course of a lifetime, but there\'s something very special about turning one.  1st Wishes realizes that you only get to celebrate your first birthday once, so they have everything that is needed to make that party extra special.  With over thirty party themes to choose from, they specialize in commemorating the momentous occasion.  1stWishes has animal and insect themes, sports, sports and vehicle, princess and dolls--whatever your tiny tot\'s heart desires!  You can even personalize your chosen theme with favorite photo, personal message, font, color and image options.  
<br /><br />
Party packages include balloons and decorations, favors and toys, tableware, invitations and more and with 1st Wishes Ultimate Party Pack, you get everything you need to put together perfect. The only thing missing is the cake!   They also have party supplies for 2nd birthdays, big kids parties and even adults.  Every purchase you make at 1stWishes.com is backed by their 100% satisfaction guarantee--so what are you waiting for!  Celebrate that milestone birthday with party decorations and supplies from 1st Wishes.
<br /><br />
Looking to save money on your kids birthday party supplies?  Try a 1stWishes coupon from Savings.com.  At Savings.com, we scour the web to bring you all the best deals and discounts--like our 1st Wishes coupons.  So before you finalize your order at <a href=\"http://www.1stwishes.com\">1stWishes.com</a>, stop by Savings.com for a 1st Wishes coupon.','displayUrl'=>'http://www.1stwishes.com/','imageUrl'=>'http://cdn.savings.com/logo/1178084.png','allowPartnerDeals'=>'true','categoryIds'=>20878),
  array('id_index'=>45,'id'=>239994,'name'=>'2 Days Bargain','description'=>'','displayUrl'=>'http://www.2daysbargain.com/','imageUrl'=>'http://cdn.savings.com/logo/998347.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>46,'id'=>298269,'name'=>'2 Little Chicks','description'=>'','displayUrl'=>'http://www.2littlechicks.com/','imageUrl'=>'http://cdn.savings.com/logo/2605539.png','allowPartnerDeals'=>'true','categoryIds'=>20237),
  array('id_index'=>47,'id'=>298376,'name'=>'2010 NY Comic Con','description'=>'','displayUrl'=>'http://www.newyorkcomiccon.com','imageUrl'=>'http://cdn.savings.com/logo/2601478.png','allowPartnerDeals'=>'true','categoryIds'=>20832),
  array('id_index'=>48,'id'=>306967,'name'=>'20x200','description'=>'20x200 is a website that sells art to the online public from various independent artists in several size selections for affordable prices, with choices and styles for everyone.

The art on 20x200 are all limited first editions for low prices, so not only do you get a great piece of art for cheap, but since they are all offered in limited quantities, you get a unique piece as well. 

Through 20x200, you can use their browse feature to look for specific artists work that you like, search for soon sold out pieces with limited quantity in stock, the date it was created, allowing you to get the latest and greatest pieces of art, it even allows you to search by price if you\'re looking for great art on an even tighter budget.

If you\'re looking for great art for even cheaper than advertised, get a <a href=\"http://www.20x200.com\">20x200 coupon code</a> check out Savings.com and pick up a great 20x200 coupon to pick up a great piece for even cheaper.','displayUrl'=>'http://www.20x200.com','imageUrl'=>'http://cdn.savings.com/logo/2624653.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>49,'id'=>307988,'name'=>'24 Hour Canvas','description'=>'','displayUrl'=>'http://www.24hourcanvas.com','imageUrl'=>'http://cdn.savings.com/logo/2732573.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20868),
  array('id_index'=>50,'id'=>228929,'name'=>'24 Hour Fitness','description'=>'Despite its humble origins as a single sports club in 1983, 24 Hour Fitness has expanded to become a leading sports club in the US and in other parts of the world. Mark S. Mastrov, chairman of 24 Hour Fitness Worldwide, took that single club and turned it into 385 clubs worldwide with upwards of three million members. Mastrov wanted to create a multi-sport club that was affordable (made even more affordable with a 24 Hour Fitness coupon code or a 24 Hour Fitness discount code from Savings.com), suited to users of all fitness and ability levels, and filled with the top of the line fitness machines and equipment. Through strategic partnerships with celebrity athletes and through a lot of television coverage on NBC\'s \"The Biggest Loser,\" 24 Hour Fitness has become a widely recognizable brand. All of these efforts are to one end: \"to make fitness a way of life for everyone.\" With a 24 Hour Fitness coupon code, a 24 Hour Fitness promo code, or a 24 Hour Fitness discount code, making fitness a way of life will be less expensive than you\'d expect.<br><br>

If you\'re one of many that need a group environment in order to be motivated to work out, 24 Hour Fitness offers a wide variety of group classes to suit the workout preferences of almost anyone. Whether you\'re into cardio or lifting, aerobics or yoga, 24 Hour Fitness will have a class that\'s right for you. Without a gym membership, classes like these could cost you an arm and a leg, but with a 24 Hour Fitness coupon code or a 24 Hour Fitness discount code from Savings.com, it will cost you far less than you\'d think. If you prefer to work out solo, 24 Hour Fitness provides the highest quality workout machines, free weights, pools, spas, and steam rooms at many of their locations. You can do research into clubs in your area online, and you can even sign up for membership through 24 Hour Fitness online. By signing up online, you can save on their already affordable membership fees with a 24 Hour Fitness coupon code or a 24 Hour Fitness discount code. <br><br>

Before you checkout at <a href=\"http://www.24hourfitness.com\">24 Hour Fitness</a> online, take a moment to search Savings.com for a 24 Hour Fitness coupon code or a 24 Hour Fitness discount code. When you\'re checking out, simply enter the 24 Hour Fitness coupon code or the 24 Hour Fitness discount code when you\'re prompted, and you\'ll see your savings. Join one of the most reputable and popular gyms in the country, and in the world, and get fit for less than you\'d expect by using a 24 Hour Fitness coupon code or a 24 Hour Fitness discount code from Savings.com.','displayUrl'=>'http://www.24hourfitness.com/','imageUrl'=>'http://cdn.savings.com/logo/439666.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>51,'id'=>266843,'name'=>'24 Hour Tax','description'=>'','displayUrl'=>'http://www.24hourtax.com/','imageUrl'=>'http://cdn.savings.com/logo/1612035.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>52,'id'=>259152,'name'=>'24/7 Office Hours','description'=>'','displayUrl'=>'http://www.247officehours.com/','imageUrl'=>'http://cdn.savings.com/logo/1530715.png','allowPartnerDeals'=>'true','categoryIds'=>20828),
  array('id_index'=>53,'id'=>258753,'name'=>'247 Market Place','description'=>'','displayUrl'=>'http://www.247marketplace.com','imageUrl'=>'http://cdn.savings.com/logo/1527584.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>54,'id'=>315958,'name'=>'25net.us','description'=>'','displayUrl'=>'http://www.facebook.com/pages/Once-a-Marine-Always-a-Marine/114854548579007','imageUrl'=>'http://cdn.savings.com/logo/2813109.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20838),
  array('id_index'=>55,'id'=>380278,'name'=>'2 Cute Lingerie','description'=>'','displayUrl'=>'http://www.2cutelingerie.com/','imageUrl'=>'http://cdn.savings.com/logo/2912137.png','allowPartnerDeals'=>'true','categoryIds'=>20824),
  array('id_index'=>56,'id'=>309803,'name'=>'2insure4less','description'=>'','displayUrl'=>'http://insurance63.com/x/0/210/21447/','imageUrl'=>'http://cdn.savings.com/logo/2629766.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>57,'id'=>279365,'name'=>'2kTshirts','description'=>'Wear your art on your chest with the range of men and women\'s t-shirts from 2kTshirts at 2K by Gingham, the home of unique, art-expressive t-shirts from big brand names such as Bob Kronbauer, Damion Silver, Reluctant Hero and William Lemon.

Register with 2kTshirts to receive their email newsletter packed with the latest new designs and exclusive offers; you can even save your own wish list on the site so you need never forget about a great t-shirt again. 

If you can\'t decide which of the 2kTshirts to go for, why not take pot luck and order a grab bag containing a random selection of either 3 or 10 t-shirt designs, and because everybody loves t-shirts you\'ll never be short of a gift idea with gift vouchers available up to the value of $500.

Grab yourself a 2kTshirts discount code from Savings.com; free to use every day you could make great savings using a <a href=\"http://www.2ktshirts.com\">2kTshirts discount code</a> and your only problem will be what t-shirt to wear today.','displayUrl'=>'http://www.2ktshirts.com/drupal/','imageUrl'=>'http://cdn.savings.com/logo/1657621.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>58,'id'=>235903,'name'=>'2mcctv','description'=>'','displayUrl'=>'http://www.2mcctv.com','imageUrl'=>'http://cdn.savings.com/logo/635526.gif','allowPartnerDeals'=>'true','categoryIds'=>20844),
  array('id_index'=>59,'id'=>285097,'name'=>'2STONER','description'=>'','displayUrl'=>'http://www.2stoner.com','imageUrl'=>'http://cdn.savings.com/logo/1664599.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>60,'id'=>250032,'name'=>'3 Arts Healing','description'=>'','displayUrl'=>'http://www.3artshealing.com/','imageUrl'=>'http://cdn.savings.com/logo/1483594.png','allowPartnerDeals'=>'true','categoryIds'=>20734),
  array('id_index'=>61,'id'=>208115,'name'=>'3Balls','description'=>'Although 3Balls wasn\'t incorporated until 2000, the business-savvy behind the strange appellation has over twenty years experience.  From modest beginnings as a discount golf pro shop, 3 Balls Golf quickly grew to specialize in offering the best used and like new golf clubs and equipment available.  In addition, golfing aficionados can score golf shoes, bags, clothing and--of course--golf balls at 3Balls com from top brands like Adidas, Callaway, Mizuno, TaylorMade, Titleist and Nike.  Whether you\'re looking to add a new driver, iron, putter or wedge to your golf club arsenal or searching for hard-to-find golfing equipment specifically made for lefties, women or junior players, 3 Balls has you covered.
Customer service has always been top priority for 3Balls and so you can expect consistent excellence along with no sales tax (except in MA), same day shipping, 100% authenticity, 30-day no-hassle returns and 100% satisfaction guaranteed.  3Balls.com allows for easy online shopping with the ability to shop by product category, brand, model, price and more.  If you need a Callaway Big Bertha Diablo driver or Mizuno MP-57 irons or Cleveland CG14 Camo wedges, you\'ll find it at 3 Balls Golf.  And if you\'re looking to save money on your golf equipment and apparel purchase then look no further than the 3Balls coupons from Savings.com.  
Savings.com is your source for the best deals and discounts on the web--like our 3 Balls Golf coupons.  So before you finalize your order at 3Balls.com, stop by Savings.com for 3Balls com coupon code.  Even if you can\'t shave strokes off your score, you can shave dollars off your purchase with the great coupons and codes from Savings.com.','displayUrl'=>'http://www.3balls.com','imageUrl'=>'http://cdn.savings.com/logo/27139.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>62,'id'=>236644,'name'=>'360 Pros','description'=>'','displayUrl'=>'http://www.360-pros.com','imageUrl'=>'http://cdn.savings.com/logo/1506575.gif','allowPartnerDeals'=>'true','categoryIds'=>20229),
  array('id_index'=>63,'id'=>296464,'name'=>'360Tuners','description'=>'','displayUrl'=>'http://www.360tuners.com','imageUrl'=>'http://cdn.savings.com/logo/2237771.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>64,'id'=>301222,'name'=>'365Hangers','description'=>'','displayUrl'=>'http://www.365hangers.com/','imageUrl'=>'http://cdn.savings.com/logo/2614451.png','allowPartnerDeals'=>'true','categoryIds'=>20822),
  array('id_index'=>65,'id'=>299097,'name'=>'39 Steps Off-Broadway Tickets','description'=>'','displayUrl'=>'http://39stepsny.com','imageUrl'=>'http://cdn.savings.com/logo/2605065.gif','allowPartnerDeals'=>'true','categoryIds'=>20832),
  array('id_index'=>66,'id'=>6929,'name'=>'39 dollar glasses','description'=>'A group of respected optometrists created 39 Dollar Glasses to provide you with high-quality, name brand prescription eyeglasses for children and adults at a significantly reduced price. We just know you\'ll love the company\'s knowledgeable customer service team that is always available to give you expert advice on your next eyeglasses purchase.

39 Dollar Glasses offers a wide range of popular, stylish brands in eyeglasses, including Transitions, Varilux, Optical Dynamics, Carl Zeiss Vision, Seiko, NuPolar, and many more. You can also pick up some chic sunglasses that have metal, plastic, bendable titanium, rimless, or semi-rimless frames, and don\'t forget their wide range of child-sized prescription glasses and sunglasses for the little ones in your life.

At Savings.com, we know that spending less money on your next purchase of eyeglasses at 39 Dollar Glasses is very important to you, so pick up a <a href=\"http://www.39dollarglasses.com\">39 Dollar Glasses coupon</a> or even several 39 Dollar Glasses coupons and start saving today.','displayUrl'=>'http://www.39dollarglasses.com','imageUrl'=>'http://cdn.savings.com/logo/27192.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>67,'id'=>302450,'name'=>'3D Laser Gifts','description'=>'','displayUrl'=>'http://www.3dlasergifts.com','imageUrl'=>'http://cdn.savings.com/logo/2618352.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20213),
  array('id_index'=>68,'id'=>318227,'name'=>'3D Products','description'=>'','displayUrl'=>'http://www.3dproducts.com/','imageUrl'=>'http://cdn.savings.com/logo/2819829.png','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>69,'id'=>238772,'name'=>'3K Wholesale.com !','description'=>'','displayUrl'=>'http://www.3kwholesale.com','imageUrl'=>'http://cdn.savings.com/logo/1506595.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20870),
  array('id_index'=>70,'id'=>311022,'name'=>'3KissesLingerie','description'=>'','displayUrl'=>'http://www.3KissesLingerie.com','imageUrl'=>'http://cdn.savings.com/logo/2683405.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>71,'id'=>298156,'name'=>'3M','description'=>'3M is a trusted household name when it comes to reliable home & office products. This Minnesota-based company produces more than 55,000 quality products for home, office or industrial use.

You\'re probably familiar with the 3M line of Post-Its and Scotch tape dispensers. 3M also manufactures automotive products for detailing your car and offers hard wood floor maintenance products for keeping your hard wood floors shiny and in top shape. 

The line of fire protection equipment will keep your home or office safe from noxious gases or the spread of flame. The Nexcare First Aid products use premium materials to provide comfort when you\'re hurt. The Scotch-Brite line of reliable cleaning products makes it easier to remove grease and grime anywhere from the industrial kitchen to your home.

With a <a href=\"http://www.shop3m.com\">3M coupon</a> you\'re guaranteed to save on top quality products. Be sure to check Savings.com often for the latest and greatest in 3M coupons.','displayUrl'=>'http://www.shop3m.com/','imageUrl'=>'http://cdn.savings.com/logo/2600425.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>72,'id'=>251368,'name'=>'3tailer','description'=>'','displayUrl'=>'http://www.3tailer.com','imageUrl'=>'http://cdn.savings.com/logo/2086510.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>73,'id'=>235527,'name'=>'42nd St Photo','description'=>'Located in New York, 42Photo.com offers a wide selection of computer and electronics items, including DVDs, cameras, televisions, VCRs, and more.','displayUrl'=>'http://www.42photo.com','imageUrl'=>'http://cdn.savings.com/logo/626468.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>74,'id'=>322150,'name'=>'42nd Street Photo','description'=>'','displayUrl'=>'http://www.42photo.com/','imageUrl'=>'http://cdn.savings.com/logo/2822986.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>75,'id'=>230234,'name'=>'48HourPrint','description'=>'','displayUrl'=>'http://www.48hourprint.com/','imageUrl'=>'http://cdn.savings.com/logo/614191.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>76,'id'=>238325,'name'=>'48 Long Stems','description'=>'The founder of 48 Long Stems began their business venture as a curbside vendor in West Palm Beach, Florida, opening a stand on Valentine\'s Day in 2001 and selling around 1,000 roses. Now, the little curbside stand has developed into a nationwide business offering flowers to consumers across the country.

Although the founder of the company began with just selling roses, the corporation now presents customers with a wide selection of flowers and gifts, with the intent to keep extending their product line. On the 48 Long Stems website, consumers can find flowers like Peruvian Lilies, Sunflowers, and Gerber Daisies, or gifts such as chocolate gift baskets, gourmet coffee, and bath and body sets.

If you\'re interested in buying flowers or gifts but feel like high prices are a thorn in your side, we at Savings.com offer the most current <a href=\"http://www.48longstems.com\">48 Long Stems coupons</a> so get ready to stop and smell the roses and enjoy your savings with the 48 Long Stems coupon you picked.','displayUrl'=>'http://www.48longstems.com','imageUrl'=>'http://cdn.savings.com/logo/1018207.png','allowPartnerDeals'=>'true','categoryIds'=>20853),
  array('id_index'=>78,'id'=>5751,'name'=>'4AllMemory','description'=>'Is your computer running slow? Chances are that your memory is out of date, and you need to upgrade your computer memory with 4 All Memory. 4 All Memory are the memory professionals. When you log onto 4 All Memory you can find the right memory that is 100% compatible with your computer, guaranteed! 4 All Memory can also check your hard drive to see which upgrades will work with your system. Check out the fantastic selection of 4 All Memory RAM, including 4 All Memory desktop memory, 4 All Memory notebook memory, 4 All Memory DDR memory, 4 All Memory Rambus memory, and more. Plus, 4 All Memory carries 4 All Memory USB flash drives, 4 All Memory camera memory, and 4 All Memory video cards. Take a look at Savings.com list of 4 All Memory coupons to save you cash. Savings.com updates their 4 All Memory coupons, 4 All Memory promotional codes, 4 All Memory specials, and 4 All Memory offers regularly, so check in often.','displayUrl'=>'http://www.4allmemory.com','imageUrl'=>'http://cdn.savings.com/logo/1688.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>79,'id'=>295837,'name'=>'4AllVitamins.com','description'=>'','displayUrl'=>'http://www.4AllVitamins.com','imageUrl'=>'http://cdn.savings.com/logo/1795655.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>80,'id'=>248122,'name'=>'4checks','description'=>'Ordinary checks are predictable and boring, but most fancy and fun checks are over the top and tacky. The mission of 4checks is to provide their customers with playful and whimsically designed checks that are both practical and fun to show off.

Customers can choose from a diverse range of checks which includes the original basic blue check, artistic landscape designs and everything in between. The more decorative checks come in elaborate geometric patterns as well as simple but bold designs. 

The character checks offer something for any user of any age to smile at. Every character conceivable from Iron Man and the Marvel Heroes to Strawberry Shortcake is pressed onto the surface of these checks.

A deal as great as the ones offered by 4checks is something incredible enough to come by, but Savings.com offers great <a href=\"http://www.4checks.com\">4checks coupon</a> packages with a variety of 4checks coupons so you can get your personal checks today.','displayUrl'=>'http://www.4checks.com/','imageUrl'=>'http://cdn.savings.com/logo/1187855.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>81,'id'=>293267,'name'=>'4FocusGraphics.com','description'=>'','displayUrl'=>'http://retail.4focusgraphics.com/','imageUrl'=>'http://cdn.savings.com/logo/1718932.png','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>82,'id'=>298609,'name'=>'4 Fun Parties','description'=>'The next time you are planning an event, 4 Fun Parties features decorations, noisemakers, novelties, party hats and more, that we know will make your next theme party a memorable occasion. 

Here you will discover unique items from all your favourite characters here, like Harry Potter, Sponge Bob Squarepants, Batman and Mickey Mouse, or plan a milestone birthday with the Sweet 16 and Over The Hill collections.

Great holiday celebrations are made at 4 Fun Parties, where you\'ll find straw sombreros and genuine maracas for an authentic Cinco De Mayo fiesta, and red money envelopes and chopsticks for your next lucky Chinese New Year party. With free ground shipping on orders over $39 from 4 Fun Parties, we know that shopping here will save you time and money, making planning your next event stress-free and fun.

When you are in the mood to celebrate for any occasion, be sure to stretch your party budget with a <a href=\"http://www.4funparties.com\">4FunParties coupon</a> from Savings.com, the best place for a 4 Fun Parties coupon or discount code.','displayUrl'=>'http://www.4funparties.com/','imageUrl'=>'http://cdn.savings.com/logo/2603046.png','allowPartnerDeals'=>'true','categoryIds'=>20825),
  array('id_index'=>83,'id'=>206351,'name'=>'4inkjets','description'=>'4inkjets.com is one of the leaders in the ink supplying business.We guarantee you that you don\'t even have to look somewhere else because 4inkjets.com carries a complete line of printer inkjet cartridges, inkjet refill kits, laser toner, fax toner and countless other printer supplies. The best brands on the market are available: HP, Dell, Canon, Epson...

We have great news for you. You will get the best prices and customer service than any other competitor. The company has received the Bizrate Platinum Circle of Excellence Award for the 6th consecutive year.

We highly recommend that you get some 4inkjets coupon codes that will let you buy at discount prices online. If you connect now to our website, Savings.com, you will also be able to spend less on your purchases by getting <a href=\"http://www.4inkjets.com\">4inkjets coupons</a>. This offer will end soon, so don\'t wait too long.

We care about your wallet and 4inkjets.com is the best example of high quality services along with low prices.','displayUrl'=>'http://www.4inkjets.com','imageUrl'=>'http://cdn.savings.com/logo/634038.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>84,'id'=>260152,'name'=>'4Luggage.com','description'=>'Based in Quincy, Illinois, 4Luggage.com has been providing its customers with top-quality luggage, hand bags and travel accessories for over 35 years. You\'ll love the website\'s price matching policy, exclusive Rewards Dollars program, and the great financing options that are available if you\'re on a tight budget.

If you are looking for sturdy, yet stylish, luggage to take on your next vacation or business trip, you can browse through 4Luggage.com\'s collection of duffel bags and luggage sets, which include brand names such as Adidas, Eagle Creek, Briggs & Riley, Nike, and Wilson. If you are just trying to find a snazzy purse to complete your outfit or a reliable briefcase to hold important work, you can also find those items there at bargain prices.

Here at Savings.com, we are pleased to provide many <a href=\"http://www.4luggage.com\">4Luggage.com coupons</a> that can help you get some extra money off your next luggage purchase, so pick up some great 4Luggage.com coupons here today.','displayUrl'=>'http://www.4luggage.com/','imageUrl'=>'http://cdn.savings.com/logo/1534266.gif','allowPartnerDeals'=>'true','categoryIds'=>20894),
  array('id_index'=>85,'id'=>278159,'name'=>'4mags.com','description'=>'','displayUrl'=>'http://www.4mags.com/','imageUrl'=>'http://cdn.savings.com/logo/1656284.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20724),
  array('id_index'=>86,'id'=>248520,'name'=>'4MD Medical Solutions','description'=>'','displayUrl'=>'http://www.4mdmedical.com','imageUrl'=>'http://cdn.savings.com/logo/1506647.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>87,'id'=>252686,'name'=>'4Media Software Studio','description'=>'','displayUrl'=>'http://www.mp4converter.net/','imageUrl'=>'http://cdn.savings.com/logo/1496340.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>88,'id'=>476786,'name'=>'4rsgold.com','description'=>'','displayUrl'=>'http://www.4rsgold.com/','imageUrl'=>'http://cdn.savings.com/logo/2935048.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20895),
  array('id_index'=>89,'id'=>219437,'name'=>'4WheelParts','description'=>'With over 50 years in the business, 4WheelParts is the place to go for all the truck and jeep accessories you want. With everything from brakes to lift and suspension kits, these guys know their stuff. All the top brands are here, including ProComp, Smittybilt, Go Rhino and Magnaflow Exhaust, so you know you\'re buying the best.

With free UPS shipping on most US orders over $75, 4 Wheel Parts knows how to treat its customers right, and with fast shipping to Canada, Canadian customers can great truck gear too. We know you\'ll feel confident with the no-hassle return policy, backed by a solid commitment to outstanding customer service. If you need professional advice, be sure to check out their free video demos and buyer guides, such as how to install an Extang tonneau cover and budget Ford F-150 lift kits.

Don\'t just spin your wheels looking for a deal. To get a great <a href=\"http://www.4wheelparts.com\">4WheelParts coupon</a>, cruise on over to Savings.com, the best place on the net to find 4WheelParts coupon codes.','displayUrl'=>'http://www.4wheelparts.com/','imageUrl'=>'http://cdn.savings.com/logo/2615252.gif','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>90,'id'=>243958,'name'=>'511 Tactical','description'=>'Law enforcement officials need the best providers to make sure they have flexible, light clothing and durable accessories that won\'t give out when they need them most. 511 Tactical fulfills this need by producing hard-wearing attire for all of their customers.

511 Tactical offers standard military and law enforcement themed shirts, pants, hats, and standard clothes as a normal customer would expect them to. However, this innovative tactical retailer also thought to include useful gear such as folding tactical knives, all-inclusive backpacks and steel-toed boots making them the ultimate tactical gear provider. 

The vast majority of their products are produced under the self-titled 511 line of tactical apparel. Their staff encourages questions about the nature of their business and is friendly and approachable to say the very least.

A very special <a href=\"http://www.511tactical.com\">511 Tactical coupon</a> is offered by Savings.com for anyone looking for top-notch military gear and anyone who would want the benefits of some outstanding 511 Tactical coupons.','displayUrl'=>'http://www.511tactical.com/','imageUrl'=>'http://cdn.savings.com/logo/1116147.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>91,'id'=>254853,'name'=>'525America','description'=>'','displayUrl'=>'http://www.525america.com/','imageUrl'=>'http://cdn.savings.com/logo/1525488.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>92,'id'=>314746,'name'=>'5star_products','description'=>'','displayUrl'=>'http://cgi.ebay.com/ws/eBayISAPI.dll?ViewItem&item=150575864066','imageUrl'=>'http://cdn.savings.com/logo/2714209.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>93,'id'=>229526,'name'=>'6ave','description'=>'<p>Sixth Avenue Electronics has been a leading source of high end electronics and accessories since 1984.</p>

<p>First opened in New York City by the Temiz family, 6ave was founded on the vision of providing customers with the best selection of products at affordable prices, as well as with the best advice and product information available from knowledgeable 6ave customer service representatives who know and love everything about the products they sell.</p>

<p>Whether you’re looking for brand new plasma or LCD TVs, GPS navigation systems, digital cameras, Blu-ray players, home theater systems or some other high tech electronic wonder or accessory, 6ave is sure to have whatever it is you want and need from trusted brand names like Sony, Toshiba, Garmin, Canon and more – all at affordable low prices that are sure to make you smile.</p>

<p>With savings up to 50% off the original prices of select brand name electronics and accessories throughout the site as well as free shipping promotions and extra discounts on top of everyday low prices thanks to amazing <a href=\"http://www.6ave.com\">6ave</a> coupons and 6ave coupon codes, you’ll find yourself stocking up on all the electronics you’ve been coveting from the top brand names you’ve come to love and trust – all without breaking the bank.</p>

<p>For even more savings on your 6ave order, be sure to check out our latest 6ave coupons and 6ave coupon codes right here at Savings.com and get all the high end electronics and accessories you’ve been looking for at great, low prices from 6ave you can more than afford.</p>','displayUrl'=>'http://www.6ave.com','imageUrl'=>'http://cdn.savings.com/logo/1140593.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>94,'id'=>206375,'name'=>'6pm.com','description'=>'6pm.com is your source for designer clothing, footwear and accessories for up to 75% off retail prices.  With top quality items at deep discount prices, 6pm.com has thousands of products for men, women kids and babies.  

Shop by department, category or brand with the functional and easy-to-use website at 6pm.  And speaking of brands, 6pm.com carries only top names like Clarks, UGG, adidas, Vans, Puma and Converse.  There are over one thousand respected brands at 6pm, from Anne Klein to Zoo York. 

Endorsed by BizRate and the BBB, 6 PM offers a safe shopping guarantee and 30-day return policy so you can shop 6pm.com with confidence.  Great selection, designer names, affordable prices and excellent service make 6pm.com your one-stop shop for your entire family\'s wardrobe.

Want to get the best deal possible on your purchase?  Look for 6pm.com deals and 6pm coupons at Savings.com.  We\'re all about great deals and discounts at Savings.com, which is why you should check here first for a <a href=\"http://www.6pm.com\">6pm.com coupon code</a> or 6pm.com promo code. Get ready to save!','displayUrl'=>'http://www.6pm.com','imageUrl'=>'http://cdn.savings.com/logo/1734850.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>95,'id'=>229458,'name'=>'7 For All Mankind','description'=>'7 for All Mankind is most decidedly one of the leading denim brands in the world with a wide range of cuts, styles and colors to suit all body types and budgets for men, women and children.<br><br>

Founded by Michael Glasser, Jerome Dahan and Peter Koral back in 2000 in sunny Los Angeles, California, the company initially started out selling only women’s fashions, but then branched out into men’s fashions in 2002 and then into a girls and boys line in 2005. This means that men, women and children of all ages in over 80 countries around the world (including Japan, Canada and Europe) are all flaunting their good fashion sense in their favorite pair of 7 for All Mankind.<p>
Of course, high quality denim doesn’t come cheap these days, so it’s a bit of an epic shopping journey to find a good 7 for All Mankind coupon or sale that makes this brand as affordable as we’d like it to be. Luckily, the 7 for All Mankind website usually has free shipping promotions and savings up to 70% off the original prices of everything from jeans to dresses, tops, jackets, accessories, handbags and more.<br><br>

To be sure you’re getting the very best <a href=\"http://www.7forallmankind.com\">7 for All Mankind</a> discounts, be sure to check out our site right here at Savings.com and get ready to rack up the savings with the latest sales and promotions on the designer brand clothing and accessories you love at just a fraction of the cost you might pay elsewhere.','displayUrl'=>'http://www.7forallmankind.com','imageUrl'=>'http://cdn.savings.com/logo/2620148.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>96,'id'=>257354,'name'=>'7-Eleven','description'=>'','displayUrl'=>'http://www.7-eleven.com/','imageUrl'=>'http://cdn.savings.com/logo/1523983.gif','allowPartnerDeals'=>'true','categoryIds'=>20861),
  array('id_index'=>97,'id'=>256969,'name'=>'77ink.com','description'=>'','displayUrl'=>'http://77ink.com/','imageUrl'=>'http://cdn.savings.com/logo/1522225.gif','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>98,'id'=>298545,'name'=>'77Kids','description'=>'','displayUrl'=>'http://www.ae.com/77kids/index.jsp','imageUrl'=>'http://cdn.savings.com/logo/2681975.png','allowPartnerDeals'=>'false','categoryIds'=>'Array'),
  array('id_index'=>99,'id'=>240488,'name'=>'7DayWarehouse.com','description'=>'','displayUrl'=>'http://www.7daywarehouse.com/','imageUrl'=>'http://cdn.savings.com/logo/1014175.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>100,'id'=>291025,'name'=>'7Gates.worldventures.biz','description'=>'','displayUrl'=>'http://www.7GATES.worldventures.biz','imageUrl'=>'http://cdn.savings.com/logo/1697273.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20901),
  array('id_index'=>101,'id'=>239416,'name'=>'7inkjet','description'=>'','displayUrl'=>'http://www.7inkjet.com','imageUrl'=>'http://cdn.savings.com/logo/949995.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>102,'id'=>276581,'name'=>'7ops','description'=>'','displayUrl'=>'http://7ops.com/','imageUrl'=>'http://cdn.savings.com/logo/1656286.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>103,'id'=>290841,'name'=>'800HighTech.com','description'=>'','displayUrl'=>'http://www.800hightech.com/','imageUrl'=>'http://cdn.savings.com/logo/1695849.gif','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>104,'id'=>291604,'name'=>'80s Purple','description'=>'','displayUrl'=>'http://www.80spurple.com/','imageUrl'=>'http://cdn.savings.com/logo/1705630.gif','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>105,'id'=>236110,'name'=>'877MYJUICER.COM','description'=>'','displayUrl'=>'http://www.877myjuicer.com','imageUrl'=>'http://cdn.savings.com/logo/645400.gif','allowPartnerDeals'=>'true','categoryIds'=>20873),
  array('id_index'=>106,'id'=>206575,'name'=>'911 Health Shop','description'=>'Based in Indiana, 911 Health Shop provides top-rated, high quality health care products, a friendly customer service team, and a hassle-free return policy that we just know you\'ll love.

When you browse through 911 Health Shop, you will find a wide array of products designed to meet your specific health care needs, including weight loss pills, detoxifying capsules, weight loss pills, mood enhancing supplements, pain relief gels, meal replacement bars, vitamins, sexual health formulas, and so much more. 

You can find all the name brands that you trust, such as Advanced BioSolutions, Palo Alto Labs, TriMedica, Tom\'s of Maine, and Symbiotics, and they are all at bargain prices that you won\'t be able to resist.

At Savings.com, we are pleased to offer exclusive <a href=\"http://www.911healthshop.com\">911 Health Shop coupons</a> to help you spend less money on your next purchase of health care products, so grab a 911 Health Shop coupon code here today and start saving.','displayUrl'=>'http://www.911healthshop.com','imageUrl'=>'http://cdn.savings.com/logo/624530.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>107,'id'=>294928,'name'=>'99designs','description'=>'','displayUrl'=>'http://99designs.com/','imageUrl'=>'http://cdn.savings.com/logo/2606345.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>1130,'id'=>301615,'name'=>'123 Copy DVD','description'=>'Introduced in 2001, 123 Copy DVD is a software solution from Bling Software Ltd developers that offers a safe way to back up all your favorite DVDs without loss in quality.

If you need to make a backup of your favorite blue-ray movie, so you can safely store your original away, look no further than 123 Copy DVD site where you can find the software which works with your PC or Mac, providing a fast and efficient solution. 123 Copy DVD also offers other software packages like ones to transfer your movies, in a seamlessly converted format, to your mobile device like an iPad, iPhone, Blackberry or Android smart phone.

Savings.com is pleased to offer extra savings for your purchases on the software that allows backup copies of your DVD slide shows for gifts to family or for transferring a movie to your iPod to view on vacation; shop 123 Copy DVD use one of our <a href=\"http://www.123copydvd.com\">123 Copy DVD coupons</a> now for your purchases.','displayUrl'=>'http://www.123copydvd.com','imageUrl'=>'http://cdn.savings.com/logo/2616400.png','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>1391,'id'=>250220,'name'=>'5Forms.com','description'=>'Running a business is incredibly hard work. Managing staff. Correcting unforseen issues. Making sure people are paid. All of these tasks take a lot of work, however at the end of the day, a means to document it all makes it worthwhile. 5Forms.com is a national wholesaler who works with various manufacturers to negotiate low prices on printed products. 

Inventory is stocked with items such as business checks, deposit tickets and invoices to make sure that any business owner has the right products to make sure day-to-day transactions are ran smoothly. This site also features a live chat, which can greatly enhance your shopping experience. Providing quality service is a high priority.

A number of popular products in its inventory set these guys apart from other rivals in this particular field. One such product is the 401-piece HVAC Starter Kit, which is a bundle set of products including necessary items such as Work Order Invoices, Service Labels and a service call book made to help anyone manage their office in an efficient way. Set up your payroll checks here. 

Invest in a Name and Address stamp, prices start at $17.71. Other items such as company letterhead and two-sided business cards are also available in varying designs and colors to the meet the customer\'s expectations. Outside of the office world, other forms available include those for automotive businesses, locksmiths, warehouse and receiving. When that time of year comes to spread some cheer, this store also has a separate section for holiday-themed items to top off its large amount of diverse items.

With so much to choose from, deals have to be inevitable, right? Without question. A promotional section on the website lists items ranging from paper clips to letter slitters at great discounts, some going as cheaply as $1 to $2 per unit. 

Make sure to look at the <a href=\"http://www.5forms.com\">5Forms.com</a> coupons on Savings.com for amazing deals for this excellent site. We are creating deals right now. If you don\'t see a 5Forms.com coupon code or discount, let us know. We can notify you when a coupon is available. If something looks good, but you are not sure it is the right fit, you can request samples of their products.','displayUrl'=>'http://businessformsworld.com','imageUrl'=>'http://cdn.savings.com/logo/1483434.png','allowPartnerDeals'=>'true','categoryIds'=>20729),
  array('id_index'=>5108,'id'=>308395,'name'=>'6 Week Body Makeover','description'=>'','displayUrl'=>'http://www.buybodymakeover.com','imageUrl'=>'http://cdn.savings.com/logo/2628528.png','allowPartnerDeals'=>'true','categoryIds'=>'Array')
);
