<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>6904,'id'=>489011,'name'=>'Q-Force','description'=>'','displayUrl'=>'http://www.qforce.com','imageUrl'=>'http://cdn.savings.com/logo/2935670.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20857),
  array('id_index'=>6905,'id'=>255881,'name'=>'Qantas','description'=>'Qantas Airlines is the world’s second oldest and Australia’s largest domestic airline.  It is closely related to Australia’s international identity as the famous ‘flying kangaroo’ logo is recognized as one of the finest brands. Their journey started in 1920 with fragile biplanes which carried one or two passengers in open cockpits and today the new Airbus A380 carries around 450 people half way around the world in a single day. A380 was introduced in 2008 and is created using custom designed fabrics, innovative materials and premium finishes. <br><br/>

With the passage of time, Qantas has become one of the strongest brands in Australia and has been awarded various international awards. The success of Qantas is due to everyone associated with them - their staff, loyal customers, suppliers and associate business partners. Qantas continues to provide excellent customer service with the support of its committed staff. The traveler can get all the information regarding his seat, activities, dining before joining them onboard. <br><br/>

These guys are the world’s leading long-distance airline carrier and they continue to have supreme safety record and exceptional in-flight services and comfort. Their entertainment system has something for everyone including the latest blockbuster movies, current affairs, TV shows and other games. They are devoted to implement processes and policies which help to protect the environment. <br><br/>

Qantas Airlines values the money of the shareholders and investors and provides them a wide range of information about the projects and performance of the company. All details such as key financial dates, information about dividends are available via their latest news releases. The frequent flyers and business travelers are offered special services at excellent prices like PC power outlets in first and business class to recharge laptops, in-flight SMS, seat to seat calls, satellite phones and many more. <br><br/>

We at Savings.com offer you the very best in <a href=\"http://www.qantas.com\">Qantas</a> deals and Qantas discount codes so you can have Qantas flights at the right price and at appropriate time. Our aim is to help you in saving money and provide you the best available deal. We are a reliable medium for all customers who want secure, high quality and low price deals. <br><br/>','displayUrl'=>'http://www.qantas.com.au/travel/airlines/home/us/en/','imageUrl'=>'http://cdn.savings.com/logo/1506420.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6906,'id'=>298079,'name'=>'Qdoba','description'=>'','displayUrl'=>'http://www.qdoba.com/default.aspx','imageUrl'=>'http://cdn.savings.com/logo/2795716.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6907,'id'=>297853,'name'=>'QPET Supplies','description'=>'','displayUrl'=>'http://www.qpetsupplies.com','imageUrl'=>'http://cdn.savings.com/logo/2455352.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6908,'id'=>248708,'name'=>'QSN','description'=>'','displayUrl'=>'http://www.qsnelectricfireplaces.com','imageUrl'=>'http://cdn.savings.com/logo/1191684.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6909,'id'=>247360,'name'=>'QTpaws.com Pet Boutique','description'=>'','displayUrl'=>'http://shop.qtpaws.com/','imageUrl'=>'http://cdn.savings.com/logo/1178721.png','allowPartnerDeals'=>'true','categoryIds'=>20221),
  array('id_index'=>6910,'id'=>214648,'name'=>'Quality Bath','description'=>'With over 100,000 bath products to suit your fancy, Quality Bath online is the ideal place to shop. Quality Bath offers bath solutions for the do-it-yourselfer and seasoned architect alike. Check out Quality Bath for the bath supplies you need, including Quality Bath whirlpool tubs, Quality Bath shower systems, Quality Bath toilets and bidets, Quality Bath faucets, Quality Bath bathroom vanities, Quality Bath consoles, and more. When you think of shopping for luxurious bath fixtures at the best prices, Quality Bath will never let you down. Save big bucks at Quality Bath with coupons from Savings.com. On Savings.com you will find the must-have Quality Bath rebates, Quality Bath coupons, Quality Bath online offers, and Quality Bath promotions. Savings.com updates their Quality Bath code, Quality Bath codes, Quality Bath promotional code, and Quality Bath promotional code regularly, so check back often.','displayUrl'=>'http://www.qualitybath.com','imageUrl'=>'http://cdn.savings.com/logo/27349.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6911,'id'=>247743,'name'=>'Quality Inn','description'=>'Quality Inn is one of the world’s largest hotel franchisors providing high quality and high value lodging options to the businessmen and leisure travelers. It started as a small hotel chain in 1930s and has grown providing best lodging options throughout the United States and internationally ranging from limited service to full service hotels in the economy, mid scale and upscale segments. It is a franchisor of trusted brands which includes Comfort Inn, Comfort Suites, Quality Inn, Sleep Inn, Suburban Extended Stay Hotel, Cambria Suites and others. <br><br/>

You can easily find the hotels by filling the name of the city, address, route, airport, country or country codes on the homepage of the Quality Inn website. The process of booking a stay at any of the hotel is very simple. The Quality Inn hotels are recognized for their brilliance in hospitality, service, appearance and operational standards. Various special packages are offered by them such as advance purchase packages, dining packages, stay and fly packages, golf packages and others. There are no charges for stay of children below 18 years. <br><br/>

Quality Inn provides business travel services like free high-speed internet, fire wireless internet access, fitness centers, free local calls, free continental breakfast, meeting and banquet facilities.  Their group and meeting section provides special offers, deals and information.  The rooms are wide, clean and comfortable and the beddings include clean pillows, cases and sheets. The Quality Inn hotels not only provide spacious place for parking and staying but also give incredible savings to the customers. <br><br/>

The Quality Inn website also features a list of popular locations and a list of suggested travel destinations. Their travel professionals are dedicated to provide everything you need to make your trip memorable and comfortable. The person can find about the special offers on their homepage or can provide an email address to receive the latest special offers in his inbox. <br><br>

We at Savings.com, provide some of the very best in <a href=\"http://www.qualityinn.com\">Quality Inn</a> coupons and Quality Inn discounts so you can enjoy a comfortable stay in a trusted hotel without having to worry about breaking the bank. So be sure to check out our latest Quality Inn coupons and get ready to save. <br><br/>','displayUrl'=>'http://www.qualityinn.com/','imageUrl'=>'http://cdn.savings.com/logo/1181341.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6912,'id'=>295358,'name'=>'Quality Logo Products','description'=>'','displayUrl'=>'http://www.qualitylogoproducts.com/blog/military-month/','imageUrl'=>'http://cdn.savings.com/logo/1736760.gif','allowPartnerDeals'=>'true','categoryIds'=>20729),
  array('id_index'=>6913,'id'=>302962,'name'=>'Quality Paperback Books Club','description'=>'','displayUrl'=>'http://www.qpb.com','imageUrl'=>'http://cdn.savings.com/logo/2619347.png','allowPartnerDeals'=>'true','categoryIds'=>20723),
  array('id_index'=>6914,'id'=>296424,'name'=>'Quality Tools for Less','description'=>'','displayUrl'=>'http://QualityToolsForLess.com','imageUrl'=>'http://cdn.savings.com/logo/2215022.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6915,'id'=>239014,'name'=>'Quality Water Filters 4 You','description'=>'','displayUrl'=>'http://www.qualitywaterfilters4you.com','imageUrl'=>'http://cdn.savings.com/logo/1524042.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6916,'id'=>295939,'name'=>'qualitydiscountlighting.com','description'=>'','displayUrl'=>'http://www.qualitydiscountlighting.com','imageUrl'=>'http://cdn.savings.com/logo/1827239.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6917,'id'=>236211,'name'=>'QualityMatters.com','description'=>'','displayUrl'=>'http://www.QualityMatters.com','imageUrl'=>'http://cdn.savings.com/logo/657217.gif','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6918,'id'=>248810,'name'=>'QualitySmith','description'=>'','displayUrl'=>'http://www.qualitysmith.com/','imageUrl'=>'http://cdn.savings.com/logo/1194347.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6919,'id'=>268661,'name'=>'QuarkPromote.com','description'=>'','displayUrl'=>'http://quarkpromote.quark.com/','imageUrl'=>'http://cdn.savings.com/logo/1613985.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>6920,'id'=>290486,'name'=>'QuashNoise','description'=>'','displayUrl'=>'http://www.quashnoise.com','imageUrl'=>'http://cdn.savings.com/logo/1692004.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6921,'id'=>248311,'name'=>'Queens Mountain Outfitters','description'=>'','displayUrl'=>'http://www.queensmountainoutfitters.com','imageUrl'=>'http://cdn.savings.com/logo/1524052.gif','allowPartnerDeals'=>'true','categoryIds'=>20885),
  array('id_index'=>6922,'id'=>233309,'name'=>'Queensboro Shirt Company','description'=>'','displayUrl'=>'http://www.queensboro.com','imageUrl'=>'http://cdn.savings.com/logo/619874.gif','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>6923,'id'=>291110,'name'=>'Quest Bar','description'=>'Based in Marina del Ray, California, the Quest Bar company is the leading online retailer of nutritious protein bars that are the snack of choice for top athletes, such as bodybuilding champion Chet Yorton and fitness model Rachel Mac. We just know you\'ll love Quest Bar\'s friendly, easy-to-contact customer service team and the satisfaction guarantee on all of its protein bars.

At Quest Bar, you can choose from two different types of tasty protein bars -Vanilla Almond Crunch and Peanut Butter Supreme. All of the protein bars are gluten-free, and they contain bio-available proteins and low non-fiber carbs, helping you shed those excess pounds of fat and gain muscle mass with every delicious bite.

At Savings.com, we are pleased to offer you a <a href=\"http://www.questproteinbar.com\">Quest Bar coupon</a> so that you can spend less money when you buy these high-quality protein bars, so grab a Quest Bar coupon today and start saving.','displayUrl'=>'http://www.questproteinbar.com/','imageUrl'=>'http://cdn.savings.com/logo/1702567.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6924,'id'=>262428,'name'=>'Quick Supply','description'=>'','displayUrl'=>'http://www.quicksupply.net','imageUrl'=>'http://cdn.savings.com/logo/1578476.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>6925,'id'=>225376,'name'=>'QuickBooks','description'=>'QuickBooks offers complete financial software solutions for the small business and is offered by Inuit -  the personal finance software company that started in 1983 with their revolutionary product Quicken.<br><br> 

Their suite of products include Accounting, Payroll, Point of Sale, Accept Credit Cards, Training, Checks, Forms & Supplies and more. They also offer industry specific solutions tailored to help your business succeed - ranging from Manufacturing to Nonprofits, Professional Services, Retail, Contracting and more.  QuickBooks is designed to help small businesses save time on their every day financial tasks and accurately manage their financial data. <br><br>

When you shop <a href=\"http://quickbooks.intuit.com/\">QuickBooks.com</a> you\'ll find several small business financial solutions. By using our coupon service, you can even get your hands on QuickBooks rebates and other discounts for your business to help stretch your budget. By using some of our QuickBooks coupons in addition to an awesome rebate, you can sometimes save double - or even triple the amount - that you would have without them. <br><br>

By signing up for our coupon service, you can shop our large selection of online stores and get rebates, discounts, and coupons for hundreds of merchants, You can save more on software, financial software services and small business software. You will be able to check an option to make sure that you receive your chosen discounts emailed directly to you.<br><br> 

Savings.com is where you will find QuickBooks coupon codes and promotions that can help the small business owner and large enterprise operations keep ahead of the curve when it comes to accounting and business management, so start browsing for your QuickBooks rebates and discounts and save on the software you need at prices you can more than afford.','displayUrl'=>'http://quickbooks.intuit.com/','imageUrl'=>'http://cdn.savings.com/logo/2683200.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6926,'id'=>220013,'name'=>'Quicken','description'=>'Quicken was launched in 1984 with its first product, Quicken Software. Since then, Quicken has amassed over 15 million users, and they\'ve built a reputation for being the go to company for solutions and better ways to manage bother personal and small business finances. Quicken is an Intuit company, the same company that owns Quickbooks and TurboTax. There\'s nothing your personal or small business finances can throw at Quicken, Quickbooks, and TurboTax that they can\'t handle. Quicken.com often offers discounts on their software, but if you\'d like to save even more on your Quiken software purchase, use a Quicken coupon code, promo code, or discount from Savings.com.<br><br>

Quicken offers a number of software products to help you manage your personal finances including: Quiken Online (free), Quiken Deluxe, Quicken Mac, Quicken Home & Business, Quicken Beam (free), and Quicken WIllMaker Plus. To help you with tax preparation, Quicken pairs up with TurboTax to offer you a software combo package. Quicken offers you a discount on TurboTax when you also add Quicken to your shopping cart. With Quicken and TurboTax combined, tax preparation doesn\'t have to be a nightmare. Use a Quicken coupon code, promo code, or discount from Savings.com to help you save money on Quicken and TurboTax software.<br><br>

Before you complete your order at <a href:\"http://www.quicken.com\">Quicken.com</a>, grab a Quicken coupon code, discount, or promo code from Savings.com to help you save money on your purchase. After you find a coupon code or discount to use on your order, simply enter it during checkout at Quicken.com to see your savings. Manage your finances and save some cash when you purchase Quiken personal or small business software with a coupon code, discount, or promo code from Savings.com. Similar stores at Savings.com offer: <a href=\"http://www.savings.com/m-QuickBooks-coupons.html\">QuickBooks coupons</a> an <a href=\"http://www.savings.com/m-Turbo-Tax-coupons.html\">TurboTax coupons</a>.','displayUrl'=>'http://www.quicken.com','imageUrl'=>'http://cdn.savings.com/logo/41053.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6927,'id'=>317119,'name'=>'QuickFix Austin','description'=>'','displayUrl'=>'http://www.quickfixaustin.com','imageUrl'=>'http://cdn.savings.com/logo/2815848.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>6928,'id'=>479220,'name'=>'Quickie Cards','description'=>'','displayUrl'=>'http://www.QuickieCards.com','imageUrl'=>'http://cdn.savings.com/logo/2935142.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20854),
  array('id_index'=>6929,'id'=>283076,'name'=>'QuickieCards','description'=>'','displayUrl'=>'http://www.QuickieCards.com/','imageUrl'=>'http://cdn.savings.com/logo/1662402.png','allowPartnerDeals'=>'true','categoryIds'=>20854),
  array('id_index'=>6930,'id'=>236723,'name'=>'QuikShip Toner','description'=>'','displayUrl'=>'http://www.quikshiptoner.com/catalog/','imageUrl'=>'http://cdn.savings.com/logo/724808.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>6931,'id'=>261707,'name'=>'Quiksilver','description'=>'','displayUrl'=>'http://www.quiksilver.com/','imageUrl'=>'http://cdn.savings.com/logo/1541808.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>6932,'id'=>262141,'name'=>'Quill','description'=>'','displayUrl'=>'http://www.quill.com/','imageUrl'=>'http://cdn.savings.com/logo/1553192.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>6933,'id'=>312975,'name'=>'QuiltRacks.com','description'=>'','displayUrl'=>'http://www.quiltracks.com','imageUrl'=>'http://cdn.savings.com/logo/2730434.gif','allowPartnerDeals'=>'true','categoryIds'=>20216),
  array('id_index'=>6934,'id'=>236994,'name'=>'Quiznos','description'=>'Quiznos started as a little sub shop that holds true to the same ideas they had when they started over 30 years ago in Denver, CO. Now a major national chain, these guys still believe that food should taste great and only be made with the highest quality ingredients, and they are dedicated to making one awesome sub at a time.

What makes them different is that they have been sandwich toasting fanatics since day one; this provides a flavor and texture that cold subs cannot compete, simply toasting makes it better. Quality is of the utmost importance and they never cheap out on ingredients - using only the finest butcher-quality meats, all-natural cheeses, chef designed flavorful signature sauces and bakery quality toasted artisan breads, no mystery meats or other low quality ingredients.

Get the best discounts with <a href=\"http://www.quiznos.com\">coupons for Quiznos</a> from Savings.com and Quiznos. When you want the highest quality ingredients, great service and the best tasting subs check out our latest Quiznos promo codes and save money with valid Quiznos coupons.','displayUrl'=>'http://www.quiznos.com','imageUrl'=>'http://cdn.savings.com/logo/766087.gif','allowPartnerDeals'=>'true','categoryIds'=>20866),
  array('id_index'=>6935,'id'=>289515,'name'=>'Quotewizard.com','description'=>'','displayUrl'=>'http://QuoteWizard.com/','imageUrl'=>'http://cdn.savings.com/logo/1684234.png','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>6936,'id'=>5314,'name'=>'QVC','description'=>'Broadcasting 24 hours a day, 7 days a week, 364 days a year, QVC reaches over 166 million homes worldwide.  One of the largest multimedia retailers in the world, QVC presents 1,150 products each week to their customers.  The vast QVC inventory includes fashion, beauty, jewelry, home items and electronics.  QVC.com carries a number of well-known brands such as philosophy, Bare Escentuals, Dell, BOSE, Garmin, HP and Dooney & Bourke. QVC has legions of satisfied customers:  in the past 22 years, QVC has shipped over one billion packages in the U.S. alone. Want to save some money on your QVC purchase?  Check out the QVC coupons from Savings.com!  Like QVC, Savings.com is all about great deals and discounts.  So what could be better than that great QVC deal made even better with a QVC.com coupon code from Savings.com?  So before you finalize your order at <a href=\"http://www.qvc.com\">QVC.com</a>, head over to Savings.com for our QVC promo codes. For Quality, Value, and Convenience, you can count on QVC.  And for the best QVC coupons, check out Savings.com!','displayUrl'=>'http://www.qvc.com','imageUrl'=>'http://cdn.savings.com/logo/1109824.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>6937,'id'=>206682,'name'=>'Qwest','description'=>'Qwest is a high-speed Internet and communications service provider dedicated to quality customer care and bringing affordable, reliable communications technology to the consumer market. Qwest strives to provide flexible package options and the lowest price possible for their customers, while still maintaining fast Internet connections and high-quality cable television.

Qwest offers DirectTV packages bundled with free trials of channels such as Showtime, HBO and Starz, as well as DSL fiber-optic Internet access with wireless, Norton Antivirus and self-installation options. 

As a bonus, internet service also grants access to a country-wide AT&T\'s mobile wireless hotspots. Traditional local and long distance phone service is available, but the more tech-savvy have the option of DSL and broadband VoIP instead, letting your computer take the place of a landline.

Make sure you don\'t miss out on extra savings by using a Qwest coupon code when signing up. Check out Savings.com\'s huge selection of <a href=\"http://www.qwest.com\">Qwest coupons</a> and enjoy a high-speed connection without a hefty price tag.','displayUrl'=>'http://www.qwest.com','imageUrl'=>'http://cdn.savings.com/logo/26920.gif','allowPartnerDeals'=>'true','categoryIds'=>20840)
);
