<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>6149,'id'=>269151,'name'=>'USbeds.com','description'=>'','displayUrl'=>'http://www.usbeds.com/','imageUrl'=>'http://cdn.savings.com/logo/1703202.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20874),
  array('id_index'=>8894,'id'=>262282,'name'=>'U Store It','description'=>'Trying to get rid of clutter or looking to put away items? Need to move right away and need to store your belongings? Eliminate the worries and hassle of looking for storage by using the services provided by U Store It. With hundreds of locations nationwide, you can find suitable and affordable options for your storage needs.

U Store It is a publicly traded company and is one of the top five self-storage operators in the United States. They have a proven track record of providing self-storage services to thousands of clients throughout the country. Unsure about how storage works? Their expert staff can help you with answers to all of your storage-related questions. In addition, many locations sell packaging materials and other supplies for your storage needs.

With this storage facility, you have the most flexibility in designing a storage plan that fits your needs, whether it is just for one month or something long-term and whether it is for personal belongings, storage for a business enterprise or simply putting a vehicle away in storage.

The storage facilities are secure with around-the-clock surveillance. Each unit is climate-controlled to further protect your items. You can secure the unit with your own lock, and take added comfort in knowing only you can access it. The units in the storage facility are available during regular business hours and many locations also offer 24-hour access. The staff will work with you to figure out the right storage needs that meet your budget. These guys also have a lowest price guarantee. If you can find a lower price for storage services, they will beat or match it.

Through Savings.com, you can take extra savings off the already low prices provided by U Store It. For example, if you sign-up for your storage service online, you get your first month absolutely free. Other special deals include 20% - 50% discounts for military personnel, free shipping on any $25.00 or more order of packing supplies, and the opportunity to save on one month of rent through their referral program. In addition, all U Store It customers have access to a free moving truck.

So check out our latest <a href=\"http://www.ustoreit.com\">UStoreIt</a> coupons and UStoreIt coupon codes and discounts and get ready to save big bucks on the storage space you need.','displayUrl'=>'http://www.ustoreit.com/','imageUrl'=>'http://cdn.savings.com/logo/1560277.png','allowPartnerDeals'=>'true','categoryIds'=>20876),
  array('id_index'=>8895,'id'=>241371,'name'=>'U-Top It Frozen Yogurt','description'=>'','displayUrl'=>'http://u-topit.com/','imageUrl'=>'http://cdn.savings.com/logo/1025402.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20866),
  array('id_index'=>8896,'id'=>5433,'name'=>'US Cavalry','description'=>'Whether you’re looking for specialized equipment for military, law enforcement and homeland security, or you just want some basic training and discussion of counterterrorism tactics, US Cavalry is your online destination for affordable goods and knowledge.
<br /><br />
As the very first military supplier to focus solely on outfitting the individual soldier, these guys have over 30 years experience in providing customers around the world with the very best in clothing, badges, field equipment, footwear, knives, tools, insignia and so much more--all at affordable low prices that mean you can stock up on the gear you need to protect yourself, your family and your country in any situation without having to worry about breaking the bank.
<br /><br />
With savings up to 80% off the original prices of select clothing, shoes, equipment, tools and more throughout the site, as well as free shipping promotions, free gifts with purchase and extra discounts on top of everyday low prices thanks to US Cavalry coupons and US cavalry coupon codes – you’ll get the high quality gear you both want and need at amazing low prices that fit your budget.
<br /><br />
For even more savings on your <a href=\"http://www.uscav.com\">US Cavalry</a> order, be sure to check out our site right here at Savings.com for some of the latest and greatest in US Cavalry coupons and US cavalry coupon codes and get the equipment, gear, clothing and more you want and need at amazing low prices from a store that hundreds of thousands of customers have come to trust in over 30 years of business.','displayUrl'=>'http://www.uscav.com','imageUrl'=>'http://cdn.savings.com/logo/2596.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8897,'id'=>255278,'name'=>'U.S. Navy Memorial Store','description'=>'','displayUrl'=>'http://navymemorialstore.com/','imageUrl'=>'http://cdn.savings.com/logo/1524067.gif','allowPartnerDeals'=>'true','categoryIds'=>20213),
  array('id_index'=>8898,'id'=>220028,'name'=>'US Toy','description'=>'The U.S. Toy Company sells a vast array of carnival/party and seasonal decorations, novelty toys, stuffed animals, balloons and many more items that have been developed by us for our exclusive sale. Our products are affordable, with some items priced as low as a penny a piece!!','displayUrl'=>'http://www.ustoy.com/','imageUrl'=>'http://cdn.savings.com/logo/619977.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20895),
  array('id_index'=>8899,'id'=>302510,'name'=>'UberPrints','description'=>'If you are looking for something creative and out of the ordinary for your customized clothing designs, then go no further than UberPrints who provide a full design service. They will provide a speedy turn-around for personal or corporate customers backed up by a guarantee that will give you piece of mind.

UberPrints have a powerful online design tool stacked full of funky designs that lets you customize a wide range and colors of clothing that can be screen, digitally printed, or embroidered for you, your team, your company and even pets so that you can add a personal touch to your clothing, and let the world know your message.

UberPrints cannot be beaten on quality or choice especially when you take advantage of the <a href=\"http://www.uberprints.com\">UberPrints coupon</a> that are available from them or head over to Savings.com to find your UberPrints coupons and get the maximum value for money.','displayUrl'=>'http://www.uberprints.com','imageUrl'=>'http://cdn.savings.com/logo/2618342.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8900,'id'=>5087,'name'=>'Ubid','description'=>'U Bid is an online auction company committed to superior customer care, providing comprehensive warranties and the best quality brands for the best prices possible. They have more than 12 years experience in the online auction marketplace. When retailers find themselves overstocked with fine quality merchandise, they buy it in bulk and auctions it well below retail prices.

They offer hundreds of deals on automotive & travel products, home & garden, apparel, music instruments, handbags, luggage, toys & games, movies, sports equipment, binoculars, telescopes, fine art, watches, jewelry, computers and electronics. Whatever you\'re in the market for, you can bid on it at U Bid.

There are many auction options available such as mega auctions, express auctions and even a red tag deal of the day for super savings on your favorite quality brands. There is a vast selection of some of the best name brand computer accessories and software to choose from such as Asus, Logitech, Microsoft, and Adobe with prices starting as low as $12.00. See their most popular auctions for a quick start, bid quickly and win an auction that is about to close or check out the brand new auctions to plan your bidding strategy.

You could win an Asus netbook for as little as $169.00 and pay only $1.95 for shipping costs, a real bargain. You can get a SanDisk 8GB MP3 Photo Video player for just $210.00, and get all the iPod accessories you need in one place from brands like Lansing, Kensington, and Skull Candy.
They also have a Toyo DC inverter split Air Conditioner with a starting price of just $1199.00. They have high quality products at unbelievable prices. Genuine diamond jewelry auctions start at just $1.00. There are also hundreds of luxury watches auctioned off every week with a very low starting bid of just $1.00.

More U Bid coupons and <a href=\"http://www.ubid.com\">U Bid</a> coupon codes become available to us all the time at Savings.com, so be sure you sign up and get notified as soon as the latest U Bid discounts become available. Don\'t miss your opportunity to grab some of the best deals on housewares, jewelry, fine china and more at U bid online auction.','displayUrl'=>'http://www.ubid.com','imageUrl'=>'http://cdn.savings.com/logo/1671360.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8901,'id'=>301824,'name'=>'uCorder','description'=>'','displayUrl'=>'http://www.ucorder.com/','imageUrl'=>'http://cdn.savings.com/logo/2615950.png','allowPartnerDeals'=>'true','categoryIds'=>20848),
  array('id_index'=>8902,'id'=>483212,'name'=>'Udders Home Furnishings','description'=>'','displayUrl'=>'http://udders.com/','imageUrl'=>'http://cdn.savings.com/logo/2935377.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20877),
  array('id_index'=>8903,'id'=>242249,'name'=>'UFC','description'=>'The Ultimate Fighting Championship (UFC) is one of the leading mixed martial arts (MMA) associations and you can find everything you need to show your love of the sport and its heroes at the UFC Store.<br><br>  

You’ll have access to event schedules, online ticket purchasing, news coverage, fighter bios, community forums and more.  If you want to take your fandom even further, shop the UFC Store for logo emblazoned apparel, DVDs, action figures, training equipment and collectibles.<br><br>  
Show support for your favorite fighters such as Chuck Liddell, Randy Couture or Yoshihiro Akiyama with products from the UFC Store.  Home to World Extreme Cagefighting and The Ultimate Fighter, this store is an MMA aficionado’s paradise!<br><br>

Want to save some cash on your UFC Store purchase?  Grab a hold of a <a href=\"http://ufcstore.seenon.com\">UFC Store</a> coupon code or promotional code from Savings.com and get ready to proclaim your fandom of mixed martial arts to the world with the latest gear, DVDs, toys, tickets and more at just a fraction of the original costs.','displayUrl'=>'http://ufcstore.seenon.com','imageUrl'=>'http://cdn.savings.com/logo/1075031.jpeg','allowPartnerDeals'=>'false','categoryIds'=>'Array'),
  array('id_index'=>8904,'id'=>235523,'name'=>'UGG','description'=>'From coast to coast and country to country, Ugg Australia has shared the power and durability of sheepskin boots with millions of fans the world over.<p>

Thanks to an ever changing line up of designs for men, women and children in fun patterns and seasonal colors, these guys have managed to make sheepskin slippers seem like glamorous footwear for almost any occasion.<p> 

Whether you’re headed to the beach, headed out to dinner with friends or headed to the couch for some downtime, the massive selection of slippers, boots, shoes, sandals and more that this brand has to offer are simply a must for your year round wardrobe. These guys even carry handbags, pillows, gloves, hats and other awesome accessories to help keep you cozy from summer to winter.<p>

With free shipping promotions, a Sale section and extra discounts on top of some super amazing prices thanks to the latest <a href=\"http://www.uggaustralia.com\">Ugg</a> coupons and Ugg coupon codes, you’re sure to find the styles of footwear, accessories and more that you want without having to worry about breaking the bank. You can even sign up for the V.I.P Program o reap the rewards from current and future purchases and get extra savings just for being a repeat customer. Not bad at all!<p>

To be sure you’re getting the best discounts available, remember to check out our site right here at Savings.com for some of the best Ugg coupons around and get the stylish sheepskin footwear and accessories you want at amazing low prices that are sure to make you smile.','displayUrl'=>'http://www.uggaustralia.com','imageUrl'=>'http://cdn.savings.com/logo/624926.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8905,'id'=>240553,'name'=>'UgradShop','description'=>'UGradShop is a California based shop for all collegiate gifts. It is the perfect place to find gifts for any distinguished graduate, student or alumnus. UGradShop.com gifts are not only elegant and sophisticated, but also provide a traditional feel to any room, making them a perfect addition to the home or office.

They pride themselves on producing quality goods and providing excellent customer service. Every one of these items is customized with an alma mater logo, making memorable and unique gifts that will be cherished by a loved one or family member for a long time to come. The extensive list of insignia includes those of Cornell, Dartmouth, Harvard, MIT, Brown, Penn State, UCLA, Virginia Tech and many more.

You will find diploma frames in mahogany or cherry, lithographs, mantle clocks, bookends, candlesticks, letter openers and coasters for the home or office. They have a variety of elegant mugs and glasses and a range of leisure products to choose from, including travel and overnight bags, alarm clocks and pocket knives. You may prefer to choose from our personal accessories such as leather, gold or silver money clips, cufflinks, lapel pins, key, blazer buttons and men\'s or women\'s watches, to name but a few. 

All of their gifts are made from stylish, high quality materials and embossed or engraved with the school insignia of your choice. Find an attractive soft leather credit card wallet or a gold or silver money clip for an upcoming graduate.

There is an extensive list of nearly 200 US schools, from Alabama right through to Yale, which also includes US Air force, Military and Naval Academies. UGradShop makes it easy for you to find the gift you are looking for. Simply select your university from the drop-down menu and then the product type you are after. If you need any assistance, live help is available. They also offer gift certificates, for those who like to shop for themselves.

Find UGradShop coupons  and <a href=\"http://www.ugradshop.com\">UGradShop</a> coupon codes and discounts right here at Savings.com. Save 10% on your order. If you’re interested in getting a gift, consider a how much an item with a school insignia can mean to someone.','displayUrl'=>'http://www.ugradshop.com/','imageUrl'=>'http://cdn.savings.com/logo/1017491.gif','allowPartnerDeals'=>'true','categoryIds'=>20213),
  array('id_index'=>8906,'id'=>310961,'name'=>'UK Gear','description'=>'','displayUrl'=>'http://www.ukgear.com/Shop.html','imageUrl'=>'http://cdn.savings.com/logo/2681739.gif','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>8907,'id'=>285131,'name'=>'UK2 Group','description'=>'','displayUrl'=>'http://www.UK2Group.com','imageUrl'=>'http://cdn.savings.com/logo/1701201.png','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>8908,'id'=>5851,'name'=>'Ulla Popken','description'=>'Ulla Popken started out in 1880 as the Popken Textile Company in Germany, and since then has evolved into the premier retailer of women\'s size 12 and up fashions. Providing stylish plus-sized wear, the exclusive quality designs include dresses, intimates, special occasion, denim, beachwear, and jackets.

Customer service is available anytime by calling the toll-free number. And with their hassle-free return policies, you can buy with confidence. There are always fabulous new arrivals and seasonal favorites for every occasion. Bargain shoppers love searching the outlet for savings of up to 75%.

There is also a great range of shoes and fashion accessories offered here, making this your best choice for one-stop, plus-sized shopping. Select your next complete must-have outfit from the comfort of your own computer. 

Savings.com is your best source for <a href=\"http://www.ullapopken.com\">Ulla Popken coupons</a>, so when shopping for the latest in plus-sized fashion, be sure to use your Ulla Popken coupon or code.','displayUrl'=>'http://www.ullapopken.com','imageUrl'=>'http://cdn.savings.com/logo/2583.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8909,'id'=>206361,'name'=>'ULTA','description'=>'Ulta Beauty is a unique retailer that offers one stop shopping for cosmetics, skincare, fragrance, hair care, bath, body and spa products as well as mens grooming products from both department store and drugstore brand price ranges.  Each store also has a full service salon. They set out to sell prestige products normally found in department stores, hair care products usually only sold in authorized retailers and salons, as well as offer beauty products found in drugstores and mass retailers. Originally founded to offer discount cosmetics, skincare, and hair care, they have become the one of the largest beauty retailers with close to 215 stores nationwide. When you use Ulta coupons and Ulta coupon codes you can stretch your beauty budget and get more great products at Ulta<br><br>

Ulta offers all of the quality, name brand and prestige cosmetics, skincare, fragrance and hair care all at affordable prices. You will save with Free Shipping coupons on your order with a minimum purchase and Free Samples. With Savings.com free coupon service, you can save on top of their values with an Ulta coupon, Ulta coupons, an Ulta coupon code, including Ulta free shipping coupons. <br><br>

At <a href=\"http://www.ulta.com\">Ulta.com</a>, not only you find your all of your favorite brands of skincare and cosmetics, including Bare Escentuals, Bare Minerals, Smashbox, Stila, L Oreal, Cover Girl, Maybelline, Revlon, Physicians Formula, Lola Cosmetics, Dermablend, Dermalogica, Urban Decay Cosmetics, LipFusion, Fusion Beauty, Sally Hansen, Burts Bees, Neutrogena, Clinique, Elizabeth Arden, Lancome, Aveeno, Clean and Clear, Clearasil, Dove, Freeze 24-7, Lorac, MD Skincare, Murad, Olay, Pur Minerals, Rimmel London, Biore, Eucerin, Lubriderm, Booths, Daily Facials, Neostrata, Paula, Dorf, Jergens, Nivea, Too Faced, StriVectin SD, Red Earth, Kinerase, Coppertone, Bain de Soleil, H20, Banana Boat, Ulta also has their own line of quality cosmetics and skincare, plus you will also find a wide selection of hair care products from Oscar Blandi, Fekkai, Jonathan, Conair, T3, Nexxus, Clairol, Garnier, John Frieda, Warren Tricomi, Shikai, Charles Worthington, Pantene, Marc Anthony, TRESemme,  LaCoupe, ULTA, Alagio, Korres, Cutler, Ojon, mop, Sunsilk, Samy, Garden Botanika, and they also carry a large collection of fragrances including Juicy Couture, Vera Wang, Ralph Lauren, Sara Jessica Parker, Calvin Klein, Giorgio Armani, Alfred Sung, Burberry, Dior, Bulgari, LAMB, Dolce and Gabbana, and more. <br><br>

When you register with Savings.com, we can get you discounts on your online cosmetics, skincare, hair care and fragrance purchases at several hundred merchants, including Ulta, that offer exclusive coupons and coupon codes through our service. You can choose to have your favorite Ulta coupon, Ulta coupons, and Ulta coupon codes emailed to you so you never have to miss out on special offers and discounts to help you save on your Ulta purchase with an Ulta coupon, Ulta coupon codes and Ulta coupons. <br><br>

Additional cosmetic, skincare, fragrance and hair care merchants you may enjoy are <a href=\"http://www.Sephora.com\">Sephora </a>, 
<a href=\"http://www.Beauty.com\">Beauty.com</a>, 
<a href=\"http://www.eyeslipsface.com\">elf cosmetics</a>,
<a href=\"http://www.strawberrynet.com\">StrawberryNet</a>, 
<a href=\"http://www.skinstore.com\">SkinStore</a>','displayUrl'=>'http://www.ulta.com','imageUrl'=>'http://cdn.savings.com/logo/714831.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8910,'id'=>288499,'name'=>'Ultimate Basic Training','description'=>'','displayUrl'=>'http://www.UltimateBasicTraining.com','imageUrl'=>'http://cdn.savings.com/logo/1670557.png','allowPartnerDeals'=>'true','categoryIds'=>20723),
  array('id_index'=>8911,'id'=>236111,'name'=>'Ultimate Nourishment','description'=>'','displayUrl'=>'http://www.ultimate-weight-products.com','imageUrl'=>'http://cdn.savings.com/logo/645401.gif','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8912,'id'=>246642,'name'=>'Ultimate Paintball','description'=>'','displayUrl'=>'http://www.pntball.com/','imageUrl'=>'http://cdn.savings.com/logo/1498732.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8913,'id'=>300986,'name'=>'Ultimate Truck','description'=>'','displayUrl'=>'http://www.ultimatetruck.com/','imageUrl'=>'http://cdn.savings.com/logo/2612918.png','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>8914,'id'=>265853,'name'=>'Ultimate Wine Shop','description'=>'','displayUrl'=>'http://www.ultimatewineshop.com/','imageUrl'=>'http://cdn.savings.com/logo/1611084.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20862),
  array('id_index'=>8915,'id'=>221595,'name'=>'Ultimate Back Store','description'=>'With so many people spending longer hours at the office in a tough economy, the award-winning Ultimate Back Store provides relief for the workforce with its ergonomic office equipment and furniture. By using ergonomic equipment, businesses can save money by reducing worker\'s comp payments and insurance claims for common, preventable ailments such as Carpal Tunnel, eye strain, back strains, and more. Customers are happy with the service and the timely shipping that is provided.

The Ultimate Back Store specializes in office seating and equipment with your health and safety in mind. Office chair prices start as low as $159.00, offering features such as construction from lightweight and flexible materials, pleasing aesthetics, and of course back-friendly adjustable postures. A variety of other office support items are available, such as adjustable keyboard trays that will reduce the user\'s risk of developing Carpal Tunnel Syndrome, adjustable monitor arms that can help reduce eye strain, and tower doilies to make re-arranging the office a breeze. 

Sleeping mattresses can even be found here, for optimum rest after a long day at work. Even massage chairs are available, ready to de-stress workers on their lunch break. The best products from Michigan furniture magnates Herman Miller and Steelcase are available here, as well as the famous Sealy and Tempur-Pedic mattresses.

These guys want to make sure you get the lowest prices on the back-friendly office equipment you need so that you can work through the day without suffering through those pesky aches and pains. With 5-star service and amazingly low prices, there\'s no reason to sit on that old, backache-inducing chair anymore! These guys are ready to help you start planning a healthier lifestyle. Come see why customers keep coming back for more.

For fantastic merchant savings, head on over to our site right here at Savings.com where you’ll find the latest and greatest in <a href=\"http://www.ultimatebackstore.com\">Ultimate Back Store</a> coupons and Ultimate Back Store coupon codes and discounts. Say goodbye to pesky backaches and hello to better posture and a healthier, happier you thanks to awesome savings on the back support products you want and need most from the brands you love and trust – all at affordable low prices from one awesome online store.','displayUrl'=>'http://www.ultimatebackstore.com','imageUrl'=>'http://cdn.savings.com/logo/619762.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8916,'id'=>236592,'name'=>'UltimateGlobes.com','description'=>'','displayUrl'=>'http://www.ultimateglobes.com','imageUrl'=>'http://cdn.savings.com/logo/1177991.png','allowPartnerDeals'=>'true','categoryIds'=>20875),
  array('id_index'=>8917,'id'=>285673,'name'=>'Ultra Barcode','description'=>'','displayUrl'=>'http://www.ultrabarcode.com','imageUrl'=>'http://cdn.savings.com/logo/1665499.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8918,'id'=>206442,'name'=>'Ultra Diamonds','description'=>'Ultra Diamonds has the most exquisite online collection of diamonds available, so whether you\'re looking for a ring, a necklace, a bracelet, earrings, a watch, or something else, browse through the galleries of brilliant precious stones to find just the size you want.

You want the memory of \"I do\" to sparkle, and there\'s no better way to remember it than a sparkling diamond from Ultra Diamonds, so check out the engagement and wedding bands in his and her sets, with silver, gold, and colored enamel bands. For your anniversary, no one has better offerings than designers like Peter Lam, Jack J, and HJ Namdar, and no one has a better collection than Ultra Diamonds.

Savings.com wants to put the special occasion within reach, so use our Ultra Diamonds promo code or an <a href=\"http://www.ultradiamonds.com\">Ultra Diamonds coupon code</a> and bring home the stone and setting that you\'ve been looking for today.','displayUrl'=>'http://www.ultradiamonds.com','imageUrl'=>'http://cdn.savings.com/logo/27052.gif','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>8919,'id'=>253403,'name'=>'Ultra Fragrances','description'=>'Ultra Fragrances is your top resource for discounted fragrances and beauty products. With an enormous selection of products available online and new arrivals revealed each day, you can find everything you need with just one click. Whether you\'re searching for a particular scent or just crave a fantastic customer service experience, they have exactly what you\'re looking for.

Dazzle your senses with some of the world\'s best designer perfumes. Get the latest scents from Carolina Herrera, Issey Miyake, and Perry Ellis, just to name a few. Give your skin the pampering it craves with a Biotherm regimen for a more youthful complexion, or sate your craving for eco-friendly beauty products with the best Burt\'s Bees cosmetics available.

With the <a href=\"http://www.ultrafragrances.com\">Ultra Fragrances coupons</a> we have waiting for you, wearing the world\'s top designers\' fragrances doesn\'t have to come with designer prices, shop around and then redeem your favorite Savings.com Ultra Fragrances coupon for savings that will have your wallet feeling as good as you do.','displayUrl'=>'http://www.ultrafragrances.com/','imageUrl'=>'http://cdn.savings.com/logo/1656336.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8920,'id'=>268140,'name'=>'UltraHosting','description'=>'','displayUrl'=>'http://www.ultrahosting.com/','imageUrl'=>'http://cdn.savings.com/logo/1656334.png','allowPartnerDeals'=>'true','categoryIds'=>20831),
  array('id_index'=>8921,'id'=>271649,'name'=>'UltraPure Cosmetics','description'=>'','displayUrl'=>'http://www.ultrapurecosmetics.com/','imageUrl'=>'http://cdn.savings.com/logo/1632758.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20733),
  array('id_index'=>8922,'id'=>300374,'name'=>'UMI','description'=>'Umi is an online shoe sales website that offers small children\'s shoes for both boys and girls for low clearance prices.

Umi sells shoes for kids ranging from newborn baby boys and girls up to big kids up to 8 years of age, of all different styles and colors, ranging from regular shoes, to sandals and slippers of all kinds. 

As a service to their customers, Umi offers a custom sizing chart, to help parents find better fitting shoes for their children, ensuring a happy baby whose shoes don\'t hurt or fly off, they also offer free shipping and delivery on all order to make sure you get the best deal possible on your order, and when you have a kid, saving money is priority number one.

To save even more money when shopping here, look for a <a href=\"http://www.umishoes.com\">Umi code</a> on Savings.com and use the Umi code to get the perfect pair of shoes for even less.','displayUrl'=>'http://www.umishoes.com','imageUrl'=>'http://cdn.savings.com/logo/2611211.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8923,'id'=>296599,'name'=>'UMIDirect','description'=>'','displayUrl'=>'http://www.umidirect.com','imageUrl'=>'http://cdn.savings.com/logo/2374083.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8924,'id'=>206547,'name'=>'UnbeatableSale','description'=>'With over 30 years of experience under their belts, the brains behind UnbeatableSale have found no trouble in consistently remaining one of the Top 400 Internet Retailers on the web.<br><br> 

With a massive selection of high-quality products from trusted brand names like Sharp, Bobbi Brown, Compaq and more, Unbeatable Sale is devoted to bringing its customers the very best UnbeatableSale deals in electronics, jewelry, furniture, healthy and beauty and more.<br><br> 

UnbeatableSale offers discounts often up to 70% or even 80% off the original prices of high-end products and free standard shipping on select products throughout their UnbeatableSale site, <a href=\"http://www.unbeatablesale.com\">UnbeatableSale</a> definitely makes it a point to stand out from the crowd of internet discount dealers.<br><br> 

Here at Savings.com, we seek out the best UnbeatableSale coupon codes and Unbeatable Sale promotional codes so that our followers can take full advantage of the awesome UnbeatableSale coupons and sales that are always going on. So be sure to check out our site for the latest UnbeatableSale promotions and enjoy the savings! <br><br>','displayUrl'=>'http://www.unbeatablesale.com/','imageUrl'=>'http://cdn.savings.com/logo/27004.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8925,'id'=>311430,'name'=>'Uncle Norm\'s Marine Products Inc.','description'=>'','displayUrl'=>'http://www.UncleNormsMarineProducts.com','imageUrl'=>'http://cdn.savings.com/logo/2682910.gif','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>8926,'id'=>239633,'name'=>'Uncle Sams','description'=>'It\'s late, the lights are down low with candles lit throughout the room. The bathroom door opens up as you anxiously wait to see what sexy number your wife has decided to put on. Her choice was camouflage. Kind of a buzz kill isn\'t it? But in actuality, if your wife recently visited Uncle Sams you might just be in for the night of your life.

In the business over 30 years, Uncle Sams specializes in bringing authentic military apparel as well as military inspired clothing to the public at a very affordable price. Items featured in GQ Magazine in 2009, as well as being able to boast clients such as Bono, Calvin Klein, 50 cent and the late Michael Jackson have helped to accentuate that Uncle Sams is so much more than the camouflage image that arose in your mind earlier. On sale now is the Woodland Camo String bikini top and bottoms for $14.75 each.

Whether visiting their store in Greenwich Village or shopping via their amazing website, which has a fantastic Live Chat option, you\'ll find an eclectic offering that encompasses everything from knives, GPS systems, flashlights, parachute (that\'s right we said parachutes) to Baby Pink Camo \"Booty Camp\" Booty Shorts, Camo String Bikinis, pea coats for men and women, children\'s attire and a large variety of shoes that range from boots to sandals. In other words, you\'ll find everything.

Featuring a section on their website titled \"Deals\", you\'re insured to always be up to date on whether that parka you\'ve had your eye on is suddenly more affordable. And when it is, don\'t forget to take note of their reputable Return/Exchange policy as well as the free shipping that is offered to new customers on the first purchase.

Check out our latest <a href=\"http://www.armynavydeals.com\">Uncle Sams</a> coupons and Uncle Sams deals and discounts right here at Savings.com to save even more money on your order. If you\'re in the market for something military, military inspired or even civil service inspired, such as the EMT Round Badge or the Police Tactical Belt, these deals are waiting for you. 

Let\'s be honest, these guys aren’t just sparring in the world of fashion battles; they\'ve taken over the war.','displayUrl'=>'http://www.armynavydeals.com','imageUrl'=>'http://cdn.savings.com/logo/952005.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8927,'id'=>239547,'name'=>'UnclesGames.com','description'=>'','displayUrl'=>'http://www.unclesgames.com/','imageUrl'=>'http://cdn.savings.com/logo/924976.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20237),
  array('id_index'=>8928,'id'=>295300,'name'=>'Uncle Vic','description'=>'','displayUrl'=>'http://www.unclevic.com','imageUrl'=>'http://cdn.savings.com/logo/1735480.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8929,'id'=>5133,'name'=>'Uncommon Goods','description'=>'Dedicated to bringing their customers a wide selection of gorgeous and unique eco-friendly products from around the world, UncommonGoods is quickly becoming a leading online retailer for goods made from reclaimed and recyclable materials. With a massive selection of home décor, art, dishes, books, gifts and more, <a href=\"http://www.uncommongoods.com\">UncommonGoods</a> has slowly cultivated a growing following of loyal customers with its eclectic mix of products scavenged from flea markets, craft fairs, famous artists and favorite eco-friendly brands. Although UncommonGoods promotional codes and coupon codes are often hard to come by, here at <a href=\"http://www.savings.com\">Savings.com</a> we send out our group of eco-friendly Deal Hunters as often as possible to track down and post to our site all the valid UncommonGoods discounts and promotional codes to be found. We want to be sure our loyal followers can come to our site and take full advantage of the UncommonGoods discounts up to 40% off the original prices of select goods, and we want to make sure they are doing so by using only the best UncommonGoods coupon codes and promotional codes on the web. So be sure to check us out before heading to the merchant\'s site for the latest and best in UncommonGoods sales and promotions so you can get the biggest bang for your buck when it comes to saving the environment with ultra-cool eco-friendly goods.','displayUrl'=>'http://www.uncommongoods.com','imageUrl'=>'http://cdn.savings.com/logo/1177995.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8930,'id'=>233060,'name'=>'Under Armour','description'=>'Under Armour was founded in 1996 with a mission to make a T-shirt that would wick sweat from your skin and thus increase performance.  From that small start, Under Armour has become a leading manufacturer of performance apparel.  With its patented technology, Under Armour keeps you cool when it\'s hot, warm when it\'s cold and dry and light in any weather.  Under Armour apparel features chafe resistant and quick drying construction, UPF 30+ skin protection, temperature regulation and great performance fit.  Whether you\'re a runner, hunter, swimmer or skier, Under Armour has performance apparel to enhance your experience.   Under Armour performance collections include UA Blitz, UA Tech, UA Metal and include everything from sports bras to running shoes to keep your comfortable covered.  Professional athletes and weekend warriors alike put their trust in Under Armour to keep them dry and comfortable under the most strenuous conditions.  You can count on Under Armour for innovative apparel that improves your performance.  And you can count on Savings.com for the best Under Armour coupons and promo codes to save you the big bucks on your purchase from <a href=\"http://www.underarmour.com\">UnderArmour.com</a>.','displayUrl'=>'http://www.underarmour.com/','imageUrl'=>'http://cdn.savings.com/logo/1177997.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8931,'id'=>206749,'name'=>'Undergear','description'=>'When you are looking for stylish men\'s underwear, be sure to head to Undergear. They feature a huge assortment of items from all of the top brands in the industry. With a focus on providing quality merchandise at affordable prices, they have become one of the premier online retailers for every type of men\'s undergarment.

While their primary focus is on underwear, Undergear also provides an excellent variety of swimwear, clothing, shoes and accessories. They feature top designers like Diesel, Calvin Klein and Hugo Boss so you always know that you are getting a top quality garment. Best of all, by signing up to receive emails, you automatically qualify for even bigger discounts off their already great prices.

In today\'s tough economic climate, it is important to save money whenever possible. Wouldn\'t it be great to have an <a href=\"http://www.undergear.com\">Undergear promo code</a> when you are ready to go shopping? Fortunately, we here at Savings.com carry Undergear coupons so come visit us before making your next purchase.','displayUrl'=>'http://undergear.com','imageUrl'=>'http://cdn.savings.com/logo/27013.gif','allowPartnerDeals'=>'true','categoryIds'=>20821),
  array('id_index'=>8932,'id'=>6003,'name'=>'Underground Station','description'=>'','displayUrl'=>'http://www.undergroundstation.com','imageUrl'=>'http://cdn.savings.com/logo/1115975.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>8933,'id'=>245437,'name'=>'Unica Home','description'=>'','displayUrl'=>'http://www.unicahome.com','imageUrl'=>'http://cdn.savings.com/logo/1139909.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8934,'id'=>296643,'name'=>'Uniform Advantage','description'=>'','displayUrl'=>'http://www.uniformadvantage.com','imageUrl'=>'http://cdn.savings.com/logo/2392916.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8935,'id'=>236913,'name'=>'Uniform City','description'=>'It’s time to suit up for success!
<br /><br />
We’re not talking about swimsuits, though – we’re talking about scrubs! Savings.com is proud to welcome you to Uniform City. Population: hundreds of discounts…
<br /><br />
Uniform City has over 40 years experience when it comes to clothing medical professionals in the most comfortable and stylish scrubs, lab coats, shoes and accessories around. Whether you’re looking for tops, pants, medical badges, stethoscopes, pens or even nurse appreciation gifts – Uniform City is sure to have the items you want and need in stock and at affordable prices that won’t stress your budget.
<br /><br />
You can save up to 50% off the original prices of select items throughout the site, get free shipping on orders of $60 or more, and can snatch up the latest styles from brands like Dickies, Silky Scrubs, Cherokee, Baby Phat, Scrub Elements and more at just a fraction of the original cost. Uniform City even offers embroidery services for custom logos or personalization!
<br /><br />
Uniform City has nine retail stores on the East coast, but their website is perfect for bargain-seeking customers worldwide. You can browse the massive selection of scrubs and more at Uniform City online with ease and quickly order the items you need at affordable prices that will leave you plenty of money left over to reward yourself when your hard working day is done.
<br /><br />
So check out our latest <a href=\"http://www.uniformcity.com\">Uniform City</a> coupons and Uniform City coupon codes and get ready for warm weather or any weather in spectacular and comfortable scrubs for all seasons at amazing, low prices that are sure to make you smile.','displayUrl'=>'http://www.uniformcity.com','imageUrl'=>'http://cdn.savings.com/logo/1070078.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8936,'id'=>509291,'name'=>'Union City Auto Glass Replacement 510-896-3390','description'=>'','displayUrl'=>'http://www.unioncitywindshieldshop.com/','imageUrl'=>'http://cdn.savings.com/logo/2937023.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>8937,'id'=>296609,'name'=>'UNiQ Cycle Sounds Motorcycle Speakers and Audio','description'=>'','displayUrl'=>'http://www.uniqcycle.com','imageUrl'=>'http://cdn.savings.com/logo/2377282.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8938,'id'=>255784,'name'=>'Unique Glass Works','description'=>'','displayUrl'=>'http://www.uniqueglassworks.com/','imageUrl'=>'http://cdn.savings.com/logo/1506396.gif','allowPartnerDeals'=>'true','categoryIds'=>20875),
  array('id_index'=>8939,'id'=>255612,'name'=>'Unique Monograms','description'=>'','displayUrl'=>'http://uniquemonograms.mybisi.com/','imageUrl'=>'http://cdn.savings.com/logo/1524011.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20213),
  array('id_index'=>8940,'id'=>249205,'name'=>'Unique Photo','description'=>'Unique Photo\'s inventory contains over 10,000 photographic products, including the latest model digital cameras, traditional cameras and accessories, and darkroom equipment as well as a comprehensive inventory of films. They carry name brands such as: Kodak, Fuji, Canon, Nikon, Sony, Pentax, Minolta, Olympus, Hasselblad, Mamiya and more.','displayUrl'=>'http://www.uniquephoto.com/','imageUrl'=>'http://cdn.savings.com/logo/1203968.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8941,'id'=>285104,'name'=>'Unique Soles','description'=>'Unique Soles knows that the closest we come to the earth is through our feet. We sometimes walk miles a day, pressing our feet on the ground, so naturally we should demand the best quality, protection and comfort from our footwear. That is why the Oregon-based company sells the most sensible footwear to honor the close connection between feet and earth: Earth Shoes.

The Restorative Excercise Institute found that Earth Shoes, when worn against normal exercise footwear, can burn more fat, reduce more body mass, and enhance breathing when worn for similar exercises.

That\'s because Earth Shoes have a unique sole that positions one\'s toes at a higher angle than one\'s heels. The 3.7 degree incline serves to strengthen our leg muscles and tone our bodies in a way that normal soles do not. So any walk to the grocery store or hike in the wilderness turns into a greater exercise for you.

Beyond their health benefits, Earth Shoes are environmentally-friendly, built with Bio-cushions that are made of 70% recycled material, so you can do good for the environment, while you look good and feel good. Earth Shoes also feature Kalso Negative Heel Technology which can help strengthen and tone the body while exercising.

Whether you are on the hunt for shoes, sandals, boots, slippers or even clogs, all can be found for a great deal with Unique Sole coupons. Earth Shoes are affordable gear for the on-the-go green advocate, and as a committed distributor of their products, Unique Sole provides tons of both Men\'s and Women\'s designs to fit your most ardent runner or most casual walker.

These guys offer free shipping on every order, and there are usually quite a few sale items offered for 20-35% off of their already low prices. Don\'t get caught on the trails with your average gear. Make it more interesting, and green, and pick up a pair of Earth Shoes.

Additional <a href=\"http://www.uniquesoles.com\">Unique Sole</a> discounts can be found at Savings.com, including savings on sale items and Unique Sole coupons for free shipping. So when you want to get closer to mother earth and get fit at the same time, check out the latest Unique Sole deals and make the statement that your feet and body are earth-friendly.','displayUrl'=>'http://uniquesoles.com/','imageUrl'=>'http://cdn.savings.com/logo/1664605.png','allowPartnerDeals'=>'true','categoryIds'=>20728),
  array('id_index'=>8942,'id'=>316932,'name'=>'UniquePearl.com','description'=>'$model.description','displayUrl'=>'http://www.uniquepearl.com/','imageUrl'=>'http://cdn.savings.com/logo/2824814.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>8943,'id'=>313999,'name'=>'UNITED SPIRIT OF AMERICA','description'=>'','displayUrl'=>'http://www.usa-spirit.com','imageUrl'=>'http://cdn.savings.com/logo/2686964.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>8944,'id'=>299750,'name'=>'United States Navy Memorial Gear Locker','description'=>'','displayUrl'=>'http://www.navymemorialstore.com','imageUrl'=>'http://cdn.savings.com/logo/2606983.gif','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>8945,'id'=>217831,'name'=>'United Vacations','description'=>'Whether you’re planning a vacation within the United States of America, to Canada, Mexico, the Middle East, Asia, Europe, Africa or to some other domestic or exotic location, United Vacations is sure to have a vacation package that’s right for you.<br /><br />

If you’re looking to save on United Vacations airfare or are in search of affordable hotel accommodations, rental cars or activities like theme parks, shows, kayaking, horseback riding or whatever else suits your fancy, be sure to check out the latest deals United Vacations has to offer.<br /><br />

For those traveling alone or with family and friends, United Vacations has travel deals for all the top destinations worldwide, along with specials on the hottest shows in town or the coolest activities to take part in once you’ve arrived. Thanks to United Vacations, you can save a bundle on luxury airfare and hotel accommodations and still have money left over for souvenirs and fun adventures.<br /><br />

Sign up for the United Vacations email newsletter for updates on the latest United Vacations travel deals and vacation packages or head to the United Vacations website to find out how to save money on featured hotels and destinations, as well as to find out about top activities at different resorts around the world.<br /><br />

To save even more money on your <a href=\"http://www.unitedvacations.com\">United Vacations</a> booking, remember to check out our site right here at Savings.com for some of the hottest United Vacations coupons, United Vacations promo codes and United Vacations deals the web has to offer and get ready to have the adventure of a lifetime at just a fraction of the cost.<br /><br />','displayUrl'=>'http://www.unitedvacations.com','imageUrl'=>'http://cdn.savings.com/logo/29711.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8946,'id'=>236166,'name'=>'United Vacuum','description'=>'United Vacuum Online sells a wide selection of vacuum cleaner products for makes such as Fantom, Eureka, Sanitaire, Miele, Sanyo, Bissell, Sharp, Panasonic, Oreck, Filter Queen, Royal, Samsung and more.','displayUrl'=>'http://www.unitedvac.com/index.php?partnerId=5','imageUrl'=>'http://cdn.savings.com/logo/655617.gif','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8947,'id'=>316006,'name'=>'Universal Ink and Toner','description'=>'','displayUrl'=>'http://www.universalinkandtoner.com','imageUrl'=>'http://cdn.savings.com/logo/2813225.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8948,'id'=>235863,'name'=>'Universal Mania','description'=>'','displayUrl'=>'http://www.universalmania.com','imageUrl'=>'http://cdn.savings.com/logo/635206.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8949,'id'=>236518,'name'=>'Universal Studios Hollywood','description'=>'Universal Studios Hollywood is located just above the 101 freeway in Los Angeles, California. Owned by NBC Universal, Universal Studios Hollywood provides an all day entertainment destination. With a theme park, studio tour, the CityWalk, shopping and dining, a movie theater, and the Gibson Amphitheatre, Universal Studios Hollywood houses all the entertainment options you could possibly handle. Universal Studios Hollywood theme park has attractions like \"Shrek 4-D,\" \"Jurassic Park, the Ride,\" and the Simpsons ride, along with the famous Universal Studios Hollywood studio lot tour where visitors are able to experience TV and movies from behind the scenes. Before you buy a day pass or an annual pass, grab a Universal Studios Hollywood coupon from Savings.com to help you save on your day of entertainment.','displayUrl'=>'http://www.universalstudioshollywood.com/','imageUrl'=>'http://cdn.savings.com/logo/715178.png','allowPartnerDeals'=>'true','categoryIds'=>20228),
  array('id_index'=>8950,'id'=>295475,'name'=>'University Books Online','description'=>'','displayUrl'=>'http://www.universitybooksonline.com/','imageUrl'=>'http://cdn.savings.com/logo/1737642.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8951,'id'=>252031,'name'=>'University of Nebraska Press','description'=>'','displayUrl'=>'http://www.nebraskapress.unl.edu/','imageUrl'=>'http://cdn.savings.com/logo/1494402.png','allowPartnerDeals'=>'true','categoryIds'=>20723),
  array('id_index'=>8952,'id'=>242475,'name'=>'UnlockCell','description'=>'','displayUrl'=>'http://www.unlockcell.com/','imageUrl'=>'http://cdn.savings.com/logo/1177999.png','allowPartnerDeals'=>'true','categoryIds'=>20838),
  array('id_index'=>8953,'id'=>316507,'name'=>'Uno Alla Volta','description'=>'$model.description','displayUrl'=>'http://www.unoallavolta.com/','imageUrl'=>'http://cdn.savings.com/logo/2827113.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8954,'id'=>301917,'name'=>'Up and Riding','description'=>'','displayUrl'=>'http://www.upandriding.com','imageUrl'=>'http://cdn.savings.com/logo/2617267.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8955,'id'=>285202,'name'=>'Up All Night Studio','description'=>'','displayUrl'=>'http://www.upallnightstudio.net/','imageUrl'=>'http://cdn.savings.com/logo/1665158.png','allowPartnerDeals'=>'true','categoryIds'=>20875),
  array('id_index'=>8956,'id'=>238029,'name'=>'UpDown','description'=>'People hesitate investing in the stock market. They don\'t want to take risks only to lose our money. Poor recent market performance and inexperience with trading only reinforce this. Two Harvard Business School students and a Harvard College graduate noticed this trend and founded UpDown, a website where visitors use virtual money to buy and trade stock.

This isn\'t a run-of-the-mill, college student\'s business dream though. Joachim Schoss, a successful and famous European Internet entrepreneur, provided funding for this particular venture. Both his money and his many years of experience with investments and business strategy helped develop this innovative company into the success it is today. Media outlets such as The Wall Street Journal and CNN praise the website for its novelty and usefulness. As long as the stock market exists, people will want to invest in it and these guys will continue to thrive.

With UpDown, you learn the ways the market moves, what the industry language and concepts mean, and, most importantly, how to make wiser investment decisions. You can then use your experience to compete in the website’s contests to see which members can beat the S&P 500. If you use your financial skills well enough and beat the index, you can win up to $500 in real money in the monthly contests.

These guys also offer a referral program, which is a great way to earn real money. If your friends or family members win a contest, the website rewards you with a bonus equal to 10% of your referral\'s winnings. By using this innovative service, you not only save money that you could have wasted on inept investments, but you also enjoy the chance to earn real money.

If you are looking to refine your financial skills before entering the real market, are wanting to test an investment plan, or are just eager to gain some more knowledge about investing and trading, these guys offer everything you are looking for.

With the latest <a href=\"http://www.updown.com\">UpDown</a> coupons and UpDown discounts and coupon codes from our site right here at Savings.com, you can start your account with this awesome company for free and use their services immediately. So get ready to learn the ins and outs of the stock market world and be sure to spread the word to your friends and family members.','displayUrl'=>'http://www.updown.com','imageUrl'=>'http://cdn.savings.com/logo/764861.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>8957,'id'=>216922,'name'=>'Upper Deck','description'=>'','displayUrl'=>'http://www.upperdeck.com','imageUrl'=>'http://cdn.savings.com/logo/619649.gif','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>8958,'id'=>312379,'name'=>'UPR Products.com','description'=>'','displayUrl'=>'http://www.uprproducts.com','imageUrl'=>'http://cdn.savings.com/logo/2684329.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>8959,'id'=>234904,'name'=>'UPrinting','description'=>'','displayUrl'=>'http://www.uprinting.com','imageUrl'=>'http://cdn.savings.com/logo/623449.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8960,'id'=>290358,'name'=>'Upscale Costumes','description'=>'','displayUrl'=>'http://www.upscalecostumes.com/','imageUrl'=>'http://cdn.savings.com/logo/1691826.png','allowPartnerDeals'=>'true','categoryIds'=>20825),
  array('id_index'=>8961,'id'=>287247,'name'=>'Upscale Gallery','description'=>'','displayUrl'=>'http://www.upscalegallery.com','imageUrl'=>'http://cdn.savings.com/logo/1667233.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8962,'id'=>272100,'name'=>'Upscale Lighting','description'=>'Upscale Lighting fulfills their motto: Where elegance, value, and convenience come together! We\'ve found much inspiration in both a visit to their web page or their showroom. They have helpful experts available to answer questions and help with any design or function issues you may have.

Looking for energy efficient lighting? The new LED lights? Whether it is discreet, hidden light sources, or flashy crystal hung lamps and chandeliers for that rich and elegant look, these guys have them all. The brands they stock run from Access, American Fluorescent, Craftmade, Eco-Story, and Light Emitting Designs to Maxim, to Tiffany, to ZiQi.

Not only that, the owner - Lars Dahlhaus - comes to the lighting business from the manufacturer side of the industry. He knows light fixtures as few people in this industry do. He comes from the Dahlhaus family, which is famous for beautiful, handmade reproductions of vintage lighting fixtures. At Upscale Lighting, Lars Dahlhaus has added modern and cutting edge lighting design to the Dahlhaus vintage design heritage. It makes a rich mix, where everyone can find something that meets their taste and budget.

If you’re looking for energy saving light fixtures, then these guys definitely have a large selection you’re sure to fall in love with – with affordable prices to match! They have everything from chandeliers, to wall sconces and LED fixtures. Some of those wall sconces were also examples of the cutting edge design. And, on the high end, they have great choices at a relative bargain compared to other online retailers. Add in Upscale Lighting deals offered for phone, web or on-site orders and you\'re really looking at something special.

These guys also carry a wide assortment of ceiling fans, path lights, and other outdoor lighting solutions, as well as just about every variety of light bulb known, even reproduction antique bulbs. In addition, they carry some stained glass windows in Craftsman and Tiffany designs. Windows, after all, also provide light, and stained glass provides color, style, and warmth, as well.

It is a wonderful place to visit in person (if you are near the Brooklyn showroom), or browse on the web at any hour of the day or night. Be sure to check the website for Upscale Lighting\'s discounts, too. They can appear in banner text or under the tab \"Hot Deals\'.

Online shopping incentives get ever better with the latest <a href=\"http://www.upscalelighting.com\">Upscale Lighting</a> discounts and Upscale Lighting coupon codes and promotions from our site right here at Savings.com, where you can snatch up great deals like free shipping on orders over $99 and discounts up to $1,000 off your order. 

So get ready to light up your life with quality light fixtures from the brands you love most at affordable prices that are sure to make you smile.','displayUrl'=>'http://www.upscalelighting.com/','imageUrl'=>'http://cdn.savings.com/logo/1633266.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8963,'id'=>257671,'name'=>'Uptown Enterprises','description'=>'Uptown Enterprises carries the entire Zippo catalog online at discount prices. This includes Zippo lighters, Harley Davidson Zippo lighters and gift sets, Cigar Cutters, ZipLight pocket flashlights, Zippo tape measures, Zippo pocket knives and Greenskeeper golf tools. They also carry stainless steel hip flasks, leather wrapped flasks and cigarette cases. The site also features custom engraving on any product for those personalized gifts, collectibles or keepsakes.','displayUrl'=>'http://www.uptownenterprises.com','imageUrl'=>'http://cdn.savings.com/logo/1524334.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8964,'id'=>252450,'name'=>'Upurea','description'=>'Upurea is a self-described \'eco-chic boutique\' with a bevy of stores in the United States of America and Canada and a popular online website famous among green mavens around the world. Since 2006, <a href=\"http://www.upurea.com\">Upurea</a> has been stocking its shelves and warehouses with a massive selection of eco-friendly cosmetics, skincare, styling tools, fragrances and more from over thirty trusted and well-known brands like La Vanile, Juice Beauty, Trilogy and oh so many more. Upurea offers free standard ground shipping on all orders of $60 or more unless the customer specifies otherwise, as well as discounts up to 70% off the original prices of eco-friendly cult classics throughout the site. Upurea is also a hit with customers thanks to free samples with all orders and free deluxe gifts with select purchases while supplies last. Here at <a href=\"http://www.savings.com\">Savings.com</a>, we like to think we\'re doing our part to help the environment. So we\'re pleased as pie to post as many valid <a href=\"http://www.savings.com/m-Upurea-Pure-Natural-Beauty-coupons.html\">Upurea coupons and codes</a> to our site as possible so that our fellow lovers of all things green and organic can stock up on the organic beauty brands they love without wincing at prices. So remember to check out our site for the latest and greatest in Upurea coupon codes and promo codes and be sure to snag some of the best Upurea discounts on the web with some of the hottest Upurea coupons and codes around.','displayUrl'=>'http://www.upurea.com/','imageUrl'=>'http://cdn.savings.com/logo/1497481.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8965,'id'=>333753,'name'=>'Upward Sports','description'=>'','displayUrl'=>'http://www.upward.org/military/','imageUrl'=>'http://cdn.savings.com/logo/2827893.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20899),
  array('id_index'=>8966,'id'=>239159,'name'=>'UpYourRide.com','description'=>'','displayUrl'=>'http://www.upyourride.com','imageUrl'=>'http://cdn.savings.com/logo/839333.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8967,'id'=>260077,'name'=>'Urban Original','description'=>'','displayUrl'=>'http://www.urbanog.com/','imageUrl'=>'http://cdn.savings.com/logo/1534286.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20728),
  array('id_index'=>8968,'id'=>6880,'name'=>'Urban Outfitters','description'=>'For the latest fashions and hottest styles, there is no better place to shop online than Urban Outfitters. A top retailer of men\'s and women\'s apparel, they also provide a huge assortment of products for the city home. Best of all, shipping is only $10 regardless of the size of your order.

You can only be young once, and Urban Outfitters has everything you need to round out your busy lifestyle. Whether you are looking for a cool new t-shirt or a reasonably priced couch, Urban Outfitter\'s exhaustive website offers a huge variety of products, many of which are available nowhere else.

These days, everyone is trying to save money whenever possible. That\'s why we at Savings.com are so excited to offer Urban Outfitters coupons on our website. The next time you are ready to shop and save, come visit us, clip an <a href=\"http://www.urbanoutfitters.com\">Urban Outfitters coupon</a> for yourself and head over to urbanoutfitters.com to shop at your favorite store online.

Urban Outfitters sometimes offers coupons like this one:<br><a href=\"http://cdn.savings.com/img/Urban-Outfitters-Coupon.png\"><img src=\"http://cdn.savings.com/img/Urban-Outfitters-Coupon.png\" alt=\"0\" border=\"0\" width=\"100\" alt=”Urban Outfitters”></a>','displayUrl'=>'http://www.urbanoutfitters.com/6098','imageUrl'=>'http://cdn.savings.com/logo/2935544.jpeg','allowPartnerDeals'=>'false','categoryIds'=>'Array'),
  array('id_index'=>8969,'id'=>248212,'name'=>'Urban Minx','description'=>'Urban Minx was founded by Londoner Melissa Walton. Growing up, her cheeky, fun-loving, and somewhat naughty nature earned her the nickname of Minx. So when Melissa wanted to open her own boutique, there really was not a question about the name. Urban Minx was born with the only name it could have. And as they like to say there, \"We pride ourselves in bringing out the \"Minx\" in everyone!\"

UrbanMinx.com is your one-stop fashion shop for designer clothing. With brands like Australia Luxe, Miss Me, Diesel, Hudson, Junk Food, Juicy Couture, and Black Halo, you are sure to find what you are looking for. This site is a plethora of high quality purses, clothing and accessories for fashion forward women, and men as well. 

Just because you are buying high-end designer clothing, does not mean that you will necessarily be paying designer prices. Many of the designer brands at this store are discounted, so save money and look great. This is the place to shop like a celebrity without having to pay celebrity prices.
Looking fierce every day is a great thing, but if you are looking for something a bit more formal, then these guys have you covered there as well. Dress like a Hollywood A-Lister for your next big night out on the town. With brands like Black Halo and Miss Me, you are just a click away from looking red carpet fabulous. Watch out for the paparazzi.

Urban Minx isn\'t just for clothes and hand bags. They also carry several lines of high quality beauty products. Shoe polish touch up, fashion tape, nail polish and fashion conscientious bras are all have their place at this site. Melissa Walton\'s company has left little to be desired from a fashion outlet.

To save even more money on the designer brands you love, remember to check out our site right here at Savings.com for the latest and greatest in <a href=\"http://www.urbanminx.com\">Urban Minx</a> coupons and Urban Minx codes and discounts. Get ready to experience genuine designer clothes at a bargain price. Remember, everybody has a caged minx inside, so find your inner minx and let loose.','displayUrl'=>'http://www.urbanminx.com/','imageUrl'=>'http://cdn.savings.com/logo/1494479.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8970,'id'=>255620,'name'=>'Urban Posters','description'=>'Urban Posters is a new website designed to cater to your specific wall art needs. If you want a store that has a selection of over 500,000 different posters, then store is the site for you.

These guys offer a wide range of posters, from movie and comic book, to music and those fancy old vintage posters, they have it all. With prices ranging from cheap to insanely cheap, they guarantee that you will not have to worry about spending all your money to enjoy these beautiful posters. 

The site is also being constantly updated, with new posters coming out each week. This means that you can get your favorite new movie poster within days of the movie\'s release. If it\'s a classic print from the Jungle Book, they have that too. Or maybe you had Harry Potter in mind. Whatever your poster poison, these guys are sure to have the perfect picture to suit your artful state of mind.

Aside from the numerous movie, dorm, music, sport, vintage and comic posters on display, there is also a selection of framed art for as well. Not only can you buy these works of beauty for a cheap price, but you can also frame your own picture or poster, forever preserving its glamour. Recent deals have included $4.98 sale on thousands of posters.

Aside from the good prices, unique and varied choice of goods and the incredible shipping. The bonus to being a member is getting access to the latest news and latest product info as soon as they come out. That the poster you\'ve been waiting for has finally come, and now is your chance to grab it. Your blank walls will thank you for making some additions today.

Urban Posters offers their customers unique discounts, such as the amazing shipping price of only $4.99. This bargain again makes sure you won\'t spend all your money on shipping (or waiting as a matter of fact). These guys offer incredibly fast shipping to get you your poster exactly on time.
 
So be sure to check out our site right here at Savings.com for the latest and greatest in Urban Posters coupons and <a href=\"http://www.urbanposters.com\">Urban Posters</a> discounts and coupon codes and get ready to plaster your walls in all the pop art, landscapes, classical paintings, rock band memorabilia and more you love without having to worry about breaking the bank.','displayUrl'=>'http://www.urbanposters.com/','imageUrl'=>'http://cdn.savings.com/logo/1505984.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8971,'id'=>218074,'name'=>'Urban Scooters','description'=>'UrbanScooters.com offers a huge selection of brand name, electric scooters, gas scooters, electric bikes, pocket bikes, parts and accessories. The brands we sell include top names like Currie, GT, Go-Ped, LashOut, Freedom, Boreem, Schwinn, Mongoose, Mosquito, Rad2Go and more. We\'ve sold thousands of motorized scooters and bikes and are the most heavily trafficked web site in our product niche. Make no doubt about it, motorized scooters are a hot ticket item.','displayUrl'=>'http://urbanscooters.com/','imageUrl'=>'http://cdn.savings.com/logo/1495397.gif','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>8972,'id'=>290921,'name'=>'Urinozinc','description'=>'','displayUrl'=>'http://www.urinozinc.com','imageUrl'=>'http://cdn.savings.com/logo/1701196.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20857),
  array('id_index'=>8974,'id'=>235536,'name'=>'US Appliance','description'=>'US Appliance is a factory authorized source for name brand home appliances.','displayUrl'=>'http://store.yahoo.com/cgi-bin/clink?usappliance+k8WLns+index.html','imageUrl'=>'http://cdn.savings.com/logo/626528.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8975,'id'=>240091,'name'=>'US Armorment','description'=>'','displayUrl'=>'http://www.usarmorment.com','imageUrl'=>'http://cdn.savings.com/logo/1006774.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8976,'id'=>297834,'name'=>'US Bones.com','description'=>'','displayUrl'=>'http://www.usbones.com','imageUrl'=>'http://cdn.savings.com/logo/2451726.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8977,'id'=>299745,'name'=>'US Entry Law','description'=>'','displayUrl'=>'http://usentrylaw.com/services/military/','imageUrl'=>'http://cdn.savings.com/logo/2606913.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>8978,'id'=>244800,'name'=>'US Medical Supplies','description'=>'','displayUrl'=>'http://www.usmedicalsupplies.com/','imageUrl'=>'http://cdn.savings.com/logo/1177989.png','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>8979,'id'=>287575,'name'=>'US Miles','description'=>'','displayUrl'=>'http://ad.doubleclick.net/clk;224404187;6805272;f?http://www.usmiles.com','imageUrl'=>'http://cdn.savings.com/logo/1670495.png','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>8980,'id'=>301376,'name'=>'US Military Wedding & Event Photography','description'=>'','displayUrl'=>'http://www.usmilitaryweddings.com','imageUrl'=>'http://cdn.savings.com/logo/2614619.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>8981,'id'=>262308,'name'=>'US Navy Seal Store','description'=>'','displayUrl'=>'http://www.usnavysealstore.com','imageUrl'=>'http://cdn.savings.com/logo/1560642.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8982,'id'=>301909,'name'=>'US Patriot','description'=>'','displayUrl'=>'http://www.uspatriottactical.com/','imageUrl'=>'http://cdn.savings.com/logo/2620458.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8983,'id'=>279825,'name'=>'USpets','description'=>'','displayUrl'=>'http://www.uspets.com/','imageUrl'=>'http://cdn.savings.com/logo/2935406.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8984,'id'=>285005,'name'=>'US Remodelers','description'=>'','displayUrl'=>'http://www.usremodelers.com/','imageUrl'=>'http://cdn.savings.com/logo/1664412.png','allowPartnerDeals'=>'true','categoryIds'=>20876),
  array('id_index'=>8985,'id'=>247377,'name'=>'US Search','description'=>'','displayUrl'=>'http://www.ussearch.com/','imageUrl'=>'http://cdn.savings.com/logo/1497152.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>8986,'id'=>288596,'name'=>'US Standard Issue','description'=>'','displayUrl'=>'https://secure.usstandardissue.com/','imageUrl'=>'http://cdn.savings.com/logo/1670475.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8987,'id'=>233779,'name'=>'Us Weekly','description'=>'Us Weekly magazine site is a free online site that provides all your favorite style, health, beauty, and entertainment news, along with the gossip and dish that you love. The site will keep you up to date on all of your top celebrities, hot bodies, and very important people.

You can find out who is pregnant and who has just gotten fat. Get your fix of the top singers, the cast of Jersey Shore, the alcoholics, or the humanitarians without buying the magazine or switching on the television. Learn how to dress like a style god, following fashion icons and their designers. 

Find out how to get made-up like a professional, or someone who can afford a professional. Get the skin, lips, eyes, hair, and body that you always wanted. Be on the cutting-edge of music, movies and television. Keep up The Bachelorette\'s Ali and Roberto, now that season finale is over. Find out what other celebrities just got married.

Download the musical musings of Ian Drew and brag to all of your friends that you know O\'Neal McKnight\'s Song for Snooki, because you have to love that shortie from the Shore. Get the latest on Justin Bieber, his music, and backstage on his tour. Get the exclusive on Lady Gaga\'s bowling partner. Who even knew that Lady Gaga likes to bowl? Discover the secrets to an amazing body that only the stars seem to find. Be a part of the \"Fashion Police\" and cast your vote for best and worst dressed.

If you happen to discover that the Us Weekly magazine site is the site for you, then you can get the magazine risk-free for four weeks, an exclusive online offer. When you are sure that you love it, get Us Weekly at a fabulous new low price of only $5.99 per month. At four magazines per month, that is a bargain of only about $1.50 a week.

Us Weekly is the best source for all the best information on all of the hottest, craziest, fittest, pregnant, successful and painfully unsuccessful celebrities. Save 70% on a yearlong subscription with the <a href=\"http://www.usmagazine.com\">Us Weekly</a> coupons and Us Weekly coupon codes and discounts we’ve posted straight to our site right here at Savings.com. Don\'t miss the top news that everybody else is following.','displayUrl'=>'http://www.usmagazine.com','imageUrl'=>'http://cdn.savings.com/logo/620432.gif','allowPartnerDeals'=>'true','categoryIds'=>20724),
  array('id_index'=>8988,'id'=>239317,'name'=>'USA Beauty Supplies','description'=>'yahoo merchant','displayUrl'=>'http://www.usabeautysupplies.com/','imageUrl'=>'http://cdn.savings.com/logo/885660.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20733),
  array('id_index'=>8989,'id'=>261475,'name'=>'USA Canvas Art','description'=>'','displayUrl'=>'http://www.usacanvasart.com/','imageUrl'=>'http://cdn.savings.com/logo/1539603.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20868),
  array('id_index'=>8990,'id'=>291850,'name'=>'USA Equipment Direct','description'=>'','displayUrl'=>'http://usaequipmentdirect.com','imageUrl'=>'http://cdn.savings.com/logo/1709839.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8991,'id'=>303333,'name'=>'USA Military Medals','description'=>'','displayUrl'=>'http://www.usamilitarymedals.com/cyber-monday-a-6.html','imageUrl'=>'http://cdn.savings.com/logo/2620207.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20772),
  array('id_index'=>8992,'id'=>206269,'name'=>'USA TODAY','description'=>'USA Today is the leading news source in America today. USA Today uses cutting edge reporting on everything from politics, sports, food, travel, weather, careers, lifestyle, and everything in between. USA Today prides itself on accuracy in reporting, on the most interesting and up-to-date topics imaginable. It\'s no wonder that USA Today is found on the desks of the brightest minds and in the hands of learned readers. More than 10.3 million readers log on to USA Today.com and 5.2 million read the hard copy every single day! Be in the know with USA Today. At Savings.com you can have USA Today 24-hour online access and USA Today delivered to your door with amazing discount prices. Savings.com brings you all-access to USA Today with USA Today online coupons, USA Today discount promotions, USA Today coupon codes, USA Today savings, and USA Today promotions.','displayUrl'=>'http://www.myusatoday.com','imageUrl'=>'http://cdn.savings.com/logo/1613836.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8993,'id'=>255940,'name'=>'USA Western Wear','description'=>'','displayUrl'=>'http://www.usawesternwear.com/','imageUrl'=>'http://cdn.savings.com/logo/1506865.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20821),
  array('id_index'=>8994,'id'=>282431,'name'=>'usa4ink.com','description'=>'','displayUrl'=>'http://www.usa4ink.com/','imageUrl'=>'http://cdn.savings.com/logo/1661702.png','allowPartnerDeals'=>'true','categoryIds'=>20835),
  array('id_index'=>8995,'id'=>6813,'name'=>'USA Florist','description'=>'In this digital age, receiving actual mail has become a rare and exciting event. There\'s no way to brighten a loved one\'s day like a sending them a thoughtful bouquet of their favorite flowers. For over 15 years, USA Florist has been dedicated to providing Americans with stunning flower arrangements and to-your-doorstep delivery service. With a website running and ready to take orders 24 hours a day, 7 days a week, rest assured knowing your floral needs will be met.

Because USA Florist has stores all across the United States and in 140 other countries, same day deliveries ensure your loved ones receive fresh and professional bouquets and products no matter how much you\'re spending. From Valentine\'s Day to a new baby\'s arrival, they have the perfect gift for any occasion. The elegant and classic rose bouquet ranges in size from a quarter dozen up to a luscious 2 dozen. The roses are available in traditional romantic deep reds, to exotic bright lavender, to buttery yellows and pretty pinks. If you\'re looking for something a little funkier, try one of the Modern Cubes filled with fun Gerbera Daisies.

If flowers aren\'t the ideal gift for the situation, USA Florist offers a wide array of potted plants, balloons, and gift baskets for all occasions. If cooking isn\'t your strong suit, why not send the lucky someone a gourmet dessert basket? A wine basket filled with complementary chocolates or cheeses is another perfect and unexpected way to show that special someone you\'re thinking about them.

The site\'s unique \"Reminder Service\" feature sends out notices when special days like Mother\'s Day and family birthdays are around the bend, to help make sure busy customers don\'t forget or find themselves without a gift. We can help you get started planning these surprises right now. 
If there is no holiday around the corner - no problem. Just let your friends know you care by surprising them at their office with a healthy new potted plant to brighten up the place. If they receive an arrangement that\'s not exactly what you had in mind, USA Florist has a resolution policy and commitment to resolve your issue within 2 hours, updating you on the progress every step of the way.

The next time you order Mom some chrysanthemums, check out Savings.com first for USA Florist coupons and <a href=\"http://www.usaflorist.com\">USA Florist</a> coupon codes and discounts, like $5 off any arrangement, or 10% off any flowers or gifts. Take advantage of great promo codes to help you save a bundle on that beautiful bouquet and help make your special days even more memorable.','displayUrl'=>'http://usaflorist.com/','imageUrl'=>'http://cdn.savings.com/logo/26274.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>8996,'id'=>263425,'name'=>'usamallmasters','description'=>'','displayUrl'=>'http://www.usamallmasters.com/','imageUrl'=>'http://cdn.savings.com/logo/1607911.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>8997,'id'=>239385,'name'=>'usaprintworx.com','description'=>'','displayUrl'=>'http://www.usaprintworx.com','imageUrl'=>'http://cdn.savings.com/logo/911136.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8998,'id'=>239286,'name'=>'usbphoneworld','description'=>'','displayUrl'=>'http://www.usbphoneworld.com','imageUrl'=>'http://cdn.savings.com/logo/873851.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>8999,'id'=>239162,'name'=>'UsedCisco.com','description'=>'','displayUrl'=>'http://www.usedcisco.com','imageUrl'=>'http://cdn.savings.com/logo/841583.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9000,'id'=>305572,'name'=>'UsefulParts.com','description'=>'','displayUrl'=>'http://www.usefulparts.com/','imageUrl'=>'http://cdn.savings.com/logo/2621370.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20847),
  array('id_index'=>9001,'id'=>239552,'name'=>'Userful.com','description'=>'','displayUrl'=>'http://www.userful.com/','imageUrl'=>'http://cdn.savings.com/logo/924975.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>9002,'id'=>248313,'name'=>'UShopFast.com','description'=>'','displayUrl'=>'http://www.ushopfast.com','imageUrl'=>'http://cdn.savings.com/logo/1186733.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9003,'id'=>264144,'name'=>'USinsurance.com','description'=>'','displayUrl'=>'http://www.usinsurance.com/','imageUrl'=>'http://cdn.savings.com/logo/1612076.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9004,'id'=>288364,'name'=>'USMiles','description'=>'','displayUrl'=>'http://www.usmiles.com/','imageUrl'=>'http://cdn.savings.com/logo/1670437.png','allowPartnerDeals'=>'true','categoryIds'=>20234),
  array('id_index'=>9005,'id'=>300224,'name'=>'USMilitaryStuff.com','description'=>'','displayUrl'=>'http://www.usmilitarystuff.com','imageUrl'=>'http://cdn.savings.com/logo/2609064.gif','allowPartnerDeals'=>'true','categoryIds'=>20722),
  array('id_index'=>9006,'id'=>323009,'name'=>'USMilitarytravel.com','description'=>'','displayUrl'=>'http://www.usmilitarytravel.com','imageUrl'=>'http://cdn.savings.com/logo/2826971.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20892),
  array('id_index'=>9007,'id'=>220143,'name'=>'US Olympic Shop','description'=>'','displayUrl'=>'http://www.usolympicshop.com','imageUrl'=>'http://cdn.savings.com/logo/619883.gif','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>9008,'id'=>206610,'name'=>'US Outdoor','description'=>'US Outdoor is one of the leading online stores for outdoor gear and apparel.<br /><br />

US Outdoor has one of the finest collections of Alpine Skis, snowboards and backpacks. Volcom jackets and Dakine daypacks are always in stock at US Outdoor. US Outdoor is the best choice, offering free shipping and no sales tax, along with superior US Outdoor customer service and discounted US Outdoor prices on the gear you want most.<br /><br />

New collections at US Outdoor are in stock now! Get your US Outdoor goggles, jackets, climbing gear, hiking boots, and more for less at US Outdoor. US Outdoor has the gear you need to enjoy the outdoors at affordable US Outdoor prices.<br /><br />

Savings.com can help bring low <a href=\"http://www.usoutdoor.com\">US Outdoor</a> prices even lower. Check Savings.com for US Outdoor coupons, US Outdoor deals, US Outdoor special offers and US Outdoor rebates and US Outdoor discounts. At Savings.com, we update our great US Outdoor offers regularly, so check back often for the latest US Outdoor promotion codes and US Outdoor specials.<br /><br />

Don’t hide from the snow. Get out and feel the wind and chill of US Outdoor savings! Savings.com and US Outdoor are ready to get you the cheapest gear out there.<br /><br />','displayUrl'=>'http://www.usoutdoorstore.com/','imageUrl'=>'http://cdn.savings.com/logo/26237.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9009,'id'=>322318,'name'=>'USTA National Tennis Center','description'=>'','displayUrl'=>'http://a.yfrog.com/img612/2972/eg0y.png','imageUrl'=>'http://cdn.savings.com/logo/2823339.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>9010,'id'=>296663,'name'=>'Utah Skis','description'=>'','displayUrl'=>'http://www.UtahSkis.com/','imageUrl'=>'http://cdn.savings.com/logo/2600220.png','allowPartnerDeals'=>'true','categoryIds'=>20883),
  array('id_index'=>9011,'id'=>288452,'name'=>'utilityboardsupply','description'=>'','displayUrl'=>'http://www.utilityboardsupply.com','imageUrl'=>'http://cdn.savings.com/logo/1735285.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9012,'id'=>287054,'name'=>'uTOYpia','description'=>'','displayUrl'=>'http://www.utoypia.com','imageUrl'=>'http://cdn.savings.com/logo/1666421.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9013,'id'=>246637,'name'=>'Utrecht','description'=>'Utrecht Art Supplies - the very name sets creative hearts aflutter. For over six decades, these guys have supplied the raw materials that painters, sculptors and crafters use to make their visions reality. Whether you\'re a graphics design pro or a Sunday scrapbooker, this store has what you need. 

Over the years, Utrecht Art Supplies has become one of the leading names in art supplies. The company is as well-known for its quality and value as it is for its excellent selection. Featured brands include Bienfang, Winsor & Newton, Faber Castell, Grumbacher, more than 15,000 products in all.

Looking for a hard-to-find specialty like eco-friendly watercolor paper? These guys have got it, from top-flight brand Moleskine, no less. How about some art supplies for children? Utrecht stocks enough Sculpey, Crayola crayons and safety scissors to keep the little ones happily creating masterpieces for hours. 

Need a few quarts of gesso to prime your canvasses? Try the store\'s own famous house brand, formulated by artist Norman Gulamerian, who founded the company with his brother, Harold, in 1949. Frustrated because he couldn\'t find fine painter\'s canvas he needed in the States, Norman decided to import it himself from Europe. Word traveled, and soon he was supplying artist friends, then friends of friends and before long, he and Harold were among New York City\'s leading canvas suppliers. Their Brooklyn factory is still operating today, producing the same high-quality canvas as well as a full line of fine art oil and acrylic paints.

But all that history doesn\'t mean Utrecht\'s not up-to-the minute. It\'s got a Twitter account (Utrecht_Art), a Facebook page with more than 11,000 fans plus a blog (utrechtblog.com) that explores trends and happenings the art world while keeping customers abreast of sales, promotions and contests. Its Website, utrecht.com, is easy to navigate loaded with deals and discounts. Even an online learning center is full of how-tos, artist profiles and educational articles. 
<br /><br />
This store regularly offers clearance events, discounted (or free) shipping and online specials. And by clicking on the <a href=\"http://www.utrechtart.com\">Utrecht</a> coupons and Utrecht codes and promos here on Savings.com, you can make the deals even sweeter. Be sure to check back often, because new specials pop up regularly, and some are for a limited time only. Because just as Utrecht offers the very best in art supplies, Savings.com offers the very best deals for savvy art supply shoppers.','displayUrl'=>'http://www.utrechtart.com/','imageUrl'=>'http://cdn.savings.com/logo/1187943.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9014,'id'=>300454,'name'=>'Utsav','description'=>'','displayUrl'=>'http://www.utsavsarees.com/','imageUrl'=>'http://cdn.savings.com/logo/2610861.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9015,'id'=>285188,'name'=>'UWantSavings','description'=>'Would you rather buy a $1300 Nikon Digital camera at half the price? The hunt is over. UWantSavings is your one-stop shop for incredible prices on brand names, from Banana Boat, Calvin Klein and the NBA. 

One of USA Today\'s \"Ten Picks for the Best Sites to Find Deals Now\" and Action News\' \"8 Best Shopping Websites\", these guys have prices even lower than sale prices at many stores. Stores overstock, and manufacturers over-produce. They hunt for overstock and closeout items, and pass on the deals to you. Their parent company has over 50 years of experience in the closeout business, so you know they can find all the best prices. So whether it\'s made by Coleman or Weight Watchers, you\'ll get it at prices you won\'t find anywhere else.

Let\'s face it, we like bargains. We\'ll browse and haggle and spend hours on the hunt for the perfect price. Like that department store skirt? That cordless drill? Chances are, if another store has the same one for half the price, that\'s where we\'d buy it. When we shop online, how many websites do we visit before we finally find the biggest deal or the greatest savings? Wouldn\'t it be nice if we could find all our bargains in one spot? In fact, the only thing we like better than a bargain is a bargain we don\'t have to hunt for.

All new UWantSavings deals begin at midnight, central time, and there is at least one new product every day, so check back often. Shipping is free and items are always sent within two business days of the order. They are committed to providing top brand named merchandise at less than discount prices, with the best service possible. Look around and you\'ll find incredibly high user ratings and reviews.

You can find great deals every day at this online deal haven, but the savings keep on coming with the UWantSavings coupons and <a href=\"http://www.uwantsavings.com\">UWantSavings</a> coupon codes you can find right here at Savings.com. With these incredible offers, you\'ll never have to overpay again. Customers get the brands they want, with the speed and customer service they expect, at the prices far beyond what they imagined.','displayUrl'=>'http://www.uwantsavings.com/','imageUrl'=>'http://cdn.savings.com/logo/1665019.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9016,'id'=>250535,'name'=>'Uxsight.com','description'=>'','displayUrl'=>'http://www.uxsight.com/','imageUrl'=>'http://cdn.savings.com/logo/1494435.png','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>9017,'id'=>314360,'name'=>'Uzzeni','description'=>'','displayUrl'=>'http://www.uzzeni.com/','imageUrl'=>'http://cdn.savings.com/logo/2711997.png','allowPartnerDeals'=>'true','categoryIds'=>20217)
);
