<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>9534,'id'=>236623,'name'=>'X-Heli R/C Helicopters','description'=>'','displayUrl'=>'http://www.xheli.com','imageUrl'=>'http://cdn.savings.com/logo/1178061.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9535,'id'=>230210,'name'=>'XTreme Geek','description'=>'Xtreme Geek is here for all your geeky needs. Hi Tech electronic gadgetry and ingenious innovative gifts and collectibles sure to make the day. From Rex, the Electronic WatchDog to Dream Cheeky, the USB missile launcher, there is something for every geek here.

You can feed your geek and you can save up to 50% weekly just by signing up for exclusive e-mail specials and sales, even up to 80% by shopping in the clearance section. No matter the budget, they\'ve got something for you.

What do you get for the geek who has it all? You won\'t have to look for long, before you find that truly unique gift for a truly unique person. Looking for an executive gift for that genius IT specialist? How about the PC technician diagnosis dice, or maybe talking toilet paper. Try MindFlex, the mental acuity game, a Hogwarts student hat or a \"Don\'t Phase me bro\" t-shirt. There are so many interesting, truly geeky things, they\'ll wonder how you ever found it.

They\'ve got stuff for your cellphones like Bone Collection accessories, games and toys for the kids, travel gifts for the car, caffeinated soap or a Jumpin\' Banana Fire Bell Alarm for your home. Apparel awaits for your geek closet, like a Ziotek battery upsizer kit for your camping gear and of course AirZooka for the office. They also boast an unusual collection of geek tools anyone would be proud of as well as the best array of strange collectibles and unusual decor.

There are products that make perfect party favors too, like gem shaped ice trays, a curiosity at any party. Buckyballs are small, yet powerful rare earth magnets that you can build or shape. You\'ll love the Perplexus Buksi amazing puzzle ball, guaranteed to keep them busy and interested. You won\'t have to tell the kids to turn off the TV.

If you want to get more discounts, don\'t forget to sign up for a free catalog. We have prepared Xtreme Geek deals and exclusive money-saving <a href=\"http://www.x-tremegeek.com\">Xtreme Geek</a> coupons and coupon codes for you at our site, Savings.com. Save at least 14% to 85% on your favorite geeky things. It\'s a mad, mad world, Xtreme Geek has the accessories to hack it and make it more interesting and agreeable.','displayUrl'=>'http://www.x-tremegeek.com','imageUrl'=>'http://cdn.savings.com/logo/614102.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9536,'id'=>246531,'name'=>'Xavier Media','description'=>'Is your business ready for the internet? In 1996, Xavier Media started providing web sites for those who want online businesses. They provide and tips and tools for webmasters and bloggers who want improvements on their site.

If you are in the search for a domain, you can register at Xavier Media for just $1.99 per year, get free software with a new hosting plan, or gain free access to a hosting connection. This company values and supports your freedom of speech, and you can exercise it with your very own blog.
These guys have the hottest reseller plan going and you can get started with the basic reseller package for just $59.95 per year and just $159.99 for the pro package. Sell over 50 products at competitive rates. There are no deposits or revenue sharing, you set your own prices and you decide what your profits will be. 

You\'ll get a pre-built, ready-to-go website, and it will be live the moment you sign up. These guys handle all the billing and customer support for your account, you just set it up and collect the commission check. The pro package includes a $100 Microsoft ad center credit and a $100 Google AdWords credit. The basic package includes a $75 Google AdWords credit.

You\'ll get free 24/7 support for you and your customers and if you choose, a free quick start marketing guide and the Reseller Handbook, a free deluxe email account, and an online file folder. You\'ll get a free secure SSL certificate, express email marketing and an absolute 30 day money back guarantee.

It\'s so easy to use Xavier Media and you\'ll never need to look again for a place to park your website because these guys are fast, convenient and easy to use and you\'ll wonder how you ever got by without them. Get on-line faster and within your budget, without the confusion you get at other media hosting sites. 

Savings.com is proud to offer you these outstanding <a href=\"http://www.xaviermedia.biz\">Xavier Media</a> coupons and Xavier Media discounts and coupon codes, where you can host your website for just $3.95 per month or choose an economy plan for only $3.99 a month. Bookmark this page to get take advantage of these offers now, and sign up and be notified of future deals and you\'ll get on the web for less. Click a link to activate an Xavier Media coupon and you could be live in half an hour.','displayUrl'=>'http://www.xaviermedia.biz/','imageUrl'=>'http://cdn.savings.com/logo/1482684.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9537,'id'=>305564,'name'=>'Xbox','description'=>'','displayUrl'=>'http://promotrcker.info/x/0/1740/21447/','imageUrl'=>'http://cdn.savings.com/logo/2621339.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20229),
  array('id_index'=>9538,'id'=>425369,'name'=>'Xceon','description'=>'','displayUrl'=>'http://www.xceoninc.com/','imageUrl'=>'http://cdn.savings.com/logo/2911985.jpeg','allowPartnerDeals'=>'true','categoryIds'=>21162),
  array('id_index'=>9539,'id'=>251537,'name'=>'XEMEXUSA','description'=>'','displayUrl'=>'http://www.xemexusa.com','imageUrl'=>'http://cdn.savings.com/logo/1491532.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9540,'id'=>299482,'name'=>'Xenon Project','description'=>'','displayUrl'=>'http://www.xenonproject.com/','imageUrl'=>'http://cdn.savings.com/logo/2605984.png','allowPartnerDeals'=>'true','categoryIds'=>20897),
  array('id_index'=>9541,'id'=>233769,'name'=>'Xerox','description'=>'Xerox is the undisputed leader in copier technology. The company, founded in 1906, introduced the first photo-copier 1959, which revolutionized offices everywhere. Other innovations these guys spearheaded are the fax machine, laser printers, and color copy machines.

Are you longing to make a great impression with color copies and haven\'t been able to afford it? If the idea of having a free color copier makes your heart beat a little faster, then the membership promotion offered by this company is something you will want to take part in. You may well be wondering why such an industry leader is offering such a great deal, and the answer is pretty simple. All you need to do to get the free color copier is to buy your supplies from Xerox, which are competitively priced.

The program, designed for small businesses and non-profit organizations, who print at least 2,000 copies per month, spend $125 in printing costs, have at least one person on staff, and can buy their supplies with a credit card. Supplies will be purchased online, and shipping is free. These guys estimate savings over a three-year period at $1,257 for the 8560D and at $2978 for the 8560MFD.

The promotion features two copiers, the top-selling, award-winning 8560D and the 8560 MFD/D. They each offer a great array of up-to-date features, including a 600MHz processor (the fastest in its class), and printing up to 30 page per minute. The Solid Ink Technology produces 90% less waste than many laser printer inks, and is mess-free to load. The 8650 has standard capacity paper trays that will hold 625 sheets. 

Both machines will print on a variety of paper, including card stock, labels, post cards, and recycled paper. The 8560MFD/D has some nifty functions including the ability to scan documents from the copier to your computer (and even into separate folders), faxing and printing directly from your computer, and secure document features.

Participation is fairly straightforward. You will complete an on-line questionnaire to decide if your print usage is a good fit for the program, and then an on-line application asking straightforward questions about your organization. 

Savings.com has a <a href=\"http://www.freecolorprinters.com\">Xerox</a> coupon offering a free Xerox color printer with purchase of printing supplies online, as well as other Xerox discounts and coupon codes to help you save money on all your printing needs. Once approved, you will sign a three-year agreement, not a contract or lease. You will agree to make at least 2,000 copies per month and buy your supplies through Xerox. Go ahead, make the great impression you\'ve longed for with this wonderful offer.','displayUrl'=>'http://www.freecolorprinters.com','imageUrl'=>'http://cdn.savings.com/logo/620422.gif','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>9542,'id'=>239310,'name'=>'XGaming.com','description'=>'','displayUrl'=>'http://www.xgaming.com','imageUrl'=>'http://cdn.savings.com/logo/885324.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9543,'id'=>240932,'name'=>'Xilisoft','description'=>'','displayUrl'=>'http://www.xilivideo.com','imageUrl'=>'http://cdn.savings.com/logo/1018261.png','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>9544,'id'=>222015,'name'=>'XM Radio','description'=>'XM Satellite Radio was started in 1992 and has been publicly traded on NASDAQ since 1999.  XM Satellite Radio was started by radio?s first major  technological  advancement since the popularization of FM radio in the 1970?s.This change was the invention of a third broadcast medium that was transmitted by satellite.  This brought the radio satellite era to join AM and FM radio on the radio dial. XMRadio.com was one of only two with a license for this new national audio service.  XM Satellite Radio sought out and hired the best radio professionals in the business to bring the world into the new generation of radio broadcasting.  The current XM Satellite Radio lineup for 2008 includes more than 170 digital channels of across the United States which is the most music in satellite radio.  This number includes 69 commercial-free music channels and exclusive live concerts and original programming, plus premier sports, talk, comedy, children\'s and entertainment programming; and 21 channels of the most advanced traffic and weather information. 
XMRadio.com is not only leading the way in satellite radio content, but they were also the leader in satellite-delivered entertainment and data services for the automobile market.  XM Satellite Radio partnered with General Motors, Honda, Hyundai, Nissan, Porsche, Subaru, Suzuki and Toyota to make listening to XM Satellite Radio easier than ever before.  XM Satellite Radio is now available in over 140 2008 different vehicle models.
At XMRadio.com you will find great deals on quality radio receivers from such well-known manufacturers as Yamaha, Pioneer, Audiovox and Delphi..  The best way to save at XMRadio.com is to visit Savings.com first for coupons and coupon codes.  With XMRadio.com coupons or XM Satellite Radio coupon codes from Savings.com you can save even more.  Savings.com was created as a way to save our customers money with coupons and coupon codes for the hottest merchants online.  XMRadio.com coupons and XM Satellite Radio coupon codes are available at Savings.com to save you money.  So be a smart, informed shopper and visit Savings.com for XM Satellite Radio and XMRadio.com coupon codes.','displayUrl'=>'http://www.xmradio.com','imageUrl'=>'http://cdn.savings.com/logo/40203.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9545,'id'=>259210,'name'=>'Xoom.com','description'=>'','displayUrl'=>'http://www.xoom.com','imageUrl'=>'http://cdn.savings.com/logo/1530779.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9546,'id'=>247815,'name'=>'XOXO','description'=>'','displayUrl'=>'http://www.xoxo.com/','imageUrl'=>'http://cdn.savings.com/logo/1181368.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9547,'id'=>235510,'name'=>'Xperience Days','description'=>'Since 2004, Xperience Days has been providing customers with unique experiences nationwide. Specializing in the unusual and unique gift experience that provides unforgettable memories and enjoyment. You can choose from a wide range of gifts in several categories, from a hot air balloon ride to glass blowing lessons. If you want to give a more adventurous experience to get the blood pumping, give the gift of off-roading in the Las Vegas desert or being behind the wheel of a real NASCAR Stockcar Racecar in Detroit!

But what if you don\'t want to gift a thrilling adventure? Xperience Days has more than just hair-raising high-speed car races up our sleeve. They cater to those who would enjoy being pampered in the relaxing environment of a spa, take pleasure in a scenic train ride while nibbling on tasty fare, or cruise on a peaceful gondola ride. Experiences like this are a rare opportunity to give someone you care about a new unforgettable and life changing memory.

Xperience Days also offers Choice Certificates, which allow the gift recipient to choose from an assortment of experiences within certain color choice levels. You know you want to give that special person in your life this opportunity, but you don\'t know exactly what to get? No problem, these guys have great deals to choose from. Each certificate is also presented in a gift box with details about the whole booking process and calendar. Your loved ones will thank you for making their dreams and desires come true.

They have earned that distinction as one of the leading adventure and experience gift companies in the country. Their customers feel pleasure also, when they see the excitement on another person\'s face. Give someone a gift box to open. Whether it is an engagement gift, birthday gift or \"what a tough week at the office\" gift, these guys have terrific promos like instant email gifts and even coupon codes for savings. 

Save $20 off you gift, with our <a href=\"http://www.xperiencedays.com\">Xperience Days</a> discounts and Xperience Days coupons and coupon codes at Savings.com. If you don\'t see a coupon, let us know if you would like to be notified when discounts are available. It\'s time to surprise someone soon.','displayUrl'=>'http://www.xperiencedays.com','imageUrl'=>'http://cdn.savings.com/logo/1178066.png','allowPartnerDeals'=>'true','categoryIds'=>20228),
  array('id_index'=>9548,'id'=>277879,'name'=>'Xsitepro','description'=>'','displayUrl'=>'http://www.Xsitepro.com/','imageUrl'=>'http://cdn.savings.com/logo/1656892.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>9549,'id'=>239204,'name'=>'XSportsProtective','description'=>'','displayUrl'=>'http://www.XSportsProtective.com','imageUrl'=>'http://cdn.savings.com/logo/1178064.png','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>9550,'id'=>296541,'name'=>'Xterra Wetsuits','description'=>'','displayUrl'=>'http://www.xterrawetsuits.com','imageUrl'=>'http://cdn.savings.com/logo/2328007.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9551,'id'=>247425,'name'=>'xtreamgadgets','description'=>'','displayUrl'=>'http://www.xtreamgadgets.com','imageUrl'=>'http://cdn.savings.com/logo/1179230.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9552,'id'=>296459,'name'=>'Xtreme Diesel Performance','description'=>'','displayUrl'=>'http://www.xtremediesel.com','imageUrl'=>'http://cdn.savings.com/logo/2237513.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20886),
  array('id_index'=>9553,'id'=>239139,'name'=>'Xtreme Gameroom','description'=>'','displayUrl'=>'http://www.xtremegameroom.com','imageUrl'=>'http://cdn.savings.com/logo/832484.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9554,'id'=>206264,'name'=>'Xtremez','description'=>'Since 1995, Paintball Online has been dedicated to serving its customers in over 60 countries around the world. With a staff brim-full of a combined 80 years of paintball knowledge and experience, the customer support at <a href=\"http://www.paintball-online.com/\">Paintball Online</a> is ?needless to say- unmatched. This merchant guarantees the lowest prices on paintball gear anywhere on the web and stores its paintballs in a climate-controlled warehouse, ready to ship the same day you order them to ensure freshness and the ultimate paintball experience, whether you are playing indoors or outdoors. At <a href=\"http://www.savings.com\">Savings.com</a>, we send our team of deal hunters out onto the web to seek out the very best Paintball Online coupon codes and promo codes on the net. We make it our mission to post only valid Paintball Online discount codes so that our followers know they can always expect the best Paintball Online coupon codes and the most up-to-date information on Paintball Online sales and clearances when they come to our site before checking the latest Paintball Online promotions directly on the merchant\'s page. We make sure we are first in line to test out the latest Paintball Online promo codes so that our followers don\'t have to waste time while saving money. So remember to check out our most recent Paintball Online coupon code posts before heading to the merchant\'s site so you can make the most of the latest Paintball Online sales and promotions.','displayUrl'=>'http://www.xtremez.com','imageUrl'=>'http://cdn.savings.com/logo/27141.gif','allowPartnerDeals'=>'true','categoryIds'=>20226),
  array('id_index'=>9555,'id'=>250197,'name'=>'xUmp.com','description'=>'','displayUrl'=>'http://www.xump.com','imageUrl'=>'http://cdn.savings.com/logo/1482956.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9556,'id'=>285717,'name'=>'XZipit.com','description'=>'','displayUrl'=>'http://www.xzipit.com/','imageUrl'=>'http://cdn.savings.com/logo/1665851.png','allowPartnerDeals'=>'true','categoryIds'=>20877)
);
