<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>4201,'id'=>239242,'name'=>'Youneek','description'=>'Hewlett-Packard (HP), the world\'s largest technology company, is now the leader in personalized gifts and decor. Youneek.com creates unique invitations, greeting cards, calendars, and posters that center around you. They give you the tools to wow your friends and family with professionally personalized and printed stationery and apparel they\'ll want to keep for years to come.

Birthdays, weddings, anniversaries, these are the milestones that you will remember for a lifetime. Up to now, you\'ve had to use the design, layout, and content of someone else\'s greeting card. But with this site, everything is up to you. The give you the tools you need for every step of the creative process: from the images and text (content), to the complete layout. They offer such quality that matches a professional printing shop. All from the comfort of your own home.

Youneek wants to fulfill all your professional printing needs. They offer hundreds of customizable greeting card templates for any occasion. Our easily navigable website allows to browse the merchandise by Brand, Occasion, Interest, or Product type. They offer brands for every interest: everything from Bugs Bunny to Norman Rockwell to NBA Stars. This is your one-stop website for graduation, friends and family.

Prints are available in different sizes and paper types. For a beautiful and distinctive finish, you can choose from many different frames. All these gifts are available in two to three days or via in-store pickup. You can browse the entire collection from home and enjoy the savings we pass on to you. If you need to brand/advertise a special event, there\'s no better way then with customized T-Shirts. You decide the color and size, and get to enjoy the savings from the comfort of your home.

This is the fan\'s destination for all things customizable. If you need a personalized gift for a loved one, browse the incredible number of branded greeting cards, prints, and T-Shirts. And now, with Savings.com, you\'ll be able to save even more with special Youneek coupons. Youneek coupon codes and Youneek.com discounts and promotions include free shipping with the purchase of 6 greeting cards. <a href=\"http://www.youneek.com\">Youneek.com</a> coupons offer free in-store pick up at several major retail stores.','displayUrl'=>'http://www.youneek.com','imageUrl'=>'http://cdn.savings.com/logo/1070769.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9557,'id'=>246813,'name'=>'YaHobby.com','description'=>'','displayUrl'=>'http://www.yahobby.com','imageUrl'=>'http://cdn.savings.com/logo/1176515.png','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9558,'id'=>208059,'name'=>'Yahoo! Affiliate Program','description'=>'Make your website earn more with Yahoo! Affiliate Program. Yahoo! Affiliate Program premise is simple, to give you access to links, products, and marketing information to help you drum up business. Yahoo! Affiliate Program helps you drive traffic to Yahoo!, and earn various commissions. Yahoo! Affiliate Program can get you to earn commissions today with ease. Yahoo! Affiliate Marketing can give your sites earning potential a boost simply by driving your audience to Yahoo!. Yahoo! Affiliate Program is the premiere name in affiliate programs which can make your business shine. Take advantage of discounts on Yahoo! Affiliate Program services with Savings.com. Savings.com is the best source for Yahoo! Affiliate Program coupons, Yahoo! Affiliate Program online coupons, Yahoo! Affiliate Program coupon codes, Yahoo! Affiliate Program discount coupons, and Yahoo! Affiliate Program promotions. With Savings.com and Yahoo! Affiliate Program, you can make money while saving money.','displayUrl'=>'http://advertising.yahoo.com/affiliate_programs/','imageUrl'=>'http://cdn.savings.com/logo/27289.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9559,'id'=>249116,'name'=>'Yahoo Games','description'=>'So, you\'re bored of your same old annoying online game sites? Sites which pretend to have a ton of games but most of them are boring? Or ones that actually do have good games, but only a few of them? Well, look no further, Yahoo Games is here.

These guys offer you an incredible amount of games. Seriously, the selection of the games is crazy. Top games include Bejeweled 2, Super Collapse! 3, Epic Adventures: La Jangada and Super Granny 5. You have multiple genres to choose from, whether you prefer good old classic board games, or cool new action games that test your skill. If you like puzzles or word games, you won\'t be disappointed in the selection. Your kids might think of these as games, but you know that they are really valuable educational experiences. They can improve their vocabulary and spelling. Are you lonely? Come test your skills against another player, there are always multiplayer games, where you can face off against your friends.

Unlike other gaming sites, Yahoo Games actually hosts tournaments in which you can participate and win awesome prizes. This is where these guys really shine. Now, you can finally put your gaming skills to good use by competing and winning yourself some neat prizes. Not only that, but winning gets you access to even higher leagues, offering even better prizes.

But that, just the tip of the iceberg! There also amazing games, made by famous online game developers such as PopCap, that provide a ton of fun as well as hours of gameplay value. Free trials of these games are available. Becoming a member, actually gives you access to discounts on these games.

Last, but not least, Yahoo Games gives you daily updates and news on your favorite games, as well as articles and latest videos. So, not only do you play games and have fun, but you\'re also up to date with the latest gaming news! This is the site you want to check out if you\'re a gamer, either casual or hardcore, because this is the site for you.

We at Savings.com, have several <a href=\"http://www.games.yahoo.com\">Yahoo Games</a> coupons and Yahoo Games discount codes. Free trial versions of games and 65% of each game with a Platinum Membership are some of the offers waiting for you. You better start clearing some free time for your game playing today!','displayUrl'=>'http://games.yahoo.com/','imageUrl'=>'http://cdn.savings.com/logo/1203426.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20229),
  array('id_index'=>9560,'id'=>6155,'name'=>'Yahoo Personals','description'=>'Find that special someone with Yahoo! Personals. Savings.com has made your search for Mr/Miss right even better by offering you amazing discounts. Do a Savings.com search for Yahoo! Personals coupons, Yahoo! Personals coupon codes, and Yahoo! Personals online promotions and you\'ll be calling that special someone in no time. Yahoo! Personals offers the best in services that let you take the opportunity to find the right person for you. Meet your destiny. Use Savings.com to search for Yahoo! Personals coupons, Yahoo! Personals online specials, and Yahoo! Personals special deals, and you\'ll be waking up next to that special someone for the rest of your life. You can\'t afford not to. You can finally afford to with Savings.com and Yahoo! Personals. Take the first step in making your dreams of love and companionship by using Yahoo! Personals and Savings.com.  ','displayUrl'=>'http://personals.yahoo.com/us','imageUrl'=>'http://cdn.savings.com/logo/1661818.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9561,'id'=>249117,'name'=>'Yahoo Web Hosting','description'=>'Are you looking to increase revenue and searching for something to drive customers to your small business? At some point you will be ready to take the next steps to drive traffic to your door by building a website. Yahoo Web Hosting is a great place to start when you need to build a professional looking website to help increase revenue and grow your business. These guys have no set up fees and a 30-day satisfaction guarantee so you can\'t go wrong with their competitive rates, and to make things even better, top it off with a savings of 25% over 3 months.

Yahoo Web Hosting offers 24-7 phone, email, and online support to help you with the state of the art design tools that will give your site a professional look. The design tools are easy to use and requires no experience to set up a website. They also offer an Audio/Video media player that supports JPG, GIF, and PNG to enhance the look and feel of your website.

It is always important to track the number of visitors and traffic visiting your website. These guys offer reporting features that check your progress and your ranking in search engine results. This important tool helps you to see which key words customers use to find your site and which websites are driving visitors to your business.

Of course, every business needs a domain name and purchasing your domain through Yahoo Web Hosting provides reliable and secure hosting services. This service also includes unlimited disk space, unlimited data transfer, unlimited email storage with professional email services, password protection, PayPal, and of course their unparalleled support services. All this is just a part of the terrific value offered by this service. You will also get online getting started guides and tutorials along with a comprehensive online help center to answer any question you may have when creating your website.

Yahoo Web Hosting marketing and promotions tools offer automatic site submission to Yahoo! Google, Bing and Ask. Automatic site submission is an added benefit that will index all content available on your website and offer the best possible match when users looking for your product online. These guys also offer $50 in Google AdWords credit and a $100 Yahoo! Marketing credit when you subscribe to their services. Take advantage of the Savings.com coupons for free setup on all hosting plans or unlimited website storage space, unlimited data transfer, and a Free Domain Name with all purchases.

So do you still want to create a website for your small business, but don\'t feel you are creative enough or you just can\'t find the time to create one yourself? Yahoo Web Hosting will create a customized website for you, based off your preferences and give you a professional look and feel for your business.

So what are you waiting for, head over to Savings.com to sign up today. Create your online business and increase your revenue by using <a href=\"http://www.smallbusiness.yahoo.com\">Yahoo Web Hosting</a> discounts and Yahoo Web Hosting coupons to grow your business with a visually appealing website, that will bring customers back time after time.','displayUrl'=>'http://smallbusiness.yahoo.com/webhosting/','imageUrl'=>'http://cdn.savings.com/logo/1661822.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9562,'id'=>236669,'name'=>'Yankee Candle','description'=>'Yankee Candle boasts over 150 fragrances which truly lives up to their \"passion for fragrance\" slogan.  The most recognized and best-selling candle brand in America, Yankee Candle is not just about candles but carries home fragrance products, car fresheners and candle accessories as well.  Yankee Candle premium scented candles are made from fragrance extracts and real essential oils.  From luscious florals like Hydrangea and Sweet Violet to fruit-filled scents such as Black Raspberry and Honeydew Melon, Yankee Candle has a scent to soothe you.  Apple Cider and Oatmeal Cookie, Autumn Leaves, Willow Breeze, Mistletoe and Christmas Eve: Yankee Candle\'s evocative fragrances set the mood for any occasion.  Before you light the wick of Yankee Candle, check out Savings.com for Yankee Candle coupons.','displayUrl'=>'http://www.yankeecandle.com','imageUrl'=>'http://cdn.savings.com/logo/1613865.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9563,'id'=>240475,'name'=>'Yassy\'s Gourmet Dog Kitchen','description'=>'','displayUrl'=>'http://yassysgdk.com/','imageUrl'=>'http://cdn.savings.com/logo/1178070.png','allowPartnerDeals'=>'true','categoryIds'=>20221),
  array('id_index'=>9564,'id'=>234873,'name'=>'Yatra','description'=>'','displayUrl'=>'http://usatoindia.yatra.com','imageUrl'=>'http://cdn.savings.com/logo/714749.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20228),
  array('id_index'=>9565,'id'=>311134,'name'=>'YaySave','description'=>'$model.description','displayUrl'=>'https://www.yaysave.com','imageUrl'=>'http://cdn.savings.com/logo/2824717.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9566,'id'=>296156,'name'=>'Yazmo.com','description'=>'','displayUrl'=>'http://www.yazmo.com','imageUrl'=>'http://cdn.savings.com/logo/1966034.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9567,'id'=>280677,'name'=>'Yellow Bear, LLC.','description'=>'','displayUrl'=>'http://myyellowbear.com','imageUrl'=>'http://cdn.savings.com/logo/1659298.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9568,'id'=>274427,'name'=>'Yelp Biz Owner','description'=>'','displayUrl'=>'http://www.yelp.com/business','imageUrl'=>'http://cdn.savings.com/logo/1661921.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>9569,'id'=>278138,'name'=>'Yes To Carrots','description'=>'','displayUrl'=>'http://www.yestocarrots.com/','imageUrl'=>'http://cdn.savings.com/logo/1656894.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>9570,'id'=>216647,'name'=>'YesAsia','description'=>'','displayUrl'=>'http://www.yesasia.com','imageUrl'=>'http://cdn.savings.com/logo/619974.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20231),
  array('id_index'=>9571,'id'=>216645,'name'=>'YesStyle','description'=>'','displayUrl'=>'http://www.yesstyle.com','imageUrl'=>'http://cdn.savings.com/logo/622847.png','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>9572,'id'=>229973,'name'=>'YLighting','description'=>'YLighting is known for its contemporary and energy-efficient lighting solutions. They offer a variety of lamps, sconces, and chandeliers for any room in the house, as well as many outdoor furnishings. If you are looking for a modern way to spruce up your room there is no better place to look than this phenomenal store. Their fast and friendly customer service staff are willing to answer any questions and help ease any concerns you may have about their products.

Brighten your living room with some new track lighting, or fix up that dark hallway with a set of Claire wall sconces. You could create an elegant ambiance with a unique floor or table lamp as your new centerpiece. It is easy to liven up that dull office space with a fun and energy-efficient desk lamp. Even if you are looking on a budget, this site offers discounts and specials on many of their products. For whatever needs you have, this website has the best solution.

These guys have a large selection of closeout and overstocked items, which could be the perfect accent to your room. YLighting coupons and discounts are constantly updated to make sure that you get the biggest bang for your buck. The site offers both a low price and price match guarantee, as well as free shipping on all items. If you can find a better to-your-door price on any of their products they will match the competitor\'s price. They also offer a 100% refund on any unused never installed merchandise.

You can find many low price and discounted products at this website, plus you can find coupon codes for many of their products on Savings.com. Be sure to search our extensive coupon database and find great <a href=\"http://www.ylighting.com\">Ylighting</a> coupons and Ylighting discounts for deals such as 40% off select lighting and free shipping on orders of $50. 

These guys offer many solutions to any of your lighting needs and their helpful staff are willing to answer any questions you might have. Whether you are looking for a flashy floor lamp or a grand chandelier, this store offers a variety of name brands, as well as the best price for your lighting solution.','displayUrl'=>'http://ylighting.com','imageUrl'=>'http://cdn.savings.com/logo/1178068.png','allowPartnerDeals'=>'true','categoryIds'=>20216),
  array('id_index'=>9573,'id'=>295854,'name'=>'YLiving','description'=>'','displayUrl'=>'http://www.yliving.com','imageUrl'=>'http://cdn.savings.com/logo/1800837.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9574,'id'=>294753,'name'=>'YMCA of the Rockies','description'=>'','displayUrl'=>'http://www.ymcarockies.org','imageUrl'=>'http://cdn.savings.com/logo/1733570.gif','allowPartnerDeals'=>'true','categoryIds'=>20901),
  array('id_index'=>9575,'id'=>278286,'name'=>'Yobitech','description'=>'','displayUrl'=>'http://www.yobitech.com','imageUrl'=>'http://cdn.savings.com/logo/1656353.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9576,'id'=>299536,'name'=>'Yoga Journal Florida Conference','description'=>'','displayUrl'=>'http://www.yjevents.com/florida/free.php','imageUrl'=>'http://cdn.savings.com/logo/2606198.gif','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>9577,'id'=>253775,'name'=>'Yoga-Clothing.com','description'=>'Down dog, up dog, mountain and tree pose--optimize your yoga practice with gear that moves with you courtesy of Yoga Clothing com.  Let\'s face it--you do yoga to increase your strength, endurance and suppleness.  Should your yoga clothes be strong, well-made and flexible?  Yoga-Clothing.com carries high-quality yoga gear by top brands like Fila, Hard Tail, prAna, So Low and Splendid.  In addition to camis and tanks, cropped and full-length yoga pants, hoodies and jacket, Yoga Clothing com also carries mats, towels, bags and other accessories to fully equip you for your yoga classes--or your at home practice.
<br><br>
Looking to save money as you work the mind-body connection of yoga?  Try a Yoga Clothing com coupon code from Savings.com.  At Savings.com, we scour the web for the best deals and discounts--like our Yoga Clothing com coupons.  So before you finalize your order at <a href=\"http://www.yoga-clothing.com\">Yoga-Clothing.com</a>, stop by Savings.com for a Yoga Clothing com promotion code.','displayUrl'=>'http://www.Yoga-Clothing.com/','imageUrl'=>'http://cdn.savings.com/logo/1552514.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9578,'id'=>246516,'name'=>'YogaAccessories.com','description'=>'When YogaAccessories.com set up their company and website they recruited staff who had a real enthusiasm for yoga so the company would not be just another provider of yoga-related equipment. They wanted to be a provider of products from around the globe that would make sure you got the best support in finding holistic and spiritual wellbeing.

Over 1 million people have clicked on YogaAccessories.com to find all the equipment that is needed to help achieve the ultimate yoga experience. Whether it is mats or straps, blankets or bolsters, you can be sure that the staff at YogaAccessories.com has done their best to carry products that offer great value for money while maintaining excellent quality.

To get hold of these great deals, go to their website and make use of a YogaAccessories.com coupon or here at Savings.com you will find the <a href=\"http://www.yogaaccessories.com\">YogaAccessories.com coupon code</a> that also guarantees you a fantastic saving.','displayUrl'=>'http://www.yogaaccessories.com/','imageUrl'=>'http://cdn.savings.com/logo/1614230.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9579,'id'=>262305,'name'=>'YogaDirect.com','description'=>'','displayUrl'=>'http://www.yogadirect.com/','imageUrl'=>'http://cdn.savings.com/logo/1560621.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9580,'id'=>316667,'name'=>'YogiDirect.com','description'=>'','displayUrl'=>'http://www.yogidirect.com','imageUrl'=>'http://cdn.savings.com/logo/2814912.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9581,'id'=>246175,'name'=>'Yola','description'=>'You are an expert at your business, but who is the expert at building websites for your business? The name of that expert is Yola. Featured in The Wall Street Journal, TechCrunch, Entrepreneur, CNet, and ABC NewsFree, this website building and hosting service helps the small businesses with the developement of their online business. This winner of many awards, helps you create stunning websites that are simple to manage and maintain.

Instantly design, create and host your website with tools that allow you to edit the background, designs, include pictures, photos & videos, and Google Maps. Collect data with online forms that you designate. Incorporate PayPal, Flickr, YouTube, Gentoo, Skype, Twitter, Facebook and Google Adsense to increase your efficiency. Create the website you envision.

There are 3 several services available. First, with Yola\'s free service, you can use the website builder with unlimited bandwidth, secure, reliable, and banner free hosting, website design templates, customer support along with 5 sites having 1 GB storage area and 15 MB file size.
The Yola Silver software, at $49.95 per year, offers you a custom domain name, registration, premium styling, giving your site a distinctive look for a major lead over the competitors. You may also choose a unique domain name. This package provides you with 25 sites having 5GB storage and 100 MB file size.

The company’s partnership with HP Logoworks team of professional website designers are eager to develop your website. With Yola Premier, at $349.95 per year, the designers will create and design the website to suit your business. HP Logoworks designers can also design a website that you can control and update, for a one time fee.

We at Savings.com invite you to incorporate these amazing and affordable services into your small business. So check out our website for the latest <a hef=\"http://www.yola.com\">Yola</a> coupons and discounts and snatch up coupons for Free Website Building and Hosting and a whole number of other awesome services. Their passionate team of engineers, designers, and entrepreneurs, are dedicated to helping your small business flourish. These guys will help you meet your needs, while you spend your valuable time on actually running your business.','displayUrl'=>'http://www.yola.com','imageUrl'=>'http://cdn.savings.com/logo/1146818.png','allowPartnerDeals'=>'false','categoryIds'=>20831),
  array('id_index'=>9582,'id'=>280584,'name'=>'Yonofoco','description'=>'','displayUrl'=>'http://www.yonofoco.com','imageUrl'=>'http://cdn.savings.com/logo/1659113.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9583,'id'=>5577,'name'=>'YOOX','description'=>'YOOX, the world\'s premiere on online designer clothing boutique, is visited by around 4 million people each and every month. People come to this innovational shopping website to experiment with their styles with ideas from designers like Versace, Stella McCartney, Dolce & Gabbana, Diesel, and many, many others. 

These guys have direct relationships with designers and dealers, and this close relationship has allowed them to become the hugely successful virtual boutique that it is today by letting millions of shoppers around the world browse through high end designer luxuries at just a fraction of the cost – stocking up on all their favorites like boots, sunglasses, coats, dresses, handbags and so much more without having to worry about breaking the bank. Why, you ask? Because the site’s close relationship with all your favorite designers has enabled them to cut out those pesky middlemen like department stores and warehouses and to sell their goods directly to you through this awesome website.

This store offers designer fashion clothing, shoes, and accessories for men, women, and kids. With designer clothing, designer shoes, and accessories from famous artists like Roberto Cavalli, Alexander McQueen, Armani, Balenciaga, Marc Jacobs, Prada, and so many more, YOOX presents with a plethora of stylistic options for your wardrobe. From Baldinini men\'s shoes and John Galliano denim for women to Givenchy handbags and Diesel clothes for babies, these guys have everything you need to make sure you and your family are looking your very best. Whether you\'re purchasing a new Coach bag for yourself or a new Christian Dior brooch for your guy, this store is sure to have the perfect item in stock and at a price you can more than afford.

Before placing your order, remember to take a minute to check out our site right here at Savings.com for all the latest and greatest in valid <a href=\"http://www.yoox.com\">Yoox</a> codes and Yoox coupons and snatch up a Yoox coupon code that’s sure to save you a bundle on the designer fashions and accessories you’ve just got to have. Gone are the days of fretting over price tags. It’s time to indulge in the luxuries you deserve.','displayUrl'=>'http://www.yoox.com/','imageUrl'=>'http://cdn.savings.com/logo/715201.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9584,'id'=>252349,'name'=>'Youda Games','description'=>'','displayUrl'=>'http://www.youdagames.com/','imageUrl'=>'http://cdn.savings.com/logo/1495276.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9585,'id'=>288643,'name'=>'youdagames.com','description'=>'','displayUrl'=>'https://www.plimus.com/','imageUrl'=>'http://cdn.savings.com/logo/1670848.png','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>9586,'id'=>295652,'name'=>'You Floral','description'=>'','displayUrl'=>'http://www.youfloral.com/','imageUrl'=>'http://cdn.savings.com/logo/1739358.png','allowPartnerDeals'=>'true','categoryIds'=>20853),
  array('id_index'=>9587,'id'=>294055,'name'=>'Young Explorers','description'=>'Creative Educational Products.','displayUrl'=>'http://www.youngexplorers.com/','imageUrl'=>'http://cdn.savings.com/logo/1726474.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9588,'id'=>242859,'name'=>'Younits','description'=>'','displayUrl'=>'http://www.Younits.com','imageUrl'=>'http://cdn.savings.com/logo/1149770.png','allowPartnerDeals'=>'true','categoryIds'=>20873),
  array('id_index'=>9589,'id'=>233213,'name'=>'Your Baby Can Read','description'=>'','displayUrl'=>'http://www.yourbabycanread.com','imageUrl'=>'http://cdn.savings.com/logo/619640.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20237),
  array('id_index'=>9590,'id'=>244028,'name'=>'Your Brand Shop','description'=>'','displayUrl'=>'http://www.yourbrandshop.com','imageUrl'=>'http://cdn.savings.com/logo/1110866.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9591,'id'=>235593,'name'=>'Your Electronic Warehouse','description'=>'Your Electronic Warehouse is a Top 500 Internet Retailer that remains in the top by satisfying customers again and again with affordable pricing on a wide range of electronics and gadgetry from top and trusted brands, as well as free standard shipping on all orders of $75 or more. Customers can browse the Deal of the Month page, the Specials page or the <a href=\"http://www.4electronicwarehouse.com\"Your Electronic Warehouse Outlet</a> to save anywhere from 10 to 60% off the original prices of a massive selection of iPod docks, speakers, satellite dishes and so much more ? all at competitive prices that are more than affordable and always from brand names customers know and trust. Here at <a href=\"http://www.savings.com\">Savings.com</a>, we know that taking the time to seek out further Your Electronic Warehouse discounts online is not always so fruitful. With that in mind, we send our group of Deal Hunters out onto the web as often as possible to seek out and post to our site all the valid Your Electronic Warehouse coupon codes and promo codes they can find for our followers to use in conjunction with the latest Your Electronic Warehouse sales and promotions we also post to our site. So check us out for some of the latest Your Electronic Warehouse coupon codes and promo codes on the net and start saving.','displayUrl'=>'http://www.4electronicwarehouse.com','imageUrl'=>'http://cdn.savings.com/logo/629798.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9592,'id'=>308449,'name'=>'Your Face Booth','description'=>'','displayUrl'=>'http://www.yourfacebooth.com/','imageUrl'=>'http://cdn.savings.com/logo/2627496.png','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>9593,'id'=>233280,'name'=>'Your Guide To Green','description'=>'','displayUrl'=>'http://www.YourGuideToGreen.com','imageUrl'=>'http://cdn.savings.com/logo/1178072.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9594,'id'=>281912,'name'=>'Your Lowest Price','description'=>'','displayUrl'=>'http://www.yourlowestprice.com','imageUrl'=>'http://cdn.savings.com/logo/1660586.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9595,'id'=>244452,'name'=>'Your Mobile Spot','description'=>'','displayUrl'=>'http://yourmobilespot.com','imageUrl'=>'http://cdn.savings.com/logo/1116635.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9596,'id'=>289341,'name'=>'Your Online Superstore','description'=>'','displayUrl'=>'http://www.youronlinesuperstore.com','imageUrl'=>'http://cdn.savings.com/logo/1688520.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9597,'id'=>263664,'name'=>'Your Planet Mall','description'=>'','displayUrl'=>'http://www.yourplanetmall.org','imageUrl'=>'http://cdn.savings.com/logo/1606063.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9598,'id'=>310583,'name'=>'Your Sexy Jeans','description'=>'','displayUrl'=>'http://www.yoursexyjeans.com','imageUrl'=>'http://cdn.savings.com/logo/2646123.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20822),
  array('id_index'=>9599,'id'=>239134,'name'=>'Your Warehouse Direct','description'=>'','displayUrl'=>'http://www.yourwarehousedirect.com','imageUrl'=>'http://cdn.savings.com/logo/1178076.png','allowPartnerDeals'=>'true','categoryIds'=>20216),
  array('id_index'=>9600,'id'=>310419,'name'=>'Your Best Deals','description'=>'','displayUrl'=>'http://yourbestdeals.com','imageUrl'=>'http://cdn.savings.com/logo/2681703.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9601,'id'=>240151,'name'=>'Your Blinds','description'=>'Do you need darker shades to block the morning sun from waking you? Do you have a home theater room that really needs to be darker? Your Blinds is a place where you can discover deals while shopping for blinds of all colors, shapes and sizes. Their perfect customer satisfaction score at BBB online could almost speak for itself. Headquartered in Austin, TX, they want your experience to be fast, easy and informative. They are committed to providing you with the best designs, in order to accurately match your lifestyle.

You\'ve probably heard that a house is not a home, untill the proper blinds are installed. Visit their \"How to Install\" and \"How to measure\" menus and videos, so that you know exactly how to prepare for the project. Your Blinds gives you more than blinds that flow well with a room, they offer top customer support.

Dubbed \'best of the web\' by About.com, Your Blinds is a great solution, making shopping for honeycomb blinds, cellular shades, window coverings, custom shades, roller, faux wood blinds, mini blinds, sheer horizontal shades as well as brands like Levolor and Bali easy through a new method of comprehensive pricing with a comparison section, so you\'re sure to get the best prices.
There are also many deals on window shades and blinds. It\'s actually common to see a 25%, or 35% off price tag. These blinds usually come with a warranty. Time varies on the particular blind or shade warranties, yet this testifies that they want you to be happy their products.

If those deals aren\'t sweet enough for you, head over to Savings.com and get free shipping and 10%-25% off on sales. YourBlinds.com takes pride in supplying you with top-notch products for use in most window projects around the house just like we take pride in delivering Your Blinds coupons and <a href=\"http://www.yourblinds.com\">Your Blinds</a> discount codes and promotions. 

But the best part about shopping for shades and blinds is that they offer the most comprehensive advice when it comes to matching your lifestyle, so you\'re sure to make the best decisions on window shades. For all window covering solutions, you will be covered.','displayUrl'=>'http://www.yourblinds.com/','imageUrl'=>'http://cdn.savings.com/logo/1013792.png','allowPartnerDeals'=>'true','categoryIds'=>20216),
  array('id_index'=>9602,'id'=>243126,'name'=>'YourGameWorldo.com','description'=>'','displayUrl'=>'http://www.yourgameworldo.com','imageUrl'=>'http://cdn.savings.com/logo/1093635.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9603,'id'=>236978,'name'=>'YourInkCenter.com','description'=>'','displayUrl'=>'http://www.yourinkcenter.com','imageUrl'=>'http://cdn.savings.com/logo/728096.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9604,'id'=>295725,'name'=>'YourNaturalOptions.com','description'=>'','displayUrl'=>'http://www.yournaturaloptions.com','imageUrl'=>'http://cdn.savings.com/logo/1771641.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9605,'id'=>455006,'name'=>'YourRxDiscounts','description'=>'','displayUrl'=>'http://www.yourrxdiscounts.com/','imageUrl'=>'http://cdn.savings.com/logo/2923241.png','allowPartnerDeals'=>'true','categoryIds'=>29176),
  array('id_index'=>9606,'id'=>273375,'name'=>'Youth Corridor','description'=>'','displayUrl'=>'http://www.YouthCorridor.com/','imageUrl'=>'http://cdn.savings.com/logo/1634949.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20733),
  array('id_index'=>9607,'id'=>240562,'name'=>'Youthful Essence','description'=>'','displayUrl'=>'http://www.youthfulessence.com/','imageUrl'=>'http://cdn.savings.com/logo/1019044.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9608,'id'=>250943,'name'=>'Yowza Fitness','description'=>'Yowza Fitness is dedicated to providing customers with discounts up to 60% off retail prices for trusted, brand name fitness equipment and accessories like treadmills, elliptical machines and more.<br /><br />

These guys offer both folding and non-folding treadmills, fixed motion elliptical machines and variable motion elliptical machines, core training torso machines and so much more – all carefully designed with both the environment and the economy in mind so customers can save some green while going green with thoughtfully produced fitness equipment and accessories that use recycled plastics and paints and cut out the middle man to bring you the fitness products you want direct from the factory.<br /><br />

All the fitness equipment and accessories sold at Yowza Fitness are backed by a Lifetime Limited Warranty and are shipped out the day after your order is placed so you can get fit as soon as possible on a rigorously tested piece of machinery that’s sure to get you the results you want.<br /><br />

With discounts up to 60% off select items throughout the site, free shipping on select treadmills and elliptical machines and extra discounts on top of everyday savings thanks to awesome Yowza Fitness coupon codes and Yowza Fitness promos, you’re sure to find the workout equipment you want at prices you can more than afford.<br /><br />

Want to save even more money on your workout equipment and gear? Be sure to check out our site right here at Savings.com for some of the latest and greatest in <a href=\"http://www.yowzafitness.com\">Yowza Fitness</a> coupon codes and Yowza Fitness discounts to snatch up the equipment you want at affordable prices that are sure to make you smile. <br /><br />','displayUrl'=>'http://www.yowzafitness.com/','imageUrl'=>'http://cdn.savings.com/logo/1489837.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9609,'id'=>240056,'name'=>'YOYO Lip Gloss, Inc.','description'=>'','displayUrl'=>'http://www.yoyolipgloss.com/','imageUrl'=>'http://cdn.savings.com/logo/1006002.png','allowPartnerDeals'=>'true','categoryIds'=>20733),
  array('id_index'=>9610,'id'=>278288,'name'=>'YoYoInk','description'=>'','displayUrl'=>'http://www.yoyoink.com','imageUrl'=>'http://cdn.savings.com/logo/1656355.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9611,'id'=>290340,'name'=>'Yukon Pikes','description'=>'','displayUrl'=>'http://www.yukonpikes.com','imageUrl'=>'http://cdn.savings.com/logo/1691174.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9612,'id'=>296103,'name'=>'Yums Shop','description'=>'','displayUrl'=>'http://www.yumsshop.com','imageUrl'=>'http://cdn.savings.com/logo/2610509.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9613,'id'=>5553,'name'=>'Yves Rocher','description'=>'A trusted name for 50 years, Yves Rocher continues to produce top quality beauty products from botanical sources that do not harm the environment. Yves Rocher is still based in Bretagne, France where they harvest their own organically grown plants for use in their products.

Whether you\'re a trusted customer or just discovering Yves Rocher, you\'ll find amazing products that will surprise you from their line of skin care serums, makeup, hair care, body washes, or fragrances. 

The best-selling Elixir 7.9 Youth Intensifier will give you twice the effectiveness of the usual anti-aging product with just one drop. The Lilac Eau de Toilette will bathe you in the soft scent of lilacs any time of the year. Heading out on the town? You\'ll find the Plumping Sheer Gloss, an indispensable necessity in its convenient travel size.

With <a href=\"http://www.yvesrocherusa.com\">coupons for Yves Rocher</a> you can\'t go wrong. Check Savings.com regularly for the latest Yves Rocher coupon code.','displayUrl'=>'http://www.yvesrocherusa.com','imageUrl'=>'http://cdn.savings.com/logo/2622185.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9614,'id'=>319558,'name'=>'Yves Saint Laurent Beauty, L\'Oreal USA, Inc.','description'=>'$model.description','displayUrl'=>'http://www.yslbeautyus.com/','imageUrl'=>'http://cdn.savings.com/logo/2824437.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array')
);
