<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @author Geoffray Warnants
 * @version 0.2b
 */

//
// Database "savings_test"
//

// savings_test.wp_savings_merchants
$wp_savings_merchants = array(
  array('id_index'=>4412,'id'=>237190,'name'=>'ZAGG','description'=>'ZAGG began with the invention of the invisibleSHIELD in 2005--originally developed to protect a wristwatch.  The invisibleSHIELD later was used for the Apple iPod nano and thus ZAGG was founded in 2007.  The unusual name can be attributed to the company\'s two slogans:  \"Zealous about Great Gadgets\" (aka \"ZAGG\") or \"When others zig, we ZAGG!\"  In any case, the ZAGG invisibleSHIELD now boasts over 3,000 versions to protect devices like the iPod, iPhone, Palm Pre, Blackberry and more.  In addition, ZAGG has expanded its product line to include audio components and a variety of accessories.  
<br><br>
The invisibleSHIELD is ZAGG\'s signature product and ZAGG stands behind it with a lifetime replacement guarantee.  Protect your precious gadgets with ZAGG invisibleSHIELD--it\'s a good investment!  And you can save on your ZAGG purchase with a ZAGG discount code from Savings.com.  By using a ZAGG coupon or invisible SHIELD discount code for ZAGG, you can keep your beloved gadgets protected--and keep some extra cash in your pocket as well!  So before you finalize your order at <a href=\"http://www.zagg.com\">Zagg.com</a>, make sure you check Savings.com for a ZAGG discount code or ZAGG coupon.','displayUrl'=>'http://www.ZAGG.com','imageUrl'=>'http://cdn.savings.com/logo/1018258.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>5505,'id'=>281764,'name'=>'Zune Pass','description'=>'','displayUrl'=>'http://www.zune.net/en-us/products/zunepass/default.htm','imageUrl'=>'http://cdn.savings.com/logo/1660463.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9615,'id'=>293314,'name'=>'Z Gallerie','description'=>'','displayUrl'=>'http://www.zgallerie.com','imageUrl'=>'http://cdn.savings.com/logo/1718882.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20877),
  array('id_index'=>9616,'id'=>298276,'name'=>'Z Daisy','description'=>'','displayUrl'=>'http://zdaisy.com/','imageUrl'=>'http://cdn.savings.com/logo/2602083.png','allowPartnerDeals'=>'true','categoryIds'=>20761),
  array('id_index'=>9617,'id'=>323063,'name'=>'Zagall','description'=>'','displayUrl'=>'http://www.zagall.com','imageUrl'=>'http://cdn.savings.com/logo/2827077.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9618,'id'=>220462,'name'=>'Zagat','description'=>'Eating out at restaurants can be an expensive luxury, but you increase your likelihood of a good dining experience thanks to Zagat.  Zagat Survey gathers together opinions of diners just like you to create reviews and Zagat ratings.  The aggregated responses of consumers is what makes Zagat guides so beneficial to users--you\'re not dealing with the opinion of some snooty restaurant critic, but real people who have shared their experiences through Zagat survey.  And restaurants are just one area covered by Zagat guides:  you can read reviews for hotels, nightclubs and other attractions as well.  Zagat compiles over 350,000 survey responses for over 40,000 establishments worldwide.  Founded over thirty years ago by Tim and Nina Zagat, the guides have become a most trusted and influential source of information for discerning diners everywhere.
<br><br>
Zagat ratings, reviews and guides help savvy consumers make the most of dining dollars.  And you can make an even smarter shopping decision with a Zagat promo code from Savings.com.  Savings.com has the best deals and discounts on the web like our Zagat promo codes and Zagat coupons.  So before you finalize your purchase at <a href=\"http://www.zagat.com\">Zagat.com</a>, go to Savings.com for a great Zagat promo code or coupon for Zagat.  Savings.com and Zagat coupons--a smarter way to spend money.','displayUrl'=>'http://www.zagat.com','imageUrl'=>'http://cdn.savings.com/logo/1187981.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9619,'id'=>251363,'name'=>'Zagat Wine','description'=>'Choosing the right wine for your occasion should not be a daunting, worrisome task. Zagat Wine is set to make such occurrences uplifting and didactic. These guys are an online merchant aimed at bringing their customers the best wine available from around the world at a reasonable price. This is made possible by years and years of knowledge built up through wine tasting groups where wines were sipped, notes were scribbled and lively, focused debate took place. 

Renowned wine merchant Tony Laithwaite and his team have spent the last forty years devoting their lives to traveling and living in the vineyards and amongst the barrels to bring Zagat Wine\'s customers the best recommendations. These high quality suggestions should come as no surprise as Tony\'s team has been named Decanter Magazine\'s Independent Wine Merchant of the Year and drew U.K.\'s independent consumer watchdog, Which?, to label Tony\'s company as \"just what customers are looking for in a wine merchant\".

These guys offer a wide range of wines from an equally wide range of locales. Wines can be found from all corners of the global from Argentina, Australia, Chile, France, Germany, Italy, New Zealand, South Africa, Spain, to the United States. Assortments of wine from Cabernet Sauvignon, Merlot, Syrah, Pinot Noir, Sangiovese, Tempranillo, Zinfandel, Chardonnay, Pinot Grigio, and Sauvignon Blanc to name a few, can be share with friends and family.

Not only does Zagat Wine offer an enormous collection of wine, consumers will find a generous amount of free helpful hints on picking the right wine, correctly pairing wine, ideal storage, and common vernacular. Some deals we have offered are free wine decanters and discounts on Mystery Mixes.

We invite you to visit Savings.com for the best <a href=\"http://www.zagatwine.com\">Zagat Wine</a> discounts and coupons. You could save 40% off a 1 year subscription. New Zagat Wine Club members are offered a twelve bottle case for an astonishing $69.99, a savings of $100. Also, every three months a special price of $139.99 is offered for a twelve bottle case, a savings of 20%. Accompanied with these cases are full tasting notes to exploit the most out of each bottle. Make everyday a special occasion with the help from these great wine experts.','displayUrl'=>'https://www.zagatwine.com/','imageUrl'=>'http://cdn.savings.com/logo/1490289.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9620,'id'=>5999,'name'=>'Zales','description'=>'The first Zales store was opened in 1924 in Wichita Falls, Texas by three businessmen, who allowed customers to buy expensive diamond jewelry using a credit plan. There are over 750 stores, located in shopping malls throughout the US and Puerto Rico. The store has expanded its market internationally and online, offering not only jewelry, but also appliances and cameras.

Zales is known for its large inventory of diamond wedding, anniversary, and engagement bands and solitaires. They offer services for designing custom rings selecting the diamond and settings. They have special collections like the Colors of Romance Birthstone Collection in other gemstones available in rings, necklaces, bracelets, and earrings. 

The store offers Anne Klein and Movado watches accented with diamonds. Other popular items include men\'s watches, personalized sterling silver charm bracelets, and ID bracelets for children. Some stores carry previously owned restored jewelry.

If you are in the market for loose diamonds for investment purposes or a gift for that special love in your life look to Zales. Savings.com is your best source for a <a href=\"http://www.zales.com\">Zales coupon</a>. With so many special occasions on the calendar, you should have no problem using the Zales coupons we offer online.

Zales sometimes offers coupons like this one:<br><a href=\"http://cdn.savings.com/img/Zales-Coupon.png\"><img src=\"http://cdn.savings.com/img/Zales-Coupon.png\" alt=\"0\" border=\"0\" width=\"100\" alt=”Zales”></a>','displayUrl'=>'http://www.zales.com/','imageUrl'=>'http://cdn.savings.com/logo/714755.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9621,'id'=>299268,'name'=>'ZAMZUU','description'=>'','displayUrl'=>'http://www.GetFreeWebsiteNow.com','imageUrl'=>'http://cdn.savings.com/logo/2605258.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>9622,'id'=>5056,'name'=>'Zappos','description'=>'*While Savings.com is a coupon and deal site, we do not provide customers with Zappos coupons. Zappos.com does not provide coupons to their customers. Instead, they focus on providing the world\'s best customer service as well as an enormous selection of shoes, handbags, and apparel online. In addition, Zappos.com always provides their customers with free shipping and hassle free returns. To Zappos.com, the value of the wonderful customer service they provide far outweighs the value of any coupon they could offer to their customers.*<br><br>

Zappos.com was founded in 1999 in San Francisco by Nick Swinmurn. After an afternoon of frustrating shoe shopping at a local mall, Nick decided to launch the first company that specialized in selling shoes online. He wanted to create an online shoe store that would offer such a wide variety of styles, colors, brands, and sizes that everyone would come away finding the shoes they wanted. From women\'s shoes and men\'s shoes to kids\' shoes, Zappos was created to provide customers with all the online shoe options they could imagine.<br><br>

Zappos.com has grown enormously quickly due to their dedication to customer service and customer satisfaction. Zappos is well known in the online shoe shopping community for their superior customer service and for their fantastic selection of shoes, handbags, and apparel. Zappos also provides free shipping and exchanges to their customers. Not only does Zappos provide free shipping, but they provide fast, free shipping. All of the products that Zappos.com sells come from their own warehouse, so when you buy a pair of shoes online, Zappos has the ability to ship your order out very quickly. Zappos.com will never sell a pair of shoes online (or any other merchandise, for that matter) unless the merchandise physically exists in their warehouse, thereby alleviated the issue of slow delivery due to items being out of stock.<br><br>

Whether you\'re on the hunt for women\'s shoes, men\'s shoes, or kids\' shoes, Zappos.com is the place to shop for shoes online. From sandals and loafers to dress shoes and athletic shoes, Zappos.com has the largest selection of shoes online, not to mention their fantastic selection of clothing, eyewear, handbags, and accessories. Zappos.com provides eyewear, clothing, accessories, and shoes online from top brands and designers like Aerosoles, Nine West, Alexander McQueen, Pastry, Adidas, Puma, New Balance, and oh, so many others.<br><br>

Make <a href=\"http://www.zappos.com\">Zappos.com</a> your first top for shopping for shoes online. You\'re bound to find the perfect pair for any occasion.','displayUrl'=>'http://www.zappos.com','imageUrl'=>'http://cdn.savings.com/logo/2652.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9623,'id'=>291510,'name'=>'Zara','description'=>'','displayUrl'=>'http://zara.com/','imageUrl'=>'http://cdn.savings.com/logo/1705147.gif','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>9624,'id'=>206120,'name'=>'Zazzle','description'=>'Zazzle was started in 2005 to provide custom, on-demand products for savvy shoppers.  Their retail platform allows users to customize existing products as well as create their own.  With a wide variety of apparel and accessories items (t-shirts, sweatshirts, hoodies, aprons, tote bags, hats), postage, posters, cards, mugs and more combined with numerous style and color options customized with your choice of logo, image, design or saying, Zazzle offers billions of one-of-a-kind items which can be made in 24 hours.  They feature numerous collections of images and logos from pop culture franchises you know and love like Star Wars, Disney, Looneytunes, Barbie, South Park, Garfield, Hallmark and Neopets--just to name a few!
<br><br>
With no limits to your creativity or inspiration, Zazzle not only allows you to buy unique, custom-made products, but to SELL them as well.  You can use their product tools to design apparel or fine arts prints or just about anything.  Create your own store, name your price and make money, risk-free with no inventory costs or other overhead.  Whether you\'re designing a unique item for yourself or as a gift or a designer/entrepreneur, Zazzle features the same or better quality than comparable items in a retail store.  Except for the fact that its original design and uniqueness will have no comparable equivalent!  Plus Zazzle offers quick production, speedy shipping, no minimums and volume discounts starting at only two items--as well as a 100% satisfaction or your money back 30 day guarantee.  
<br><br>
Looking to save money on your customized, one-of-a-kind creation?  Try a Zazzle promo code from Savings.com.  At Savings.com, we scour the web to bring you all the best deals and discounts--like our Zazzle coupon codes.  So before you finalize your order at <a href=\"http://www.zazzle.com\">Zazzle.com</a>, stop by Savings.com to get a coupon for Zazzle.','displayUrl'=>'http://www.zazzle.com','imageUrl'=>'http://cdn.savings.com/logo/1661804.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9625,'id'=>238801,'name'=>'Zbattery.com','description'=>'Zbattery.com, Inc. has a technically knowledgeable staff that can help you determine the right battery to meet your needs. Located in St Joseph Michigan its midwest location means faster shipping times to most of the contintental US, even less than 3 days to 2/3 of the country.','displayUrl'=>'http://store.yahoo.com/cgi-bin/clink?zbattery+R98xkH+index.html','imageUrl'=>'http://cdn.savings.com/logo/1178078.png','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>9626,'id'=>210833,'name'=>'zChocolat','description'=>'ZChocolat.com is the online outlet for fine French chocolate! ZChocolat.com was founded on providing ZChocolat.com customers exquisite gourmet quality chocolate on the internet. ZChocolat.com offers ZChocolat.com customers a myriad of gift ideas, including ZChocolat.com photo or engraved gift boxes, hand-made gift wrapping, and 100% cocoa butter based chocolate. ZChocolat.com offers a wide variety of chocolate flavors like earl grey, lavender, orangette, and more. All of ZChocolat.com chocolates are made by award winning chocolatier and ZChocolat.com has been hailed as impeccable chocolate by such critics as Forbes, Food Network and Wall Street Journal. Savings.com is the only source you need for ZChocolat.com online offers, ZChocolat.com specials, ZChocolat.com promotions, and ZChocolat.com coupon codes to get lower prices. Check Savings.com for the latest ZChocolat.com promotional codes, ZChocolat.com code, ZChocolat.com promotional code, and ZChocolat.com codes for deep discounts. Savings.com makes shopping at ZChocolat.com even sweeter!','displayUrl'=>'http://www.zchocolat.com','imageUrl'=>'http://cdn.savings.com/logo/27247.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9627,'id'=>290746,'name'=>'Zebra Billiard Supplies','description'=>'','displayUrl'=>'http://www.zebrabilliards.com','imageUrl'=>'http://cdn.savings.com/logo/1693707.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9628,'id'=>277303,'name'=>'zendough','description'=>'','displayUrl'=>'http://www.zendough.com','imageUrl'=>'http://cdn.savings.com/logo/1664210.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9629,'id'=>313101,'name'=>'Zenfolio','description'=>'','displayUrl'=>'http://www.zenfolio.com/','imageUrl'=>'http://cdn.savings.com/logo/2685717.png','allowPartnerDeals'=>'true','categoryIds'=>20871),
  array('id_index'=>9630,'id'=>278564,'name'=>'ZenMed','description'=>'ZenMed offers holistically based products that treat all types of troubled skin. All products are 100% free of animal testing, animal products, petrochemicals, sodium lauryl, laureth sulfates, dyes, and fragrances. ZenMed designs their products to nurture your skin while also making sure that the environment is not harmed in the process.

They offer products to treat acne, rosacea, eczema/dermatitis, scars and imperfections as well as daily cleansers and supplements that will leave your skin feeling and looking radiant and healthy. The patented Derma Cleanse System will give you a clearer complexion from within by detoxifying and then treating your skin both internally and externally in three easy steps. The Skin Eraser kit removes skin imperfections such as post-Acne discoloration, bumpiness, fine lines, and wrinkles leaving you with a balanced and younger look.

For these and other great products, be sure to check Savings.com often for <a href=\"http://www.zenmed.com\">ZenMed coupons</a> and the latest Zenmed discounts.','displayUrl'=>'http://zenmed.com/','imageUrl'=>'http://cdn.savings.com/logo/1656657.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9631,'id'=>261872,'name'=>'zennioptical.com','description'=>'','displayUrl'=>'http://www.zennioptical.com/','imageUrl'=>'http://cdn.savings.com/logo/1548888.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20858),
  array('id_index'=>9632,'id'=>261617,'name'=>'Zeo Personal Sleep Coach','description'=>'','displayUrl'=>'http://www.myzeo.com/','imageUrl'=>'http://cdn.savings.com/logo/1666399.png','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>9633,'id'=>241643,'name'=>'Zephyr Airsoft','description'=>'Founded in 2004, Zephyr Airsoft offers great prices and customer service for consumers looking for airsoft guns--aka \"BB guns.\"  There are four main categories of guns sold at Zephyr Airsoft:  automatic electric guns or rifles (AEG), spring-powered, gas-powered and CO2-powered.  In addition to airsoft guns, Zephyr Airsoft sells slingshots, BBs and paintballs, military camo apparel, safety gear and accessories.  Whether you\'re a beginner or an expert, Zephyr Airsoft has the equipment and accessories to meet your needs! 
<br><br>
Looking to save some cash on your Zephyr Airsoft purchase?  Try a Zephyr Airsoft coupon from Savings.com.  At Savings.com, we bring you all the best deals and discounts on the web--like our Zephyr Airsoft coupons.  So before you finalize your order at <a href=\"http://www.zephyrairsoft.com/\">ZephyrAirsoft.com</a>, stop by Savings.com for a Zephyr Airsoft coupon.','displayUrl'=>'http://www.zephyrairsoft.com','imageUrl'=>'http://cdn.savings.com/logo/1552250.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9634,'id'=>262001,'name'=>'Zephyr Paintball','description'=>'Founded in 2003, Zephyr Paintball is dedicated to bringing cheap paintball guns, gear and supplies to all paintball aficionados in the U.S. Suit up for a good time with paintball masks, protective gear and, of course, paintballs--Zephyr Paintball\'s extensive inventory insures you\'ll find everything you need to snipe and strike and take out your competition.  Upgrade your paintball gun with barrels, boards, grips, feednecks and more.  Zephyr Paintball carries high-quality brands such as JT Sports, Maddog Designz, Kingman, Tippman and Smart Parts and a complete line of paintball equipment.  Looking to save some money on your Zephyr Paintball purchase?  How about a Zephyr Paintball coupon from Savings.com?  At Savings.com we bring you all the best deals and discounts on the web--so make sure to check us out before you finalize your order at <a href=\"http://www.zephyrpaintball.com/\">ZephyrPaintball.com</a>. Ready, aim, shoot and save with Zephyr Paintball and Zephyr Paintball coupons from Savings.com!','displayUrl'=>'http://www.zephyrpaintball.com','imageUrl'=>'http://cdn.savings.com/logo/1552289.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9635,'id'=>249919,'name'=>'Zerberts','description'=>'','displayUrl'=>'http://www.shopzerberts.com/','imageUrl'=>'http://cdn.savings.com/logo/1483598.png','allowPartnerDeals'=>'true','categoryIds'=>20761),
  array('id_index'=>9636,'id'=>322300,'name'=>'ZERO-G','description'=>'','displayUrl'=>'http://www.gozerog.com','imageUrl'=>'http://cdn.savings.com/logo/2823307.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20228),
  array('id_index'=>9637,'id'=>236625,'name'=>'Zhobby.com','description'=>'','displayUrl'=>'http://www.ZHobby.com','imageUrl'=>'http://cdn.savings.com/logo/720189.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9638,'id'=>241758,'name'=>'Ziamond','description'=>'Ziamond is a website that offers beautiful jewelry for women and men for any occasion, from anniversaries to birthdays to even engagement and wedding rings for unbelievably low prices that everyone can afford, even on the tightest of budgets.

Ziamond sells beautiful and inexpensive cubic zirconia jewelry in a variety of cuts and settings, in 14 and 18 karat gold as well as platinum, in every sort, from pendants and earrings to wedding bands for the big day. 

Ziamond also offers an online live chat help service, where an employee will ask you questions about the type of jewelry you are interested in and for what occasion and will make suggestion and help you find the exact piece you are looking for, no matter what the circumstance.

If you want beautiful jewelry for even less, check for a <a href=\"http://www.ziamond.com\">Ziamond coupon code</a> at Savings.com where you can find a Ziamond coupon that will make your purchase that much better.','displayUrl'=>'http://www.ziamond.com','imageUrl'=>'http://cdn.savings.com/logo/1070091.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9639,'id'=>300793,'name'=>'Zimbrick HONDA','description'=>'','displayUrl'=>'http://www.zimbrickhonda.com','imageUrl'=>'http://cdn.savings.com/logo/2612072.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20888),
  array('id_index'=>9640,'id'=>247003,'name'=>'Zinerrific Magazine Subscriptions','description'=>'','displayUrl'=>'http://www.zinerrific.com/','imageUrl'=>'http://cdn.savings.com/logo/1175435.png','allowPartnerDeals'=>'true','categoryIds'=>20724),
  array('id_index'=>9641,'id'=>229618,'name'=>'Zinio','description'=>'Imagine if you could fit 1,000 books in your backpack, 500 books in your purse, or 200 books in your pocket, at the same time. I know, you\'re asking yourself \"how is that possible?\" The answer, my friends, is Zinio.

We\'ve all heard about e-books... and we think they\'re kind of neat. We\'ve all heard about Kindle... and we think they\'re kind of expensive. Well now you\'re hearing about this innovative new super store.

Zinio is a digital super store for the written word. They have over 50,000 digital magazines and books available in 15 different languages, with more titles added every day. The company is based out of San Francisco and was established in 2001. It has since grown into the largest online news provider in the world.

Membership to this service is free, just pay for what you read. You can even buy back-issues of your favorite magazines. Signing up is a cinch, just enter your name, email address and a few demographics and you can begin reading your favorite books in minutes. The site also features simple navigation making it easy to find your books and magazines if they are available, even the greenest of net users will find it easy to get started.

The coolest feature of this service is their reader apps. These guys provide you with the tools to read their content in many ways using the Zinio Reader. You can download this program to PCs, Macs, iPods, iPhones and iPads, giving you the versatility to read your favorite books wherever you go.

Save trees by reading thousands of books and magazines available at the click of a button. Did you forgot your book at home? Grab it on your iPhone. Just hop online and re-download it. These guys offer a variety of free content as well. Things like PC Magazine, Reader\'s Digest, BusinessWeek, and Art Review to name a few. Find great deals on a variety of digital subscriptions to your favorite magazines.

You can save up to 90% on subscriptions by checking with us at Savings.com. By choosing a Zinio coupon or a <a href=\"http://www.zinio.com\">Zino</a> discount code from us, you can subscribe to popular magazines for less than $1 per issue. Lighten your load, yet still carry a world of knowledge with you wherever you go.','displayUrl'=>'http://www.zinio.com/home?ns=usa','imageUrl'=>'http://cdn.savings.com/logo/619768.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20724),
  array('id_index'=>9642,'id'=>247328,'name'=>'Zip Express Installation','description'=>'Did your computer crash? Zip Express Installation can help. This company performs a series of common, but desirable, technological services. With a focus on installation, they also provide valuable data recovery and backup. Networking, gaming, diagnosis, and repair are all needed services in this technology age. They will also deliver a variety of common technology products, such as TV brackets, speakers, surge protectors, cables, and televisions.

Are you the last one on the block to go wireless? Don\'t worry, Zip Express Installation can set up up your computers, printers and even Wii, so you can utilize the full potential of wireless communication. Is your computer slowing down? Do you have a virus that is preventing you from using your computer? They will run a diagnostic test and get your computer running again.

For the benefit of new customers, there is a very complete list of informative articles about electronic devices, their installation, and equipment needs. For those wanting to keep tabs on these guys there are easy to find links to Blogger, Twitter, Facebook, YouTube, and Flickr.

Customers visiting or scheduling appointments may also create an account for future use. In addition, they feature a link through which customers may contact, and later chat live with, one of the installation consultants. For those service contracts sold in some stores, a customer, with a pre-purchased contract may schedule online here also. Customers also have easy access to the variety of products that these guys sell. Customers should look for free accessory shipping offers.

Zip Express Installation is the best choice for busy electronics buyers and home theater aficionados on the run. By checking for the latest <a href=\"http://www.zipinstallation.com\">Zip Express</a> coupons and Zip Express discounts at Savings.com, you can take full advantage of the very best in deals from this store. There are deals like 15% off of computer, home theater, and TV setup. 

So remember to check out our site and get the deals you need on the computer installation and maintenance services you need and want most from the popular company you trust without having to worry about breaking the bank.','displayUrl'=>'http://www.zipinstallation.com/','imageUrl'=>'http://cdn.savings.com/logo/1497520.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>9643,'id'=>264022,'name'=>'Zipadi Digital Publishing','description'=>'','displayUrl'=>'http://www.zipadi.com/','imageUrl'=>'http://cdn.savings.com/logo/1608890.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>9644,'id'=>300693,'name'=>'Zipit','description'=>'','displayUrl'=>'http://www.zipitzipperbags.com/','imageUrl'=>'http://cdn.savings.com/logo/2611768.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9645,'id'=>262311,'name'=>'Zippo','description'=>'','displayUrl'=>'http://zippo.com/','imageUrl'=>'http://cdn.savings.com/logo/1603217.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20736),
  array('id_index'=>9646,'id'=>312245,'name'=>'ZipRealty','description'=>'','displayUrl'=>'http://www.ziprealty.com/','imageUrl'=>'http://cdn.savings.com/logo/2684159.png','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>9647,'id'=>223361,'name'=>'ZipZoomfly','description'=>'ZipZoomFly launched in 1999 and a mere five years later had excelled in providing quality consumer technology and superior customer service that they were named E-Tailer of the Year award from Intel Corporation and  Bizrate Best of the Best E-tailer.  Their inventory includes a variety of computer components such as backup drives, monitors, motherboards, speakers and headsets and video cards; consumer electronics including camcorders, digital cameras, GPS and MP3 Players; desktop and notebook computers and software.  You\'ll find most items at low discounted prices and your order gets processed quickly because ZipZoomFly lives up to its name by maintaining an in stock inventory, assuring quick delivery of your technology needs.  No need to wait to get the newest gadgets--most orders are shipped within 1-2 business days.
<br><br>
What\'s in a name?  In a word:  quality.  ZipZoomFly stocks top technology brands like Intel, Microsoft, Seagate, Asus, AMD and Hitachi--names you know and trust for your computer component and consumer electronics needs.  And your purchase is covered by a 30 day money back guarantee!  Whether you\'re looking for the latest and most cutting edge in consumer technology or to save a few bucks on a like new open box or quality refurb, you\'ve come to the right site.  Certified by the Better Business Bureau, CNET, Shopping.com and PriceGrabber, ZipZoomFly is your source for quality computers and electronics, low prices and excellent service.
<br><br>
Looking to make your computer component and/or consumer electronics purchase more affordable?  Try a ZipZoomFly coupon code from Savings.com.  At Savings.com, we scour the web to bring you all the best deals and discounts--like our ZipZoomFly coupons.  So before you finalize your order at <a href=\"http://www.zipzoomfly.com\">ZipZoomFly.com</a>, stop by Savings.com for a Zip Zoom Fly coupon.','displayUrl'=>'http://www.zipzoomfly.com','imageUrl'=>'http://cdn.savings.com/logo/1075030.jpeg','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9648,'id'=>5290,'name'=>'Zirh','description'=>'At ZIRH Men\'s Skin Care you can stay fit, stay strong, and have strong skin! ZIRH Men\'s Skin Care is the online source for a luxury line of skin care and treatments at affordable prices. ZIRH Men\'s Skin Care carries tons of ZIRH Men\'s Skin Care products, including ZIRH Men\'s Skin Care Clean Alpha Hydroxy face wash, and ZIRH Men\'s Skin Care Restore to reduce puffiness. ZIRH Men\'s Skin Care proudly carries products to rejuvenate your skin, prep your skin for shaving, protect your skin from the elements, and more, all with the ZIRH Men\'s Skin Care affordable prices. ZIRH Men\'s Skin Care is popular among famous celebrities including Troy Aikman, David Spade, and Marcus Allen. If you\'re in the market for quality care for your skin, ZIRH Men\'s Skin Care is the easy and affordable solution. The next time you\'re shopping for skin care for the whole family, check out Savings.com for an even bigger discount at ZIRH Men\'s Skin Care. Savings.com has the most comprehensive list of ZIRH Men\'s Skin Care rebates, ZIRH Men\'s Skin Care coupons, ZIRH Men\'s Skin Care incentives, ZIRH Men\'s Skin Care deals, and ZIRH Men\'s Skin Care specials. Check Savings.com often for ZIRH Men\'s Skin Care promotional code, ZIRH Men\'s Skin Care codes, ZIRH Men\'s Skin Care promotional codes, and ZIRH Men\'s Skin Care code to save even more. Direct-to-you, Savings.com brings the best discounts for ZIRH Men\'s Skin Care hands down.','displayUrl'=>'http://www.zirh.com','imageUrl'=>'http://cdn.savings.com/logo/27091.gif','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>9649,'id'=>312777,'name'=>'Zoara','description'=>'','displayUrl'=>'http://www.zoara.com/','imageUrl'=>'http://cdn.savings.com/logo/2685127.png','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>9650,'id'=>314616,'name'=>'Zoara Fine Jewelry','description'=>'','displayUrl'=>'http://www.zoara.com/coupons_discounts/military','imageUrl'=>'http://cdn.savings.com/logo/2713048.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>9651,'id'=>223237,'name'=>'Zodiac Watches','description'=>'','displayUrl'=>'https://www.zodiacwatches.com/','imageUrl'=>'http://cdn.savings.com/logo/1140713.png','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>9652,'id'=>250726,'name'=>'Zofunk','description'=>'','displayUrl'=>'http://www.zofunk.com/','imageUrl'=>'http://cdn.savings.com/logo/1494430.png','allowPartnerDeals'=>'true','categoryIds'=>21147),
  array('id_index'=>9653,'id'=>6875,'name'=>'Zone Diet','description'=>'Let Zone Diet help you lose weight by turning your body into a fat burning machine. Created by a medical professional, Zone Diet is one of the nation\'s most successful weight loss solutions. Zone Diet makes it simple and affordable to lose weight the Zone Diet way. Zone Diet gives you food and recipes, online support, motivation, and all of the important Zone Diet information you\'ll need to succeed in losing weight. Zone Diet members get Zone Diet meal planner, thousands of recipes, weight loss tools, and an online community of people losing weight just like you. Only Savings.com brings you premium Zone Diet coupons, Zone Diet online coupons, and Zone Diet super savings. On Savings.com you will find Zone Diet discount coupons, Zone Diet online coupons, and Zone Diet coupon codes for products found at Zone Diet. Zone Diet promotional codes, Zone Diet codes, Zone Diet code, and Zone Diet promotional code are updated daily at Savings.com. Savings.com is the comprehensive source of Zone Diet coupons and discounts.','displayUrl'=>'http://www.zonediet.com/','imageUrl'=>'http://cdn.savings.com/logo/1182113.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9654,'id'=>233052,'name'=>'ZoneAlarm','description'=>'','displayUrl'=>'http://www.zonealarm.com','imageUrl'=>'http://cdn.savings.com/logo/619306.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20826),
  array('id_index'=>9655,'id'=>236922,'name'=>'ZoneTronics.com Wholesale World','description'=>'','displayUrl'=>'http://www.zonetronics.com/usa','imageUrl'=>'http://cdn.savings.com/logo/727381.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9656,'id'=>273789,'name'=>'Zonk Shop','description'=>'','displayUrl'=>'http://www.zonkshop.com/','imageUrl'=>'http://cdn.savings.com/logo/1635541.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9657,'id'=>222456,'name'=>'Zoobooks','description'=>'Zoobooks is the everything-you-wanted-to-know-but-didn\'t-know-where-to-look children\'s resource for animals. Each issue delves into topics such as anatomy, habitat, socialization, and reproduction - all on a single animal or animal group - in a vibrant, easy-to-understand way that helps make learning about animals fun and easy for you and your child. 

The popular series is produced by Wildlife Education, Ltd., a company first established in 1980. Hardcover library editions of the series were first produced in 1983, and the first foreign language translation, in Japanese, appeared in 1985. Presently Zoobooks are available worldwide in any of nine different languages. 

To be sure you are getting the very best discounts possible, remember to check out our site right here at Savings.com for the latest and greatest in valid <a href=\"http://www.zoobooks.com\">Zoobooks coupons</a> and Zoobooks coupon codes and get ready to embark upon an educational adventure in which animals roam freely through your imagination.','displayUrl'=>'http://www.zoobooks.com','imageUrl'=>'http://cdn.savings.com/logo/41049.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9658,'id'=>311709,'name'=>'Zookhooks','description'=>'','displayUrl'=>'http://www.zookhooks.com','imageUrl'=>'http://cdn.savings.com/logo/2714231.gif','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9659,'id'=>282597,'name'=>'Zoosk','description'=>'','displayUrl'=>'http://www.zoosk.com/','imageUrl'=>'http://cdn.savings.com/logo/1661658.png','allowPartnerDeals'=>'true','categoryIds'=>20827),
  array('id_index'=>9660,'id'=>250583,'name'=>'Zowabi Travel','description'=>'','displayUrl'=>'http://zowabitravel.hemitc.com/','imageUrl'=>'http://cdn.savings.com/logo/1494433.png','allowPartnerDeals'=>'true','categoryIds'=>20890),
  array('id_index'=>9661,'id'=>315011,'name'=>'Zoysia Farms Nursery','description'=>'','displayUrl'=>'http://www1.zoysiafarms.com/','imageUrl'=>'http://cdn.savings.com/logo/2817633.png','allowPartnerDeals'=>'true','categoryIds'=>20736),
  array('id_index'=>9662,'id'=>296192,'name'=>'Zozelli','description'=>'','displayUrl'=>'http://www.zozelli.com','imageUrl'=>'http://cdn.savings.com/logo/2051459.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9663,'id'=>250368,'name'=>'ZoZo Music','description'=>'','displayUrl'=>'http://www.zozomusic.com','imageUrl'=>'http://cdn.savings.com/logo/1492925.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9664,'id'=>245397,'name'=>'ZShock.com','description'=>'','displayUrl'=>'http://www.zshock.com','imageUrl'=>'http://cdn.savings.com/logo/1498989.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20217),
  array('id_index'=>9665,'id'=>238493,'name'=>'Ztail.com','description'=>'','displayUrl'=>'http://www.ztail.com/','imageUrl'=>'http://cdn.savings.com/logo/766854.png','allowPartnerDeals'=>'true','categoryIds'=>20211),
  array('id_index'=>9666,'id'=>239543,'name'=>'ZTechSoftware','description'=>'','displayUrl'=>'http://www.ztechsoftware.com','imageUrl'=>'http://cdn.savings.com/logo/946049.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20837),
  array('id_index'=>9667,'id'=>295699,'name'=>'Zu Audio','description'=>'','displayUrl'=>'http://ZUAUDIO.COM','imageUrl'=>'http://cdn.savings.com/logo/1743880.jpeg','allowPartnerDeals'=>'true','categoryIds'=>''),
  array('id_index'=>9668,'id'=>287915,'name'=>'zulily','description'=>'Zulily is a fabulous, stylish online store that offers daily deals up to 90% off regular price on designer apparel, shoes and goodies for both moms and kids. You may have seen them mentioned by Martha Stewart, People Magazine Moms and Babies, USA Today, or the New York Times.

One day the Zulily deal might be for an adorable Widgeon winter coat for your little lady while the next there\'s an unbeatable offer on a unique Sozo infant wear for your little tyke. You might even grab a chic Scout storage system for yourself so you can organize in style or a pair of comfortable. lightweight Crocs for Mom, Dad or the little ones.

You\'ll never know what you\'ll find with a <a href=\"http://www.zulily.com\">Zulily coupon</a> from Savings.com, so be sure to check back often for the latest and greatest Zulily coupons. One thing is certain: you\'ll always find something fun and irresistible.','displayUrl'=>'https://www.zulily.com/','imageUrl'=>'http://cdn.savings.com/logo/1668683.png','allowPartnerDeals'=>'true','categoryIds'=>'Array'),
  array('id_index'=>9669,'id'=>299085,'name'=>'Zuma Office Supply','description'=>'','displayUrl'=>'http://www.ZumaOffice.com/','imageUrl'=>'http://cdn.savings.com/logo/2605533.png','allowPartnerDeals'=>'true','categoryIds'=>20220),
  array('id_index'=>9670,'id'=>306166,'name'=>'Zumali','description'=>'','displayUrl'=>'http://www.zumali.com/','imageUrl'=>'http://cdn.savings.com/logo/2622884.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20856),
  array('id_index'=>9671,'id'=>245334,'name'=>'Zumiez','description'=>'','displayUrl'=>'http://www.zumiez.com/','imageUrl'=>'http://cdn.savings.com/logo/1139078.png','allowPartnerDeals'=>'true','categoryIds'=>20235),
  array('id_index'=>9672,'id'=>308991,'name'=>'Zurchers','description'=>'','displayUrl'=>'http://www.zurchers.com/','imageUrl'=>'http://cdn.savings.com/logo/2628227.png','allowPartnerDeals'=>'true','categoryIds'=>20878),
  array('id_index'=>9673,'id'=>299577,'name'=>'Zuuma Dashboard Mounts','description'=>'','displayUrl'=>'http://myzuuma.myshopify.com/','imageUrl'=>'http://cdn.savings.com/logo/2606462.png','allowPartnerDeals'=>'true','categoryIds'=>20845),
  array('id_index'=>9674,'id'=>238496,'name'=>'Zyrtec','description'=>'Zyrtec is the number prescribed allergy medicine.  One of the reasons that Zyrtec is the first choice for doctors and allergist is that it relieves upper respiratory symptoms caused by both indoor and outdoor allergy triggers.  Zyrtec is as effective against pet dander, dust and mold as it is at preventing reactions to pollen, weeds and grasses.  Zyrtec comes in its original formula and Zyrtec-D which contains a decongestant to help clear up blocked nasal passages.  Zyrtec also offers chewable and liquid versions of its formula for children.  If you\'re not one to let your allergies slow you down, take Zyrtec and love the air.  And to save money on Zyrtec products, look to Savings.com for Zyrtec coupons.','displayUrl'=>'http://www.zyrtec.com','imageUrl'=>'http://cdn.savings.com/logo/766845.gif','allowPartnerDeals'=>'true','categoryIds'=>20734),
  array('id_index'=>9675,'id'=>305938,'name'=>'Zystal Hair','description'=>'','displayUrl'=>'http://www.zystal.com/','imageUrl'=>'http://cdn.savings.com/logo/2622482.jpeg','allowPartnerDeals'=>'true','categoryIds'=>20215),
  array('id_index'=>9676,'id'=>217713,'name'=>'zZounds','description'=>'','displayUrl'=>'http://www.zzounds.com/','imageUrl'=>'http://cdn.savings.com/logo/624649.gif','allowPartnerDeals'=>'true','categoryIds'=>20744)
);
